### PR TITLE
fix: replay edge cases

### LINKED ISSUE #2185: DB went down with replay error when hitting a likely datafusion bug
It seems a Datafusion bug while execute a query lead to IOx replay error

__Steps to reproduce:__
Run the following query in DB `844910ece80be8bc_3c0bd4c89186ca89`

```
SELECT Row_number() 
         OVER ( 
           partition BY Date_trunc('minute', time), bucket_id, partition_id 
           ORDER BY time DESC)    AS rn, 
       gauge, 
       Date_trunc('minute', time) AS time_bucket, 
       env 
FROM   storage_usage_bucket_cardinality 
WHERE  Cast(time AS BIGINT) > Cast(Now() AS BIGINT) - 5 * 60 * 1000000000 
       AND time <= Now(); 
```

We will see the following Datafusion internal error:
`Error running remote query: status: Internal, message: "Internal error reading points from database 844910ece80be8bc_3c0bd4c89186ca89: Internal error executing plan: Arrow error: External error: Arrow error: External error: Arrow error: External error: Execution error: Internal error: Unsupported data type in hasher. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 03 Aug 2021 18:55:08 GMT"} }`
Data Ticket: https://github.com/apache/arrow-datafusion/issues/821

Then `844910ece80be8bc_3c0bd4c89186ca89` also goes down with following error:

```
./scripts/grpcurl -plaintext localhost:1234 influxdata.iox.management.v1.ManagementService.GetServerStatus
.....
{
        "dbName": "844910ece80be8bc_3c0bd4c89186ca89",
        "error": {
          "message": "cannot load catalog: Cannot build replay plan: Minimum sequence number in partition checkpoint (123964015) is lower than database-wide number (183235313) for partition http_api_request_duration_seconds:2021-08-02 08:00:00 and sequencer 0"
        },
        "state": "DATABASE_STATE_RULES_LOADED"
      },
....
```

Update: the DF fusion bug and the replay error may not be related. After I wiped the catalog and ran the query again, I hit the same DF bug but the DB is still up running.

### LINKED ISSUE #2211: Fold DatabaseCheckpoint on Replay
Creating a DatabaseCheckpoint is currently a non-atomic operation, as it needs to iterate through all partitions in the database to find out what writes they have persisted. Additionally the order that the chunks are actually written to object storage is not guaranteed - a DatabaseCheckpoint created earlier might be persisted to the catalog later than another.

These two aspects combined make it incorrect to take the last DatabaseCheckpoint in the catalog. Instead it is necessary to fold all the DatabaseCheckpoints together to determine the replay range, by taking the max of the mins and the max of the maximums.

It should be valid to take the last DatabaseCheckpoint in each partition, as determined by the same chunk order used to determine deduplication (#1963), but this may be a pointless optimisation.

### PR DESCRIPTION
**Pull request by crepererum**
Slightly edited since the first proposal: Now only focused on the question of sorting partition and database checkpoints. See docstring on the why (not) and how.

Closes #2211.

### CODE REVIEW

File: persistence_windows/src/checkpoint.rs [hunk 1]
```diff
@@ -482,6 +584,41 @@ impl DatabaseCheckpoint {
...
+
+    /// Fold in given checkpoint to determine final result (aka last known state).
+    pub fn fold(&mut self, other: &Self) {
+        for (sequencer_id, min_max) in &other.sequencer_numbers {
+            match self.sequencer_numbers.entry(*sequencer_id) {
+                Vacant(v) => {
+                    v.insert(*min_max);
+                }
+                Occupied(mut o) => {
+                    let existing_min_max = o.get_mut();
```
Comment (tustvold) [inline persistence_windows/src/checkpoint.rs:596]: I think it would be easier to understand what is going on if it broke out the cases explicitly.

It could first deduce which has the highest maximum (confusingly this isn't necessarily the one with the largest minimum due to the non-atomicity of DatabaseCheckpoint creation).

If this larger max checkpoint has no minimum, the result is None

If it has a minumum and the other checkpoint doesn't, the result is this minimum

If they both have a minimum, the result is the max of the minimums

File: persistence_windows/src/checkpoint.rs [hunk 2]
```diff
@@ -814,6 +1050,54 @@ mod tests {
         assert_eq!(dckpt, db_ckpt!({1 => (Some(10), 20), 2 => (None, 15)}));
     }
 
+    #[test]
+    fn test_database_checkpoint_fold() {
+        let mut dckpt = db_ckpt!({
+            1 => (Some(10), 20),
+            2 => (None, 15),
+            3 => (None, u64::MAX),
```
Comment (tustvold) [inline persistence_windows/src/checkpoint.rs:1058]: I think if we're overflowing u64 we're going to be having other problems :laughing:

File: persistence_windows/src/checkpoint.rs [hunk 3]
```diff
@@ -814,6 +1050,54 @@ mod tests {
         assert_eq!(dckpt, db_ckpt!({1 => (Some(10), 20), 2 => (None, 15)}));
     }
 
+    #[test]
+    fn test_database_checkpoint_fold() {
```
Comment (tustvold) [inline persistence_windows/src/checkpoint.rs:1054]: Given the implementation adds +1, I think it would be helpful to check with seqno deltas greater than 1, just to ensure the correct codepath is actually being exercised.

File: persistence_windows/src/checkpoint.rs [hunk 4]
```diff
@@ -887,57 +1171,76 @@ mod tests {
...
+                        2 => (Some(22), 26),
+                        3 => (Some(35), 39),
+                        8 => (None, 80),
+                        9 => (Some(89), 90),
+                        10 => (None, 101),
+                        11 => (Some(110), 111)
+                    }
+                ),
+                &db_ckpt!({
+                    1 => (Some(11), 20),
```
Comment (tustvold) [inline persistence_windows/src/checkpoint.rs:1219]: I'm surprised this isn't an error - the database checkpoint is missing the sequencer id 2 in the partition checkpoint

File: persistence_windows/src/min_max_sequence.rs [hunk 5]
```diff
@@ -77,6 +115,27 @@ impl std::fmt::Display for OptionalMinMaxSequence {
     }
 }
 
+impl PartialOrd for OptionalMinMaxSequence {
+    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
+        // upcast min values so that we can use `u64::MAX + 1`
```
Comment (tustvold) [inline persistence_windows/src/min_max_sequence.rs:120]: As above, I think I'd prefer if this broke out the cases explicitly than relying on adding 1 to the minimums. i.e. establish the one with the larger maximum and then compare the minimums in light of this.

I don't think this logic is wrong, but it is making my head hurt trying to convince myself it is correct

File: server/src/db/replay.rs [hunk 6]
```diff
@@ -1703,6 +1702,85 @@ mod tests {
         .await;
     }
 
+    #[tokio::test]
+    async fn replay_works_with_checkpoints_all_full_persisted_2() {
```
Comment (tustvold) [inline server/src/db/replay.rs:1706]: Is this testing some particular edge case that I'm missing?

**Review by tustvold — APPROVED** [review]
This has to be up there with the most brain-melty PRs I've ever reviewed (through no fault of your own). I think the logic is correct, but comparing nullable ranges is pretty confusing...

File: parquet_file/src/catalog.rs [hunk 7]
```diff
@@ -152,6 +152,19 @@ pub enum Error {
         path: DirsAndFileName,
     },
 
+    #[snafu(
+        display(
+            "Using checkpoints from {:?} leads to broken replay plan: {}",
```
Comment (alamb) [inline parquet_file/src/catalog.rs:157]: As a user, what should I do in this case? Is it an internal error  (aka nothing i can do)? If so perhaps we can add that to the error message like 

"Internal Error: Using checkpoints..."

File: persistence_windows/src/checkpoint.rs [hunk 8]
```diff
@@ -303,6 +304,9 @@ pub enum Error {
         partition_key: Arc<str>,
         sequencer_id: u32,
     },
+
+    #[snafu(display("Partition checkpoint order is undetermined"))]
```
Comment (alamb) [inline persistence_windows/src/checkpoint.rs:308]: It would be great to also include some additional information here about what to do / how to fix this error (if possible). As it is this error seems to report that something is wrong but I would have no idea how to fix it

File: persistence_windows/src/checkpoint.rs [hunk 9]
```diff
@@ -411,6 +423,67 @@ impl PartitionCheckpoint {
     }
 }
 
+impl PartialOrd for PartitionCheckpoint {
+    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
```
[the remark this answers is not in the document]
Comment (alamb) [reply persistence_windows/src/checkpoint.rs:427]: Can we please document the intent of this function?

Specificially, a docstring in English that describes the definition of the conditions that makes one `PartitionCheckpoint` come before another? I am particularly interested in the intent when there are multiple sequencers

File: persistence_windows/src/checkpoint.rs [hunk 10]
```diff
@@ -796,6 +939,99 @@ mod tests {
         );
     }
 
+    #[test]
+    fn test_partition_checkpoint_partial_cmp() {
```
Comment (alamb) [inline persistence_windows/src/checkpoint.rs:943]: ❤️  thank you for this

File: persistence_windows/src/checkpoint.rs [hunk 11]
```diff
@@ -796,6 +939,99 @@ mod tests {
...
+        // compare based on sequence numbers
+        assert_eq!(
+            part_ckpt!("table_1", "partition_1", {1 => (None, 0)})
+                .partial_cmp(&part_ckpt!("table_1", "partition_1", {1 => (None, 1)})),
+            Some(Ordering::Less),
+        );
+        assert_eq!(
+            part_ckpt!("table_1", "partition_1", {1 => (Some(1), 1)})
+                .partial_cmp(&part_ckpt!("table_1", "partition_1", {1 => (Some(0), 2)})),
+            None,
```
Comment (alamb) [inline persistence_windows/src/checkpoint.rs:1016]: I don't understand why partitions can't be compared (returns `None`) -- they both have a valid sequencer and min/max sequence numbers

**Review by alamb — COMMENTED** [review]
I think this is very nicely comments / coded @crepererum  👍 

At the moment, I don't feel like my mental model is sufficient for me to understand if this code is implementing the right thing because I don't understand what the right thing should be. Perhaps we can have a brief meeting to discuss what is intended  (or maybe documentation of the definition of partition checkpoint comparison would be sufficient).

File: persistence_windows/src/checkpoint.rs (hunk 1 above)
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs:596]: I don't find your description easier to understand TBH

File: parquet_file/src/catalog.rs (hunk 7 above)
Comment (crepererum) [reply parquet_file/src/catalog.rs]: done

File: persistence_windows/src/checkpoint.rs (hunk 8 above)
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs]: Added a note that this is a bug. The thing is: it cannot be handled in a (semi-)automated way, otherwise I would handle it. The catalog data is broken :shrug:

File: persistence_windows/src/checkpoint.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs:427]: @tustvold good catch, I'm about to fix that in #2229 (the effect of this bug can even be checked w/o the ordering check just by looking at the pruning).

File: persistence_windows/src/checkpoint.rs (hunk 8 above)
Comment (alamb) [reply persistence_windows/src/checkpoint.rs]: Makes sense -- I think the new errors are clear that something is wrong that the operator can not fix. 👍

File: persistence_windows/src/checkpoint.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs:438]: @alamb added more docs.

File: persistence_windows/src/checkpoint.rs (hunk 3 above)
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs:1065]: done

File: persistence_windows/src/checkpoint.rs (hunk 4 above)
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs:1239]: We could check that as well, but I don't see how we would mess up that. Both ckpts are created by `PersistCheckpointBuilder::build` and stored in the same file. If we really wanna have more checks for the checkpoints that are stored side-by-side, I would like to add them in a follow-up PR.

File: persistence_windows/src/checkpoint.rs (hunk 11 above)
Comment (crepererum) [reply persistence_windows/src/checkpoint.rs:1027]: The `OptionalMinMaxSequence` cannot be compared, because the ranges `[1,1]` and `[0,2]` cannot be compared (bot min and max should agree on a "direction").

File: server/src/db/replay.rs (hunk 6 above)
Comment (crepererum) [reply server/src/db/replay.rs:1706]: added some comments, the edge case is that we provoke that the DB checkpoints are stored in the wrong order within the last catalog checkpoint, which will forget the last sequence number (3) and the fact that we've fully persisted partition A

File: persistence_windows/src/checkpoint.rs [hunk 12]
```diff
@@ -340,6 +344,24 @@ pub type Result<T, E = Error> = std::result::Result<T, E>;
 /// Number          min sequence              max sequence
 ///```
 ///
+///
+/// # Ordering
```
Comment (alamb) [inline persistence_windows/src/checkpoint.rs:348]: This is great -- I learned a lot 👍

File: persistence_windows/src/checkpoint.rs [hunk 13]
```diff
@@ -340,6 +344,24 @@ pub type Result<T, E = Error> = std::result::Result<T, E>;
...
+/// Partition checkpoints for the same partition are guaranteed to be created in-sequence because their creation
+/// requires a [`FlushHandle`](crate::persistence_windows::FlushHandle). Two checkpoints can therefore be compared if:
+///
+/// 1. **same table/partition:** They belong to the same table and partition. Only equality is allowed, the strings are
+///    NOT ordered.
+/// 2. **same or larger sequencer set:** Sequencers can only be added but never removed, so either both checkpoints
+///   present the same set of sequencers or one has strictly more sequencers than the other.
+/// 3. **range comparable:** For all matchin sequencers, the [`OptionalMinMaxSequence`] must be comparable.
```
Comment (alamb) [inline persistence_windows/src/checkpoint.rs:356]:
```suggestion
/// 3. **range comparable:** For all matching sequencers, the [`OptionalMinMaxSequence`] must be comparable.
```

File: persistence_windows/src/checkpoint.rs (hunk 11 above)
Comment (alamb) [reply persistence_windows/src/checkpoint.rs:1027]: Thank you for this explanation. The new doc comment on `PartitionCheckpoint` also helps. 👍

**Review by alamb — APPROVED** [review]

**Comment by crepererum** [comment]
@tustvold I'll try to make the comparison code more beautiful in a follow-up PR
