### PR TITLE
fix: ensure querier cache is refreshed for partition sort key

### LINKED ISSUE #4631: Querier panics "Sorted/persisted chunk without partition id"
```text
level=error msg="Thread panic" panic_info="panicked at 'Sorted/persisted chunk without partition id', query/src/provider.rs:625:32" target="panic_logging" location="panic_logging/src/lib.rs:107" time=1652857442531832389
thread 'IOx Query Executor Thread' panicked at 'Sorted/persisted chunk without partition id', query/src/provider.rs:625:32
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
   3: core::panicking::panic_str
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:1852:5
   5: core::option::Option<T>::expect
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:715:21
   6: query::provider::Deduplicater::sort_key_of_overlapped_chunks
             at ./influxdb_iox/query/src/provider.rs:625:13
   7: query::provider::Deduplicater::chunks_dedup_sort_key
             at ./influxdb_iox/query/src/provider.rs:581:21
   8: query::provider::Deduplicater::build_scan_plan
             at ./influxdb_iox/query/src/provider.rs:471:45
   9: <query::provider::ChunkTableProvider as datafusion::datasource::datasource::TableProvider>::scan::{{closure}}
             at ./influxdb_iox/query/src/provider.rs:285:20
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  12: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:390:64
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  15: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:675:88
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  18: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:726:88
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  21: datafusion::physical_plan::planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:621:84
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  24: <datafusion::physical_plan::planner::DefaultPhysicalPlanner as datafusion::physical_plan::planner::PhysicalPlanner>::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/physical_plan/planner.rs:327:70
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  27: <query::exec::context::IOxQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:83:63
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  29: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  30: datafusion::execution::context::SessionState::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/execution/context.rs:1418:58
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  32: datafusion::execution::context::SessionContext::create_physical_plan::{{closure}}
             at ./usr/local/cargo/git/checkouts/arrow-datafusion-71ae82d9dec9a01c/5c89c3b/datafusion/core/src/execution/context.rs:879:56
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  34: query::exec::context::IOxSessionContext::prepare_plan::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:295:66
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  36: query::exec::context::IOxSessionContext::to_series_and_groups::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/query/src/exec/context.rs:403:64
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  38: executor::DedicatedExecutor::spawn::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:232:35
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  40: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
  41: executor::Task::run::{{closure}}::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/select.rs:507:49
  42: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/future/poll_fn.rs:38:9
  43: executor::Task::run::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:43:9
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  45: executor::DedicatedExecutor::new::{{closure}}::{{closure}}::{{closure}}
             at ./influxdb_iox/executor/src/lib.rs:194:35
  46: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  47: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  48: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  49: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  50: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  51: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  52: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  53: std::panicking::try::do_call
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  54: std::panicking::try
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  55: std::panic::catch_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  56: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  59: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  60: tokio::runtime::task::LocalNotified<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
  61: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:431:13
  62: tokio::coop::with_budget::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  63: std::thread::local::LocalKey<T>::try_with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  64: std::thread::local::LocalKey<T>::with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  65: tokio::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  66: tokio::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  67: tokio::runtime::thread_pool::worker::Context::run_task
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  68: tokio::runtime::thread_pool::worker::Context::run
  69: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
  70: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  71: tokio::runtime::thread_pool::worker::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  72: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
  73: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  74: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  75: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  76: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  77: tokio::runtime::task::core::CoreStage<T>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  78: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  79: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  80: std::panicking::try::do_call
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  81: std::panicking::try
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  82: std::panic::catch_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  83: tokio::runtime::task::harness::poll_future
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  84: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  85: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  86: tokio::runtime::task::raw::RawTask::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  87: tokio::runtime::task::UnownedTask<S>::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
  88: tokio::runtime::blocking::pool::Task::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
  89: tokio::runtime::blocking::pool::Inner::run
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  90: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### PR DESCRIPTION
**Pull request by crepererum**
~Includes #4652 (marked as WIP until that one is merged).~

Fixes #4631.

### CODE REVIEW

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 1]
```diff
@@ -159,3 +159,76 @@ async fn table_not_found_on_ingester() {
...
+    let querier_config = TestConfig::new_querier(&ingester_config);
+    let mut cluster = MiniCluster::new()
+        .with_router(router_config)
+        .await
+        .with_ingester(ingester_config)
+        .await
+        .with_querier(querier_config)
+        .await;
+
+    let mut super_long_string = String::new();
```
Comment (alamb) [inline influxdb_iox/tests/end_to_end_cases/querier.rs:183]: is the super long string necessary? If so, why?

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 2]
```diff
@@ -159,3 +159,76 @@ async fn table_not_found_on_ingester() {
...
+    }
+
+    StepTest::new(
+        &mut cluster,
+        vec![
+            // create unpersisted ingester data
+            Step::WriteLineProtocol(format!("{},tag=A val=\"foo\" 1", table_name)),
+            Step::WaitForReadable,
+            Step::AssertNotPersisted,
+            // cache partition in querier w/o any partition sort key (yet)
```
Comment (alamb) [inline influxdb_iox/tests/end_to_end_cases/querier.rs:195]: this is the key, right? That we ran a query prior to persist?

File: querier/src/cache/partition.rs [hunk 3]
```diff
@@ -85,12 +92,44 @@ impl PartitionCache {
         self.cache.get(partition_id).await.sequencer_id
     }
 
-    /// Get sort key
-    pub async fn sort_key(&self, partition_id: PartitionId) -> Option<SortKey> {
-        self.cache.get(partition_id).await.sort_key
+    /// Get sort key.
```
Comment (alamb) [inline querier/src/cache/partition.rs:95]: This is a good workaround for the moment -- I wonder if this could be made explicit (as part of the same mechanism in https://github.com/influxdata/influxdb_iox/pull/4650) to refresh the cache when the ingester says it knows of a larger persisted parquet file than the querier already knows about

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 4]
```diff
@@ -159,3 +159,76 @@ async fn table_not_found_on_ingester() {
...
+        super_long_string.push('x');
+    }
+
+    StepTest::new(
+        &mut cluster,
+        vec![
+            // create unpersisted ingester data
+            Step::WriteLineProtocol(format!("{},tag=A val=\"foo\" 1", table_name)),
+            Step::WaitForReadable,
+            Step::AssertNotPersisted,
```
Comment (alamb) [inline influxdb_iox/tests/end_to_end_cases/querier.rs:194]: 👍  for asserting not persisted -- a comment explaining why that is important might help avoid future coders accidentally removing it

Something like "the test requires the first query run prior to persistence and then the second write causing persistence"

**Review by alamb — APPROVED** [review]
👍  I reviewed commit by commit and the new commits look great

File: influxdb_iox/tests/end_to_end_cases/querier.rs (hunk 1 above)
Comment (alamb) [reply influxdb_iox/tests/end_to_end_cases/querier.rs:183]: I see now it is so that a second write forces persistence -- I think it would be good to add a comment about the rationale for the super long string to help

**Comment by alamb** [comment]
(BTW this is a great testing framework for https://github.com/influxdata/influxdb_iox/pull/4650) -- thank you!

File: influxdb_iox/tests/end_to_end_cases/querier.rs (hunk 2 above)
Comment (crepererum) [reply influxdb_iox/tests/end_to_end_cases/querier.rs:195]: yes

File: querier/src/cache/partition.rs (hunk 3 above)
Comment (crepererum) [reply querier/src/cache/partition.rs:95]: I guess both mechanisms would prevent the bug.

Comment (alamb) [reply querier/src/cache/partition.rs:95]: 👍  I may steal the test ;)

File: influxdb_iox/tests/end_to_end_cases/querier.rs (hunk 1 above)
Comment (crepererum) [reply influxdb_iox/tests/end_to_end_cases/querier.rs:298]: done

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 5]
```diff
@@ -159,3 +159,76 @@ async fn table_not_found_on_ingester() {
     .run()
     .await
 }
+
+#[tokio::test]
+async fn issue_4631() {
```
[the remark this answers is not in the document]
Comment (crepererum) [reply influxdb_iox/tests/end_to_end_cases/querier.rs]: done

File: querier/src/cache/partition.rs [hunk 6]
```diff
@@ -85,12 +92,44 @@ impl PartitionCache {
...
+                match self
+                    .cache
+                    .get(partition_id)
+                    .await
+                    .sort_key
+                    .ok_or(NotFoundError)
+                {
+                    Ok(sort_key) => Ok(sort_key),
+                    Err(e) => {
+                        self.backend.remove_if(&partition_id, |cached_partition| {
```
[the remark this answers is not in the document]
Comment (crepererum) [reply querier/src/cache/partition.rs]: implementation changed

File: querier/src/table/state_reconciler.rs [hunk 7]
```diff
@@ -165,21 +192,74 @@ impl Reconciler {
...
+        for partition_id in all_columns.into_keys() {
+            let sort_key = partition_cache.sort_key(partition_id).await;
+            sort_keys.insert(partition_id, sort_key);
+        }
+
+        // write partition sort keys to chunks
+        chunks
+            .into_iter()
+            .map(|chunk| {
+                if let Some(partition_id) = chunk.partition_id() {
```
Comment (crepererum) [inline querier/src/table/state_reconciler.rs:253]: Actually partition IDs are not optional and the querier will always provide them. There are a bunch of attributes that the query engine marks as optional but then panics if they are `None`. In a follow-up PR, I'll remove a few `Option`s (hopefully).

**Comment by alamb** [comment]
Re-reviewing

**Comment by alamb** [comment]
https://circleci.com/gh/influxdata/influxdb_iox/166239?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

seems to have failed as 

```
thread 'end_to_end_cases::querier::table_not_found_on_ingester' panicked at 'Can not restart server as it is shared', /home/rust/project/test_helpers_end_to_end/src/server_fixture.rs:63:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: test_helpers_end_to_end::server_fixture::ServerFixture::restart_server::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/server_fixture.rs:63:23
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   4: test_helpers_end_to_end::mini_cluster::MiniCluster::restart_ingester::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/mini_cluster.rs:201:34
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
   7: test_helpers_end_to_end::steps::StepTest::run::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/steps.rs:239:34
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   9: end_to_end::end_to_end_cases::querier::table_not_found_on_ingester::{{closure}}
             at ./tests/end_to_end_cases/querier.rs:161:11
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
  12: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:507:48
  13: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  14: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  15: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  16: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  17: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  18: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:507:25
  19: tokio::runtime::basic_scheduler::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:361:19
  20: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:506:36
  21: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:564:57
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  23: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:564:27
  24: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:497:9
  25: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:173:24
  26: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/mod.rs:475:46
  27: end_to_end::end_to_end_cases::querier::table_not_found_on_ingester
             at ./tests/end_to_end_cases/querier.rs:137:5
  28: end_to_end::end_to_end_cases::querier::table_not_found_on_ingester::{{closure}}
             at ./tests/end_to_end_cases/querier.rs:128:7
  29: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    end_to_end_cases::querier::table_not_found_on_ingester

test result: FAILED. 48 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 10.57s

error: test failed, to rerun pass '-p influxdb_iox --test end_to_end'
```

File: querier/src/cache/partition.rs [hunk 8]
```diff
@@ -86,21 +94,42 @@ impl PartitionCache {
     }
 
     /// Get sort key
-    pub async fn sort_key(&self, partition_id: PartitionId) -> Option<SortKey> {
+    pub async fn sort_key(&self, partition_id: PartitionId) -> Arc<Option<SortKey>> {
         self.cache.get(partition_id).await.sort_key
     }
+
+    /// Expire partition if the cached sort key does NOT cover the given set of columns.
```
Comment (alamb) [inline querier/src/cache/partition.rs:101]: 👌

File: querier/src/cache/partition.rs [hunk 9]
```diff
@@ -244,4 +273,73 @@ mod tests {
...
+        assert_histogram_metric_count(&catalog.metric_registry, "partition_get_by_id", 2);
+
+        // expire
+        let p_sort_key = p.partition.sort_key();
+        cache.expire_if_sort_key_does_not_cover(p_id, &HashSet::from([String::from("foo")]));
+        let sort_key = cache.sort_key(p_id).await;
+        assert_eq!(sort_key.as_ref(), &p_sort_key);
+        assert_histogram_metric_count(&catalog.metric_registry, "partition_get_by_id", 3);
+
+        // subsets and the full key don't expire
```
Comment (alamb) [inline querier/src/cache/partition.rs:324]: Nice

File: querier/src/ingester/mod.rs [hunk 10]
```diff
@@ -211,7 +211,7 @@ struct GetPartitionForIngester<'a> {
 }
 
 /// Fetches the partitions for a single ingester
-async fn execute(request: GetPartitionForIngester<'_>) -> Result<Vec<Arc<IngesterPartition>>> {
+async fn execute(request: GetPartitionForIngester<'_>) -> Result<Vec<IngesterPartition>> {
```
Comment (alamb) [inline querier/src/ingester/mod.rs:214]: is there any need to remove the `Arc` here? Or is that just a drive by cleanup? 

Edit: No I see it is because we need to now call `with_partition_sort_key` 👍

**Review by alamb — APPROVED** [review]
LGTM 

I found https://github.com/influxdata/influxdb_iox/pull/4660/files?w=1 showed the changes a bit more concisely

The massaging of the partition sort key is quite unfortunate -- it would be nice to clean that up eventually

**Comment by alamb** [comment]
BTW this PR will substantailly conflict with https://github.com/influxdata/influxdb_iox/pull/4650 -- which is fine, I am just noting it here

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 11]
```diff
@@ -261,3 +261,156 @@ async fn ingester_panic() {
...
+
+#[tokio::test]
+async fn issue_4631_a() {
+    // See https://github.com/influxdata/influxdb_iox/issues/4631
+    //
+    // The symptom was that on rare occasion the querier would panic because the query engine was sure there must be a
+    // partition sort key but the querier did not provide any. For this to happen we need overlapping chunks and all
+    // these chunks must be sorted. This is only the case if all chunks are persisted (i.e. parquet-backed, so no
+    // ingester data). The reason why the querier did NOT provide a partition sort key was because it once got queried
+    // when the partition was fresh and only existed within the ingester, so no partition sort key was calculated yet.
```
[the remark this answers is not in the document]
Comment (NGA-TRAN) [reply influxdb_iox/tests/end_to_end_cases/querier.rs:273]: 👍

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 12]
```diff
@@ -261,3 +261,156 @@ async fn ingester_panic() {
...
+                    "+-----+--------------------------------+-----+",
+                    "| A   | 1970-01-01T00:00:00.000000001Z | bar |",
+                    "+-----+--------------------------------+-----+",
+                ],
+            },
+        ],
+    )
+    .run()
+    .await
+}
```
Comment (NGA-TRAN) [inline influxdb_iox/tests/end_to_end_cases/querier.rs:358]: Wow, what a test. Very nice comments

File: influxdb_iox/tests/end_to_end_cases/querier.rs [hunk 13]
```diff
@@ -261,3 +261,156 @@ async fn ingester_panic() {
...
+                    "+-----+-----+",
+                    "| tag | val |",
+                    "+-----+-----+",
+                    "| A   | bar |",
+                    "| A   | foo |",
+                    "+-----+-----+",
+                ],
+            },
+        ],
+    )
```
Comment (NGA-TRAN) [inline influxdb_iox/tests/end_to_end_cases/querier.rs:413]: 👍

File: querier/src/ingester/mod.rs [hunk 14]
```diff
@@ -543,7 +556,7 @@ impl QueryChunkMeta for IngesterPartition {
     }
 
     fn partition_sort_key(&self) -> Option<&SortKey> {
-        None // data comes from Ingester is not persisted yet and should not yet attached to any catalog partition
+        self.partition_sort_key.as_ref().as_ref()
```
Comment (NGA-TRAN) [inline querier/src/ingester/mod.rs:559]: What is the value of this if nothing is persisted for this partition yet? Is it `Arc<None>` ?

File: querier/src/table/state_reconciler.rs [hunk 15]
```diff
@@ -58,11 +63,33 @@ impl Reconciler {
...
         parquet_files: Vec<ParquetFileWithMetadata>,
     ) -> Result<Vec<Arc<dyn QueryChunk>>, ReconcileError> {
-        let tombstone_exclusion = tombstone_exclude_list(&ingester_partitions, &tombstones);
+        let mut chunks = self
+            .build_parquet_chunks(&ingester_partitions, tombstones, parquet_files)
+            .await?;
+        chunks.extend(self.build_ingester_chunks(ingester_partitions));
+        debug!(num_chunks=%chunks.len(), "Final chunk count after reconcilation");
+
+        let chunks = self.sync_partition_sort_keys(chunks).await;
```
[the remark this answers is not in the document]
Comment (NGA-TRAN) [reply querier/src/table/state_reconciler.rs:76]: As long as you find a more reasonable way to capture and access it, I am all for it

**Review by NGA-TRAN — APPROVED** [review]

File: querier/src/ingester/mod.rs (hunk 14 above)
Comment (crepererum) [reply querier/src/ingester/mod.rs:559]: Yes, `Arc<None>` is used if the DB entry is NULL.
