### PR TITLE
test: Added explain tests for querier. Found and fixed #4468

### LINKED ISSUE #4468: Chunks with same min and max time must be treated as overlaps
__Steps to reproduce:__
```rust
#[test]
    fn one_time_column_overlap_same_min_max() {
        // no full statistics just time min max for NG test
        let c1 = Arc::new(TestChunk::new("chunk1").with_timestamp_min_max(1, 1));    // Note: min = max = 1
        let c2 = Arc::new(TestChunk::new("chunk2").with_timestamp_min_max(1, 1));    // Note: min = max = 1

        let groups = group_potential_duplicates(vec![c1, c2]).expect("grouping succeeded");
        let groups = to_group_query_chunks(groups);

        let expected = vec!["Group 0: [chunk1, chunk2]"];
        assert_groups_eq!(expected, groups);
    }
```
__Expected behaviour:__
chunk1 and chunk2 in the same group (aka overlap) 

__Actual behaviour:__
They are treated as not overlap

### PR DESCRIPTION
**Pull request by NGA-TRAN**
Closes #4468

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

File: querier/src/namespace/query_access.rs [hunk 1]
```diff
@@ -239,32 +241,32 @@ mod tests {
             .await;
 
         partition_cpu_a_1
-            .create_parquet_file("cpu,host=a load=1 11")
+            .create_parquet_file_with_min_max("cpu,host=a load=1 11", 1, 1, 11, 11)
```
Comment (NGA-TRAN) [inline querier/src/namespace/query_access.rs:244]: Explicit set min and max time for testing overlaps

File: querier/src/namespace/query_access.rs [hunk 2]
```diff
@@ -303,13 +305,126 @@ mod tests {
...
+                "|               |                                                                                 |",
+                "+---------------+---------------------------------------------------------------------------------+",
+            ],
+        )
+        .await;
+
+        // -----------
+        // Add an overlapped chunk
+        partition_cpu_a_2
+            .create_parquet_file_with_min_max("cpu,host=a load=14 10001", 2000, 2000, 10001, 10001) // duplicate row with different field value (load=14)
```
Comment (NGA-TRAN) [inline querier/src/namespace/query_access.rs]: found bug #4468 here. This chunk at the chunk it overlaps have min and max time 1001

File: query/src/provider/overlap.rs [hunk 3]
```diff
@@ -166,48 +168,61 @@ where
     let num_chunks = chunks.len();
     let mut grouper = Vec::with_capacity(num_chunks * 2);
 
-    enum StartEnd<I> {
+    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
```
Comment (NGA-TRAN) [inline query/src/provider/overlap.rs:171]: From this line down is the fix and test for #4468

File: querier/src/namespace/query_access.rs [hunk 4]
```diff
@@ -303,13 +305,127 @@ mod tests {
...
+        // -----------
+        // Add an overlapped chunk
+        partition_cpu_a_2
+            // duplicate row with different field value (load=14)
+            .create_parquet_file_with_min_max("cpu,host=a load=14 10001", 2000, 2000, 10001, 10001)
+            .await;
+
+        assert_query(
+            &querier_namespace,
+            "SELECT * FROM cpu", // no meed `order by` because data is sorted before comparing in assert_query
```
Comment (alamb) [inline querier/src/namespace/query_access.rs:369]:
```suggestion
            "SELECT * FROM cpu", // no need `order by` because data is sorted before comparing in assert_query
```

File: querier/src/namespace/query_access.rs [hunk 5]
```diff
@@ -303,13 +305,127 @@ mod tests {
...
+                "|               |             IOxReadFilterNode: table_name=mem, chunks=1 predicate=Predicate     |",
+                "|               |                                                                                 |",
+                "+---------------+---------------------------------------------------------------------------------+",
+            ],
+        )
+        .await;
+
+        // -----------
+        // Add an overlapped chunk
+        partition_cpu_a_2
```
Comment (alamb) [inline querier/src/namespace/query_access.rs:362]:
```suggestion
        // -----------
        // Add an overlapped chunk
        // (overlaps `partition_cpu_a_2`)
        partition_cpu_a_2
```

File: query/src/provider.rs [hunk 6]
```diff
@@ -667,6 +667,7 @@ impl Deduplicater {
     ///  2. vector of non-overlapped chunks, each have duplicates in itself
     ///  3. vectors of non-overlapped chunks without duplicates
     fn split_overlapped_chunks_ng(&mut self, chunks: Vec<Arc<dyn QueryChunk>>) -> Result<()> {
+        debug!("NG plit_overlapped_chunks");
```
Comment (alamb) [inline query/src/provider.rs:670]:
```suggestion
        debug!("NG split_overlapped_chunks");
```

**Review by alamb — APPROVED** [review]
👍  looks good to me
