### PR TITLE
fix: don't update last write time on failed writes

### LINKED ISSUE #1905: Chunks are marked as being written to when they're not
Currently an open chunk's `time_of_last_write` is updated for every write into the chunk, even if that write failed.

https://github.com/influxdata/influxdb_iox/blob/a50c1e75e56d0f8a56696a4ffcb46cfafa252b99/server/src/db.rs#L650-L669

A chunk is movable to the Read Buffer if one of two conditions are met here:

https://github.com/influxdata/influxdb_iox/blob/a50c1e75e56d0f8a56696a4ffcb46cfafa252b99/lifecycle/src/policy.rs#L469-L497

1. The chunk's `row count` is at least `DEFAULT_MUB_ROW_THRESHOLD` (currently hard-coded to 100,000); or
2. The elapsed time between now and the chunk's most recent write is at least as large as the chunk's linger time (currently defaults to `300s`.

### Expected Behaviour

When an open chunk fails to processes new writes it can't move to the RUB based on row count so it should move to the RUB based on becoming "cold" (by no longer successfully processing writes).

TLDR; I think that `time_of_last_write` should be the _time of the last successful write_.

### Actual Behaviour

Open chunks in this state become stuck because they do not have enough rows to move to the RUB but they also are constantly treated as being written to even though the writes fail. I think one example where that could happen is with the schema validation here:

https://github.com/influxdata/influxdb_iox/blob/a50c1e75e56d0f8a56696a4ffcb46cfafa252b99/mutable_buffer/src/chunk.rs#L297-L299

I guess there could be other reasons in the future.

### PR DESCRIPTION
**Pull request by pauldix**
Closes #1905

### CODE REVIEW

File: server/src/db.rs [hunk 1]
```diff
@@ -701,6 +700,7 @@ impl Db {
                             partition.create_open_chunk(mb_chunk);
                         }
                     };
+                    partition.update_last_write_at();
```
Comment (alamb) [inline server/src/db.rs:703]: I was a bit confused at first if this could still get called even when there was an error but I think it is good (and the tests are 👨‍🍳 😗 )

**Review by alamb — APPROVED** [review]
looks good. It took some thinking but I am convinced 👍

File: server/src/db.rs [hunk 2]
```diff
@@ -1733,6 +1733,44 @@ mod tests {
...
+            let chunk = chunk.read();
+
+            (
+                partition.last_write_at(),
+                chunk.time_of_last_write().unwrap(),
+            )
+        };
+
+        let entry = lp_to_entry("cpu bar=true 10");
+        let result = db.store_entry(entry).await;
```
Comment (NGA-TRAN) [inline server/src/db.rs:1762]: What happen here `db.store_entry(entry)`? Nothing is written?

**Review by NGA-TRAN — APPROVED** [review]

File: server/src/db.rs (hunk 2 above)
Comment (alamb) [reply server/src/db.rs:1762]: I think the result is asserted to be an `Err` on the next line

Comment (pauldix) [reply server/src/db.rs:1762]: It returns an error because the type of `bar` changed so nothing is actually written.

File: server/src/db.rs (hunk 1 above)
Comment (pauldix) [reply server/src/db.rs:703]: I wrote the test first to confirm that it would actually fail in these two conditions before I fixed it 😄

Comment (alamb) [reply server/src/db.rs:703]: Testing for the win!
