### PR TITLE
fix: do not overwrite databases

### LINKED ISSUE #643: bug: reusing a database name drops the existing database
__Steps to reproduce:__
1. Create a database named `test`
2. Add some stuff to it
3. Try and create a new database called `test`

__Expected behaviour:__
An "already exists" error or database config update

__Actual behaviour:__
The original database is dropped and a new one is instantiated, success is returned to the caller

### PR DESCRIPTION
**Pull request by domodwyer**
Do not overwrite an existing database when attempting to create a DB with an
existing name.

This should probably update the existing database config, but for the time being
this prevents the existing database from being silently dropped.

Fixes #643

### CODE REVIEW

File: server/src/lib.rs [hunk 1]
```diff
@@ -209,7 +211,16 @@ impl<M: ConnectionManager> Server<M> {
         let db = Db::new(rules, mutable_buffer, read_buffer, wal_buffer, sequence);
 
         let mut config = self.config.write().await;
-        config.databases.insert(db_name, Arc::new(db));
+
+        // If the database already exists, do not overwrite it.
```
Comment (alamb) [inline server/src/lib.rs:215]: I recommend adding a test for this case, mostly as a way to document expected behavior rather than that I have any question that the code does what is intended.

**Review by alamb — APPROVED** [review]
A test would be nice, but not necessary in my opinion

**Review by alamb — APPROVED** [review]
