### PR TITLE
fix: do not forget outputs of file-based write buffer

### LINKED ISSUE #3179: `write_buffer` test `file::tests::test_generic` is flaky
Happens rarely, but is not impossible:

```text
failures:

---- file::tests::test_generic stdout ----
thread 'file::tests::test_generic' panicked at 'assertion failed: `(left == right)`
  left: `Some(Sequence { id: 0, number: 2 })`,
 right: `Some(Sequence { id: 0, number: 1 })`', dml/src/lib.rs:290:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:140:5
   4: dml::test_util::assert_writes_eq
             at /home/rust/project/dml/src/lib.rs:290:9
   5: dml::test_util::assert_write_op_eq
             at /home/rust/project/dml/src/lib.rs:283:39
   6: write_buffer::core::test_utils::test_multi_stream_io::{{closure}}
             at ./src/core.rs:295:9
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
   8: write_buffer::core::test_utils::perform_generic_tests::{{closure}}
             at ./src/core.rs:169:9
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  10: write_buffer::file::tests::test_generic::{{closure}}
             at ./src/file.rs:721:9
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/future.rs:119:9
  13: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:240:62
  14: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:106:9
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:399:16
  16: std::thread::local::LocalKey<T>::with
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/local.rs:375:9
  17: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:99:5
  18: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:76:5
  19: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:240:39
  20: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:349:29
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/macros/scoped_tls.rs:61:9
  22: tokio::runtime::basic_scheduler::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:349:5
  23: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:230:9
  24: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:501:9
  25: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/basic_scheduler.rs:186:24
  26: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/mod.rs:461:46
  27: write_buffer::file::tests::test_generic
             at ./src/file.rs:721:9
  28: write_buffer::file::tests::test_generic::{{closure}}
             at ./src/file.rs:720:11
  29: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    file::tests::test_generic

test result: FAILED. 40 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 13.82s

error: test failed, to rerun pass '-p write_buffer --lib'

Exited with code exit status 101
```

See <https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/12947/workflows/b602f929-257e-4566-b225-c654beee7728/jobs/94659>.

### PR DESCRIPTION
**Pull request by crepererum**
The existing channel construction could lead to cases where streams
would consume messages, put them into the channel but then when the
stream gets dropped the message would be gone forever. So lets move from
a channel-based implementation to directly invoke the generator future,
so this buffering doesn't occur.

Fixes #3179.

### CODE REVIEW

File: write_buffer/src/core.rs [hunk 1]
```diff
@@ -285,7 +285,9 @@ pub mod test_utils {
         let (_sequencer_id, mut stream) = map_pop_first(&mut streams).unwrap();
         assert_write_op_eq(&stream.stream.next().await.unwrap().unwrap(), &w1);
 
-        // re-creating stream after reading remembers offset
+        // re-creating stream after reading remembers offset, but wait a bit to provoke the stream to buffer some
+        // entries
+        tokio::time::sleep(Duration::from_millis(100)).await;
```
Comment (tustvold) [inline write_buffer/src/core.rs:290]: 100 milliseconds seems like quite a long time to wait?

File: write_buffer/src/file.rs [hunk 2]
```diff
@@ -343,11 +342,15 @@ impl WriteBufferReading for FileBufferConsumer {
     }
 }
 
-#[pin_project(PinnedDrop)]
+#[pin_project]
 struct ConsumerStream {
-    join_handle: JoinHandle<()>,
     #[pin]
-    rx: Receiver<Result<DmlOperation, WriteBufferError>>,
+    fut: Option<BoxFuture<'static, Result<DmlOperation, WriteBufferError>>>,
```
Comment (tustvold) [inline write_buffer/src/file.rs:348]: https://docs.rs/tokio-util/0.6.9/tokio_util/sync/struct.ReusableBoxFuture.html could be used here if you're feeling fancy

File: write_buffer/src/file.rs [hunk 3]
```diff
@@ -476,22 +490,32 @@ impl ConsumerStream {
...
     type Item = Result<DmlOperation, WriteBufferError>;
 
     fn poll_next(
         self: Pin<&mut Self>,
         cx: &mut std::task::Context<'_>,
     ) -> std::task::Poll<Option<Self::Item>> {
-        let this = self.project();
-        this.rx.poll_next(cx)
+        let mut this = self.project();
+        if this.fut.is_none() || *this.was_ready {
```
Comment (tustvold) [inline write_buffer/src/file.rs:501]: I'm not sure I understand the need for was_ready and the Option around the future. Unless I'm missing something I'd expect the stream to be created with the future set, this method would then poll the future and if it returns Ready, replace the future prior to returning

File: write_buffer/src/file.rs [hunk 4]
```diff
@@ -476,22 +490,32 @@ impl ConsumerStream {
...
+                this.trace_collector.clone(),
+            ));
+        }
+        let fut = this.fut.as_pin_mut();
+        let fut = fut.expect("just assigned");
+
+        match fut.poll(cx) {
+            std::task::Poll::Ready(res) => {
+                *this.was_ready = true;
+                std::task::Poll::Ready(Some(res))
```
Comment (tustvold) [inline write_buffer/src/file.rs:515]: How does this stream ever finish?

File: write_buffer/src/file.rs (hunk 2 above)
Comment (crepererum) [reply write_buffer/src/file.rs:348]: That one doesn't support "no future yet" aka `None`.

File: write_buffer/src/file.rs (hunk 4 above)
Comment (crepererum) [reply write_buffer/src/file.rs:515]: It doesn't. None of of the write buffer reader streams ever finishes, because you can always add new content to the sequencer.

File: write_buffer/src/file.rs (hunk 3 above)
Comment (crepererum) [reply write_buffer/src/file.rs:501]: I wanted to set the future `Option` to `None` to avoid the additional bool, however I couldn't get this to work with the pinning and esp. w/ `Option::as_pin_mut` which consumes the `Option` so you cannot write to  it afterwards. So I've settled to use two states:

| `Option` | `was_ready` | Situation                                              |
| -------- | ----------- | ------------------------------------------------------ |
| `None`   | `false`     | Stream not polled yet, no work started                 |
| `None`   | `true`      | Cannot happen, but we would treat it as the prev. case |
| `Some`   | `false`     | Future hasn't returned yet, poll it                    |
| `Some`   | `true`      | Future has returned, drop it and create a new one      |

Comment (tustvold) [reply write_buffer/src/file.rs:501]: I don't understand the desire to defer future creation to poll time. Rust futures are lazy so I don't understand why you can't create the future in the streams constructor, and then poll it - and when it returns `Poll::Ready` replace it then (but leave it to the subsequent poll to actually poll it).

This is the approach used by the various stream adapters I have seen, and avoids the need for Option or was_ready?

File: write_buffer/src/core.rs (hunk 1 above)
Comment (crepererum) [reply write_buffer/src/core.rs]: lowered to 10ms

File: write_buffer/src/file.rs (hunk 2 above)
Comment (crepererum) [reply write_buffer/src/file.rs]: done (w/ new design)

File: write_buffer/src/file.rs (hunk 3 above)
Comment (crepererum) [reply write_buffer/src/file.rs]: done, it's way more elegant now

**Review by tustvold — APPROVED** [review]
Is nice :ok_hand:
