### PR TITLE
fix: `persist_row_threshold` limits the out chunk row count

### LINKED ISSUE #1874: bug: Compaction will produce chunks larger than 'persist_row_threshold'
Background: limiting the size of chunks that could be compacted was introduced in https://github.com/influxdata/influxdb_iox/pull/1868

As currently implemented, the code will produce chunks potentially arbitrarily larger than the 'persist_row_threshold' limit

__Steps to reproduce:__
set 'persist_row_threshold' to 100,000 and then load data!

__Expected behaviour:__
is that there will be no chunk that has more than 100,000 rows

__Actual behaviour:__

Fo example, when the 'persist_row_threshold' is set to 100,000 on our internal tools cluster, the current code results in RUB chunks just less than 2x the limit:

```
844910ece80be8bc_3c0bd4c89186ca89> select table_name, row_count from system.chunks where storage = 'ReadBuffer' limit 10;
+------------------------------------+-----------+
| table_name                         | row_count |
+------------------------------------+-----------+
| http_query_response_bytes          | 195587    |
| http_query_response_bytes          | 195591    |
| http_query_response_bytes          | 195557    |
| http_query_response_bytes          | 195730    |
| http_query_response_bytes          | 195730    |
| http_query_response_bytes          | 195615    |
| http_query_response_bytes          | 195790    |
| http_query_response_bytes          | 195522    |
| query_control_all_duration_seconds | 189227    |
| query_control_all_duration_seconds | 190059    |
+------------------------------------+-----------+
Returned 10 rows in 50.347882ms
```

Note that if you change the threshold to over 200k in such a state, the compaction algorithm will attempt to merge an arbitrary number of chunks  together in a single chunk as each chunk individually will have fewer than the persist_row_threshold

__Opining__

I suspect the issue is because the threshold is checked to determine if a chunk should be
(perhaps because the compaction check is performed when the limit is reached)

__Config:__
```
{
  "rules": {
    "name": "844910ece80be8bc_3c0bd4c89186ca89",
    "partitionTemplate": {
      "parts": [
        {
          "time": "%Y-%m-%d %H:00:00"
        }
      ]
    },
    "lifecycleRules": {
      "mutableLingerSeconds": 30,
      "mutableMinimumAgeSeconds": 0,
      "mutableSizeThreshold": "10485760",
      "bufferSizeSoft": "42949672960",
      "bufferSizeHard": "45097156608",
      "dropNonPersisted": true,
      "immutable": false,
      "persist": false,
      "workerBackoffMillis": "100",
      "catalogTransactionsUntilCheckpoint": "100",
      "lateArriveWindowSeconds": 300,
      "persistRowThreshold": "10000000",
      "persistAgeThresholdSeconds": 1800
    },
    "workerCleanupAvgSleep": "500s",
    "writeBufferConnectionString": ""
  }
}
```

### PR DESCRIPTION
**Pull request by crepererum**
`persist_row_threshold` should limit the rows of the post-compaction
output chunk (and hence the sum of rows over the input chunks), not
the number of rows of each individual input chunk.

Fixes #1874.

### CODE REVIEW

File: lifecycle/src/policy.rs [hunk 1]
```diff
@@ -217,9 +217,11 @@ where
                     to_compact.push(chunk);
                 }
                 ChunkStorage::ReadBuffer => {
-                    if chunk.row_count() >= row_threshold {
+                    let row_count = chunk.row_count();
+                    if row_count >= rows_left {
                         continue;
                     }
+                    rows_left -= row_count;
```
Comment (e-dard) [inline lifecycle/src/policy.rs:224]: In release mode if there is a bug in the implementation of `chunk.row_count()` this will cause a quiet underflow. Given we make decisions on `rows_left` I think we should add an assertion here that `row_count >= rows_left`.

What do you think?

**Review by e-dard — APPROVED** [review]
Small suggestion but LGTM 👍

File: lifecycle/src/policy.rs (hunk 1 above)
Comment (crepererum) [reply lifecycle/src/policy.rs]: That assertion is done 3 lines above, aka if `row_count >= rows_left` then don't consider this chunk.

I however changed this subtraction now to `saturated_sub` to make it even safer.

**Review by alamb — APPROVED** [review]
nice tests 👍
