### PR TITLE
fix: Adding tag columns used in a table partition template in a transaction with table creation

### LINKED ISSUE #7871: Race condition theoretically possible with table partition templates and non-tag columns
[Currently, custom partition templates may only use tag columns](https://github.com/influxdata/influxdb_iox/blob/d68a399a7bd1f54df8fa2d04d55a338508cfafc5/mutable_batch/src/payload/partition.rs#L85-L94) (and format the time column).  

This restriction is enforced by, on table creation, going through the tag value columns used in the partition template and creating them as tag columns in the table's schema so that future writes will get an error if they try to send non-tag data in that column.

The table creation catalog request and the column creation catalog requests are not currently happening within a transaction, so there's a small chance that a user who is particularly unlucky and also trying to do something unsupported could have this happen:

> T1: create() table -> OK
> T2: write hits schema validator (runs before partitioner in the router)
> T2: schema upserts my_tag as u64
> T1: attempts to set tag type: columns().create_or_get("my_tag", id, TAG); -> error
> T1: returns error to user
> T2: request hits partitioner, partitioner refuses write, returning an error because the template uses my_tag as a tag column to partition, and it is not a tag.

The fix is making a new catalog function that does both the table creation and column creation in a transaction.

[More context in this comment](https://github.com/influxdata/influxdb_iox/pull/7826#discussion_r1205545031).

### PR DESCRIPTION
**Pull request by carols10cents**
Fixes #7871.

~~Ok @domodwyer I only have this working for Postgres right now,  but a similar change should get sqlite working too.~~ Sqlite is now also using a transaction around table create/column create!

This was a little hairier than just "call a catalog method from another catalog method" because each catalog method is using its own `&mut self.inner` with the `fetch` methods, which doesn't seem to just magically inherit the transaction if the outer method starts a transaction. 

When I didn't have the column's `fetch` methods using the transaction created in the table create method but just called the column create method, the column create query couldn't see the table that was just created in order to associate the columns with that table. (It was confusing to debug because that comes out of `sqlx` as a 'RowNotFound` error, [which we map to `ColumnCreateLimitError`](https://github.com/influxdata/influxdb_iox/blob/2a07b53879c89b87f6af0cc59e85730b43d8d5a0/iox_catalog/src/postgres.rs#L872-L875), and the problem definitely wasn't the column limit 😢 )

So I solved this by extracting the body of the column create method to a function that could also take an `Executor`, which the table creation can call with the transaction and the column create method can call with `self.inner`.

I feel like there's probably a more elegant solution that I'm not seeing right now, but this is where I'm at and I wanted to pass this along in case you want to pick it up while I'm out this week. Please feel free to modify!

### CODE REVIEW

**Review by domodwyer — COMMENTED** [review]
Yeah unfortunately this is what I had in mind! I don't think there's a nicer way around it - extracting is the way to go I think :+1:

FWIW I'm coming at this from the other side, and making the panic a not-panic, so hopefully we'll cover this off in all ways - this atomic schema setup is definitely way nicer for the user/us though, as it prevents an invalid system state from being reached :+1:

Thank you 🙏

File: iox_catalog/src/mem.rs [hunk 1]
```diff
@@ -268,60 +270,76 @@ impl TableRepo for MemTxn {
...
             }
         };
 
-        Ok(table.clone())
+        let table = table.clone();
+
+        // Partitioning is only supported for tags, so create tag columns for all `TagValue`
+        // partition template parts. It's important this happens within the table creation
+        // transaction so that there isn't a possibility of a concurrent write creating these
+        // columns with an unsupported type.
```
Comment (domodwyer) [inline iox_catalog/src/mem.rs:333]: Top comment 👌

**Review by domodwyer — APPROVED** [review]
Perfect! 🚀
