### PR TITLE
fix: Use layered tracing

### LINKED ISSUE #1012: Logs and Tracing
IOx and a number of libraries it depends on make use of [tokio-tracing](https://docs.rs/tracing/0.1.25/tracing/). This allows adding instrumentation of spans and events within the application.

A single global Subscriber can be registered which determines at runtime which instrumentation sites should be enabled, and is notified when they occur.

Having a single-global subscriber is limiting, and the trait is non-trivial to implement, so [tracing-subscriber](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/) provides a way to compose multiple Layers together into a single subscriber. 

We use this to add the following layers:

* An [OpenTelemetry layer](https://docs.rs/tracing-opentelemetry/0.11.0/tracing_opentelemetry/struct.OpenTelemetryLayer.html) that sinks to Jaeger
* An [EnvFilter](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/filter/struct.EnvFilter.html) that enables/disables log sites based on the RUST_LOG environment variable
* A [fmt::Layer](https://docs.rs/tracing-subscriber/0.2.17/tracing_subscriber/fmt/struct.Layer.html) that prints tracing events, along with their parent spans, to stdout

Unfortunately the filtering performed by `EnvFilter` is global to the entire stack of Layers, and this presents an issue as we don't want to log to stdout all the same things we send to jaeger. This is a recognized [issue](https://github.com/tokio-rs/tracing/issues/302) but there doesn't appear to be an official solution to this yet. Progress towards an official solution appears to have [stalled](https://github.com/tokio-rs/tracing/pull/508).

In the short-term we will likely need to create a custom Layer that composes the OpenTelemetry layer, and EnvFilter+fmt::Layer such that the superset of relevant callsites are enabled, but that each only sees the relevant subset of events/spans. When a better solution exists upstream we can switch to that

Note: The terminology used here is pre-0.2 tokio tracing, 0.2 renames a number of these [concepts](https://github.com/tokio-rs/tracing/pull/1015), but has [yet to be released](https://github.com/tokio-rs/tracing/issues/922)

FYI: @jacobmarble

### PR DESCRIPTION
**Pull request by mkmik**
The main issue that was preventing us to use open telemetry / jaeger tracing in IOx (and to close #1012) was the "per layer filtering" issue (see https://github.com/influxdata/influxdb_iox/issues/1012#issuecomment-821291660), whose summary is roughly:

> If we enable both logging and OT tracing, then both the logs and the trace output will be filtered with the intersection of the log and trace filters. We don't want our logs to be accidentally miss events because they are excluded from the tracing filter and we usually want the OT/jaeger tracing system to capture events at a higher verbosity (albeit at lower sample rate) than the logs.

This issue has been worked around in #1681 but it hasn't been plumbed in the IOx tracing configuration (which has been in the meantime factored out in the `trogging` crate.

This PR:

* moves the `filtered_layer` module from the `influxdb_iox` crate into the `trogging` crate, and applies a few fixes to please the more restrictive linter there.
* changes the signature of `FilteredLayer::new` from `new(filter_layer, other_layer)` to just `new(Layer)`. This was needed because all the layers in the trogging config are `Option<Layered>`, and you cannot call `.and_then()` on an `Option<T>`
* change the `trogging` subscriber `builder` to actually use two filtering layers, one for the logs (governed by the `log_filter`) and one for the tracing destinations (governed by the `traces_layer_filter`).

Closes #1012

----

Tested manually:

```console
$ cargo run -- run --traces-sampler traceidratio --log-format full --log-filter info --traces-filter=trace --server-id 1 --traces-exporter jaeger --traces-exporter-jaeger-agent-host localhost --traces-sampler-arg 1 --traces-exporter-jaeger-service-name=fooler
Jun 24 17:05:59.036  INFO influxdb_iox::influxdb_ioxd: InfluxDB IOx server starting git_hash="9ca2a08e1094f2dcf710e077b90af9a07cb61d85" num_cpus=12 build_malloc_conf="\u{0}"
Jun 24 17:05:59.036  WARN influxdb_iox::influxdb_ioxd: NO PERSISTENCE: using Memory for object storage
Jun 24 17:05:59.037  INFO server::init: server ID set server_id=1
Jun 24 17:05:59.038  INFO influxdb_iox::influxdb_ioxd: gRPC server listening bind_address=127.0.0.1:8082
Jun 24 17:05:59.038  INFO influxdb_iox::influxdb_ioxd: HTTP server listening bind_address=127.0.0.1:8080
Jun 24 17:05:59.038  INFO influxdb_iox::influxdb_ioxd: InfluxDB IOx server ready git_hash="9ca2a08e1094f2dcf710e077b90af9a07cb61d85"
Jun 24 17:05:59.078  INFO server_worker: server: started background worker
Jun 24 17:05:59.078  INFO server_worker: server::init: loaded databases, server is initalized
OpenTelemetry trace error occurred ExportFailed(ThriftAgentError(ProtocolError { kind: SizeLimit, message: "jaeger exporter payload size of 4505 bytes over max UDP packet size of 1300 bytes. Try setting a smaller batch size." }))
Jun 24 17:08:03.281  INFO server::db: Found NO existing catalog for DB foobar_weather, creating new one
Jun 24 17:08:03.281  INFO parquet_file::catalog: transaction started tkey=TransactionKey { revision_counter: 0, uuid: c9a63cc3-b4d8-4242-87c9-5df224b9f77a }
Jun 24 17:08:03.282  INFO parquet_file::catalog: transaction committed tkey=TransactionKey { revision_counter: 0, uuid: c9a63cc3-b4d8-4242-87c9-5df224b9f77a }
Jun 24 17:08:03.283  INFO db_worker{database=foobar_weather}: server::db: started background worker
```

image

### CODE REVIEW

File: trogging/src/lib.rs [hunk 1]
```diff
@@ -379,14 +381,20 @@ where
...
-            .with(self.log_filter.unwrap_or(self.default_log_filter))
-            .with(log_format_full)
-            .with(log_format_pretty)
-            .with(log_format_json)
-            .with(log_format_logfmt)
-            .with(traces_layer_otel)
-            .with(traces_layer_filter);
+            .with(FilteredLayer::new(
+                log_filter
+                    .and_then(log_format_full)
```
Comment (alamb) [inline trogging/src/lib.rs:389]: this is cool

**Review by alamb — COMMENTED** [review]
Can you remind me how I would test this (so that I can see logging at one level of verbosity and tracing at another)?

**Review by alamb — APPROVED** [review]
I think the code looks to do what it says, and since you are going to be the one configuring it / debugging it I kind of think "testing in production" is the best way here.

FYI @jacobmarble

**Comment by mkmik** [comment]
> Can you remind me how I would test this (so that I can see logging at one level of verbosity and tracing at another)?

added an example (commands + my output) in the commit description

File: trogging/src/lib.rs [hunk 2]
```diff
@@ -379,14 +381,20 @@ where
...
+
         let subscriber = tracing_subscriber::Registry::default()
-            .with(self.log_filter.unwrap_or(self.default_log_filter))
-            .with(log_format_full)
-            .with(log_format_pretty)
-            .with(log_format_json)
-            .with(log_format_logfmt)
-            .with(traces_layer_otel)
-            .with(traces_layer_filter);
+            .with(FilteredLayer::new(
```
Comment (tustvold) [inline trogging/src/lib.rs:387]: If I'm not mistaken this will enable every callsite, as FilteredLayer does not implement `Layer::enabled` can we at the very least enable a base level filter

**Review by tustvold — CHANGES_REQUESTED** [review]

**Review by e-dard — APPROVED** [review]
LGTM modulo @tustvold's comment.

File: trogging/src/lib.rs (hunk 2 above)
Comment (alamb) [reply trogging/src/lib.rs:387]: What changes are you suggesting?

Comment (mkmik) [reply trogging/src/lib.rs:387]: is it really that expensive though?

I mean, once a callsite is disabled, it goes in a cache, and the cache is consulted anyway for every event. Is the event filter impl that much slower than an access in hashmap? perhaps; should we postpone the judgement if the profiler shows that we're wasting time evaluating the EnvFilter?

Comment (mkmik) [reply trogging/src/lib.rs:387]: I think @tustvold  is suggesting to add a layered to the outer chain that implements
```
pub fn enabled(&self, metadata: &Metadata<'_>) -> bool {
  if metadata is in the very chatty hyper/tokio/h2 modules {
    return false;
  } 
}
```

Comment (tustvold) [reply trogging/src/lib.rs:387]: This is based off my experience with adding access logging to [linkerd-proxy](https://github.com/linkerd/linkerd2-proxy/pull/601) and the concern one of the authors of tokio-tracing has about the performance of unnecessarily enabled callsites. This functionality exists for a reason.

> I mean, once a callsite is disabled, it goes in a cache, and the cache is consulted anyway for every event. Is the event filter impl that much slower than an access in hashmap?

At the very least you are adding a number of lock acquisitions to every callsite, which for futures is every time they are polled. I'm fairly certain this doesn't occur if the span is disabled. Also if memory serves most values will be formatted to strings before determination of whether the data matches filters - so you're adding a load of string allocations and formatting operations as well.

> should we postpone the judgement if the profiler shows that we're wasting time evaluating the EnvFilter?

I'd imagine it would be very hard to visalize this, as the crate is aggressively inlined. It would effectively just make codepaths slower, you wouldn't necessarily see it obviously spending time in tracing. You'd see it spending time in std::fmt and waiting on locks.

> What changes are you suggesting?

I was kind of thinking you'd add a default filter of `info`, but tbh you could also just use a [compile time filter](https://docs.rs/tracing/0.1.26/tracing/level_filters/index.html#compile-time-filters) and keep it simple

Comment (mkmik) [reply trogging/src/lib.rs:387]: > This is based off my experience with adding access logging to linkerd-proxy 

my guess is that linkerd-proxy is dominated by network traffic; we're likely going to have other things eating the cpu.

> I'd imagine it would be very hard to visalize this, as the crate is aggressively inlined.
since dwarf info is used to compute the backtraces (and from the lowlevel structs I was exploring I'm sure that multiple function names can be returned for the same instruction pointer) I would expect this function to show up in the flamegraph

> I was kind of thinking you'd add a default filter of info, but tbh you could also just use a compile time filter and keep it simple

do you mean a default filter of info that drops all debug/trace calls globally or just filtering out the chatty hyper and friends?

As for the compile time filter, that's global right? We currently have `release_max_level_debug` which I plan to raise to `release_max_level_trace`.

Comment (tustvold) [reply trogging/src/lib.rs:387]: > my guess is that linkerd-proxy is dominated by network traffic; we're likely going to have other things eating the cpu.

True, but burning CPU just because we can seems a bit silly :laughing: 

> As for the compile time filter, that's global right? We currently have release_max_level_debug which I plan to raise to release_max_level_trace.

Isn't trace even more verbose than debug?

**Comment by crepererum** [comment]
@mkmik I think GitHub misinterpreted you "fix ..." comment in #1804.

**Comment by mkmik** [comment]
Oh GH, you dummy, I get it that PRs are just issues for you, but beware your leaky abstractions because that's certainly not the right way to fix a PR!

File: trogging/src/lib.rs (hunk 2 above)
Comment (mkmik) [reply trogging/src/lib.rs:415]: ok, implemented the "union filter", so that now this  PR passes the test we added in https://github.com/influxdata/influxdb_iox/pull/1804, which, IIUC, basically encoded your objection.

PTAL

File: trogging/src/layered_tracing.rs [hunk 3]
```diff
@@ -74,6 +77,93 @@ where
...
+    }
+}
+
+impl<S> Layer<S> for UnionFilter<S>
+where
+    S: Subscriber,
+{
+    /// Return the disjunction of all the enabled flags of all the inner filters which are not None.
+    ///
+    /// A None filter doesn't really mean "I want this event", nor it means "I want to filter this event out";
```
Comment (tustvold) [inline trogging/src/layered_tracing.rs:120]: Given it's a `Vec`, why not just not add a filter to the list in such a case?

File: trogging/src/layered_tracing.rs [hunk 4]
```diff
@@ -74,6 +77,93 @@ where
...
+    /// Yet, there is a blanked implementation of `Option<L>` for all `L: Layer`, and its implementation
+    /// if the `enabled()` method returns true. This works because the normal subscriber layer chain
+    /// performs a conjunction of each filter decision.
+    ///
+    /// However, the [`UnionFilter`] here is the opposite, we want to enable processing of one event
+    /// as long as one of the event filters registers interest in it.
+    fn enabled(&self, metadata: &Metadata<'_>, ctx: Context<'_, S>) -> bool {
+        self.inner
+            .iter()
+            .map(|i| match i {
```
Comment (tustvold) [inline trogging/src/layered_tracing.rs:132]: `.any` might be more idiomatic and would short-circuit

**Review by tustvold — APPROVED** [review]
Some minor nits, would be nice to have a test of the UnionFilter also

File: trogging/src/layered_tracing.rs (hunk 4 above)
Comment (mkmik) [reply trogging/src/layered_tracing.rs]: much better; thanks

File: trogging/src/layered_tracing.rs (hunk 3 above)
Comment (mkmik) [reply trogging/src/layered_tracing.rs:135]: explained why the constructor has to keep an option, but filtered out the nones in the constructor so we don't have to do it again in at runtime
