### PR TITLE
fix(router): 0 value retention periods

### LINKED ISSUE #6787: treat retention period of 0 as infinite
Retention periods on a namespace of null are currently treated as infinite. Zero should also be treated as infinite retention throughout all IOx services.

### PR DESCRIPTION
**Pull request by domodwyer**
This maps `0` to `NULL` (meaning "infinite") instead of allowing a retention period of `0` ("keep nothing").

I also added logic to reject negative retention periods in a separate commit, because while it has theoretical meaning, it's very unlikely to have been tested / supported properly in all components at this stage.

I also added router e2e tests that assert the correctness of the high-level interface and the changes it propagates to the catalog. It also highlights the (unresolved) impact of #6175 nicely.

Closes #6787.

---

* fix: map retention period 0 values to NULL (bf6ae3dc4)
      
      Treat a retention period of 0 as "infinite", and not "none".

* fix: reject negative retention periods (ec5b35e3c)
      
      Do not allow a negative retention period to be specified.

* test(router): e2e namespace retention coverage (7f363b55d)
      
      Assert the correct handling of 0 and negative retention periods when
      interacting with the namespace create & update gRPC handlers.

### CODE REVIEW

File: router/tests/grpc.rs [hunk 1]
```diff
@@ -130,3 +131,287 @@ async fn test_namespace_create() {
...
+            assert_eq!(ns.id.get(), got.id);
+            assert_eq!(ns.name, got.name);
+            assert_eq!(ns.retention_period_ns, got.retention_period_ns);
+        });
+    }
+
+    // The cached entry is not affected, and writes continue to be validated
+    // against the old value.
+    //
+    // https://github.com/influxdata/influxdb_iox/issues/6175
```
Comment (alamb) [inline router/tests/grpc.rs:337]: 👍

**Review by alamb — APPROVED** [review]
I reviewed the code and tests carefully and I think this is very nice 👨‍🍳 👌 

Thank you for the tests ❤️ 

I do think we should update the documentation in two place as well to explain that `0` / `none`  means `infinite`

1. The protobuf API definitions. For example:

https://github.com/influxdata/influxdb_iox/blob/c8da5a8e0788335a9d277ef99defa5da78b00feb/generated_types/protos/influxdata/iox/namespace/v1/service.proto#L30-L31

2. The rust client. For example 

https://github.com/influxdata/influxdb_iox/blob/c8da5a8e0788335a9d277ef99defa5da78b00feb/influxdb_iox_client/src/client/namespace.rs#L36-L37

(We could update the docs in another PR as well)

**Comment by domodwyer** [comment]
That's a good catch - I didn't know we had a rust client!

I will PR the changes separately shortly so we can land this ASAP - thank you 🙏
