### PR TITLE
fix: always remember max seen sequ. numbers during replay

### LINKED ISSUE #2215: Replay Restore Fully Persisted Sequencer
It is assumed that consecutive PartitionCheckpoints are monotonically increasing that is:

* Later PartitionCheckpoints have the same or larger min/max seqno for each sequencer id than previous
* Later PartitionCheckpoints have the same or more sequencer ids than previous

This last point is currently not necessarily the case. Consider a scenario with two sequencer ids 0 and 1, and a partition that is fully persisted in sequencer id 0. On replay only writes from sequencer id 1 will be replayed to the partition. If the partition continues to not receive writes from sequencer id 0, it may persist a PartitionCheckpoint having never "seen" a write from sequencer id 0.

At the end of replay, all persistence windows should be "seeded" with the maximum values from their PartitionCheckpoint to ensure that future checkpoints are consistent. (NB: The DatabaseCheckpoint might contain sequencer ids that have never written to this partition, and so it must be the PartitionCheckpoint that is used)

### PR DESCRIPTION
**Pull request by crepererum**
Do not forget max seen sequence numbers for partition-sequencer
combinations that can be skipped during replay.

Fixes #2215.

### CODE REVIEW

File: server/src/db/replay.rs [hunk 1]
```diff
@@ -231,6 +234,32 @@ pub async fn perform_replay(db: &Db, replay_plan: &ReplayPlan) -> Result<()> {
...
+                    .expect("replay plan inconsistent");
+
+                match partition.persistence_windows_mut() {
+                    Some(windows) => {
+                        windows.mark_seen_and_persisted(partition_checkpoint);
+                    }
+                    None => {
+                        let mut windows = PersistenceWindows::new(
+                            partition.addr().clone(),
+                            late_arrival_window,
```
Comment (alamb) [inline server/src/db/replay.rs:254]: Would it cause a problem if the `db_rules` change between when a database is shutdown and when replay is performed? If this type of out of band change would cause a problem, I don't think IOx has to gracefully handle it, but it would be nice if IOx could detect the problem an error quickly (rather than some time later when some other inconsistency surfaces)

File: server/src/db/replay.rs [hunk 2]
```diff
@@ -1925,6 +1954,136 @@ mod tests {
...
+                            "| bar | tag_partition_by | time                           |",
+                            "+-----+------------------+--------------------------------+",
+                            "| 10  | b                | 1970-01-01T00:00:00.000000010Z |",
+                            "| 20  | a                | 1970-01-01T00:00:00.000000020Z |",
+                            "| 30  | a                | 1970-01-01T00:00:00.000000030Z |",
+                            "| 40  | b                | 1970-01-01T00:00:00.000000040Z |",
+                            "+-----+------------------+--------------------------------+",
+                        ],
+                    ),
+                    // no additional chunk for partition a was created
```
Comment (alamb) [inline server/src/db/replay.rs:2068]: 👍  test makes sense to me

**Review by alamb — APPROVED** [review]
The framework for writing replay tests keeps on showing its value 👍  @crepererum

File: server/src/db/replay.rs (hunk 1 above)
Comment (crepererum) [reply server/src/db/replay.rs:254]: The persistence windows are a in-memory concept (i.e. they are not persisted). So updating during shutdown isn't a problem. Updating while the DB is online was done in #2060.
