### PR TITLE
fix(influxql): FILL(linear) for selectors

### LINKED ISSUE #8302: InfluxQL execution error when using FILL(linear) with FIRST, LAST, MIN or MAX functions
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. Load the issue 6112 data set.
2. Attempt to run the following influxql query:

```
SELECT FIRST(usage_idle) FROM cpu WHERE time >= '2022-10-31T02:00:00Z' AND time <= '2022-10-31T02:00:10Z' GROUP BY TIME(2s) FILL(linear);
```

__Expected behaviour:__
This should create a table of results equivalent to (from influxdb 1.8):

```
Name: cpu
┏━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ index ┃         time         ┃    first     ┃
┣━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━┫
┃      1┃2022-10-31T02:00:00Z  ┃  2.9800000000┃
┃      2┃2022-10-31T02:00:02Z  ┃  2.9820000000┃
┃      3┃2022-10-31T02:00:04Z  ┃  2.9840000000┃
┃      4┃2022-10-31T02:00:06Z  ┃  2.9860000000┃
┃      5┃2022-10-31T02:00:08Z  ┃  2.9880000000┃
┃      6┃2022-10-31T02:00:10Z  ┃  2.9900000000┃
┣━━━━━━━┻━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━┫
┃                  3 Columns, 6 Rows, Page 1/1┃
┃                     Table 1/1, Statement 1/1┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

__Actual behaviour:__
The following error is returned:

```
External error: Execution error: unsupported data type Struct([Field { name: "value", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "time", data_type: Timestamp(Nanosecond, None), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]) for interpolation gap filling
```

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.

```
cargo install
```

* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).

```
Darwin 22.5.0 arm64
```

* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

### PR DESCRIPTION
**Pull request by mhilton**
Closes #8302 

Ensure that selector functions such as FIRST, LAST, MIN and MAX can use LINEAR filling in the same way as influxdb 1.8. This is done by explanding the arrays in a StructArray and filling each one individually. For linear filling only the "value" array is filled linearly all other arrays are filled with null. This is consistent with influxdb 1.8.

- [ ] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

File: iox_query/src/exec/gapfill/algo.rs [hunk 1]
```diff
@@ -280,7 +280,7 @@ impl GapFiller {
 
 /// Maintains the state needed to fill gaps in output columns. Also provides methods
 /// for building vectors that build time, group, and aggregate output arrays.
-#[derive(Debug)]
+#[derive(Debug, Clone)]
```
Comment (wolffcm) [inline iox_query/src/exec/gapfill/algo.rs:283]: Rather than implement `Clone` here, can you use the `clone_for_aggr_col` method instead? Values of this type should not be cloned willy-nilly, I don't think, and there are prior uses of this method for similar reasons that you are doing now.

File: iox_query/src/exec/gapfill/algo/interpolate.rs [hunk 2]
```diff
@@ -54,6 +57,38 @@ impl Cursor {
...
+                                &a,
+                            ),
+                            _ => cursor.build_aggr_fill_null(
+                                params,
+                                series_ends,
+                                input_time_array,
+                                &a,
+                            ),
+                        }
+                    })
```
Comment (wolffcm) [inline iox_query/src/exec/gapfill/algo/interpolate.rs:88]: I think that you want to ensure that the state of cursor reflects what `build_aggr_fill_interpolate` does, so it would be good to null-fill all the other columns first with a cloned cursor, and then finish with the `value` column, without cloning.

**Review by wolffcm — CHANGES_REQUESTED** [review]
Thank you Martin!

This looks nice, but I think some more tests are required:
- an end-to-end test using `date_bin_gapfill` in SQL would be good
- add a test to `iox_query/src/exec/gapfill/exec_tests.rs` that also varies input and output batch sizes. This will exercise code that needs to keep state across record batches which will not happen in the end-to-end tests.

File: iox_query/src/exec/gapfill/algo.rs (hunk 1 above)
Comment (mhilton) [reply iox_query/src/exec/gapfill/algo.rs]: Done

File: iox_query/src/exec/gapfill/exec_tests.rs [hunk 3]
```diff
@@ -1018,6 +1033,218 @@ fn test_gapfill_oom() {
...
+                - "| b  | 1970-01-01T00:00:01.075Z | {value: 1350, time: 0, other_0: 13, other_1: 13} |"
+                - "| b  | 1970-01-01T00:00:01.100Z | {value: 1450, time: , other_0: , other_1: }      |"
+                - "| b  | 1970-01-01T00:00:01.125Z | {value: 1550, time: 0, other_0: 14, other_1: 14} |"
+                - +----+--------------------------+--------------------------------------------------+
+                "###)
+            });
+            assert_batch_count(&batches, output_batch_size);
+        }
+    }
+}
```
Comment (wolffcm) [inline iox_query/src/exec/gapfill/exec_tests.rs:1246]: These tests are looking very nice. Thanks for writing them.

I have one more concern and I'm not sure you've covered it here.

The code that does the gap filling makes the assumption that we will have buffered enough input to produce one complete output batch. For most fill strategies we can just look at the number of input rows, but linear interpolation is different. If an aggregate column is sparsely populated (lots of nulls), we need to keep reading input until we find a value in there that can serve as the endpoint of an interpolated segment, or until the series keys change. The logic for that is here:
https://github.com/influxdata/influxdb_iox/blob/f5b5bc9c53f9498f48ad2b56959b1444af27a637/iox_query/src/exec/gapfill/buffered_input.rs#L122

If we are interpolating a struct column, then we need to be specifically looking at the `value` field within the struct. So I think that will need to be updated, and there also should probably be an accompanying test.

**Review by wolffcm — COMMENTED** [review]
This is looking very close. I had one remaining concern. Happy to chat on Monday about if you like as I think parts of this might be kind of subtle.

File: iox_query/src/exec/gapfill/exec_tests.rs [hunk 4]
```diff
@@ -1018,6 +1033,218 @@ fn test_gapfill_oom() {
...
+                - "| a  | 1970-01-01T00:00:01.125Z | {value: , time: }      |"
+                - "| b  |                          | {value: -10, time: 0}  |"
+                - "| b  | 1970-01-01T00:00:00.975Z | {value: 1100, time: 0} |"
+                - "| b  | 1970-01-01T00:00:01Z     | {value: 1200, time: }  |"
+                - "| b  | 1970-01-01T00:00:01.025Z | {value: 1300, time: 0} |"
+                - "| b  | 1970-01-01T00:00:01.050Z | {value: 1325, time: }  |"
+                - "| b  | 1970-01-01T00:00:01.075Z | {value: 1350, time: 0} |"
+                - "| b  | 1970-01-01T00:00:01.100Z | {value: 1450, time: }  |"
+                - "| b  | 1970-01-01T00:00:01.125Z | {value: 1550, time: 0} |"
+                - +----+--------------------------+------------------------+
```
[the remark this answers is not in the document]
Comment (mhilton) [reply iox_query/src/exec/gapfill/exec_tests.rs:1134]: Yes the struct array has null values and the primitive array can also be null. The reason there are no blank rows is that the way the test generates the struct array it always makes the struct non-null, only making the internal arrays null as appropriate.

File: influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected [hunk 5]
```diff
@@ -3124,4 +3124,52 @@ tags: host=
...
+| 2022-10-31T02:00:08 | 99.0  |
+| 2022-10-31T02:00:10 | 2.99  |
++---------------------+-------+
+-- InfluxQL: SELECT FIRST(usage_idle),usage_system FROM cpu WHERE time >= '2022-10-31T02:00:00Z' AND time <= '2022-10-31T02:00:10Z' GROUP BY TIME(2s) FILL(99);
+name: cpu
++---------------------+-------+--------------+
+| time                | first | usage_system |
++---------------------+-------+--------------+
+| 2022-10-31T02:00:00 | 2.98  | 2.2          |
+| 2022-10-31T02:00:02 | 99.0  | 99.0         |
```
Comment (alamb) [inline influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected:3170]: I don't know how influxql works, but it as an outsider it is somewhat strange to see these examples where  `FILL(linear)` applies only to columns with aggregates / selectors but `FILL(99)` applies to all the selected columns.

File: iox_query/src/exec/gapfill/exec_tests.rs (hunk 3 above)
Comment (alamb) [reply iox_query/src/exec/gapfill/exec_tests.rs:1246]: I think this kind of test could be achieved using a dataset similar to what is in this PR with a few more sequential time/struct cols that are `None` /`Null`--  

And then perhaps sets the input / output batch sizes to small values to force the boundary logic:

```
        for output_batch_size in [7,5,1] {
            let input_batch_size = 3;
            let records = TestRecords {
```

**Review by alamb — APPROVED** [review]
I reviewed this code and past comments and I think we should proceed with merging this after adding the additional  test that @wolffcm 
 describes here: https://github.com/influxdata/influxdb_iox/pull/8396#discussion_r1284757060 

Once that test is written (and any code fixes required to get it to pass) then all comments will have been addressed (and I also think the code and tests are looking quite nice -- great job @mhilton )

File: influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected (hunk 5 above)
Comment (mhilton) [reply influxdb_iox/tests/query_tests/cases/in/issue_6112.influxql.expected:3170]: This is consistent with influxql's existing behaviour. I agree it is confusing though.

File: iox_query/src/exec/gapfill/buffered_input.rs [hunk 6]
```diff
@@ -402,4 +472,29 @@ mod tests {
...
+
+        // 6 rows
+        buffered_input.push(batches.pop_front().unwrap());
+        assert!(buffered_input.need_more(batch_size - 1).unwrap());
+
+        // 9 rows (series changes here)
+        buffered_input.push(batches.pop_front().unwrap());
+        assert!(!buffered_input.need_more(batch_size - 1).unwrap());
+    }
 }
```
Comment (mhilton) [inline iox_query/src/exec/gapfill/buffered_input.rs:500]: @alamb This test was intended to cover the case suggested by @wolffcm in [#8396 (comment)](https://github.com/influxdata/influxdb_iox/pull/8396#discussion_r1284757060).

Is there something about it that I've missed?

Comment (alamb) [reply iox_query/src/exec/gapfill/buffered_input.rs:500]: I think think this is good go go!
