### PR TITLE
fix: Return a more helpful error message for no matching sharding rule

### LINKED ISSUE #2127: Unhelpful error message
investigate why a missing match on a sharding rule returns such a unhelpful error message:  https://github.com/influxdata/influxdb_iox/blob/094945a72d529429eceb8a47c2fc19dea1db16a4/tests/end_to_end_cases/write_api.rs#L501

### PR DESCRIPTION
**Pull request by carols10cents**
Fixes #2127.

I went with "failed precondition" because the fix for no matching sharding rule might be to fix the sharding rules or fix the line protocol. Let me know if you'd rather have this send a different tonic status!

### CODE REVIEW

File: tests/end_to_end_cases/write_api.rs [hunk 1]
```diff
@@ -498,7 +498,9 @@ async fn test_write_dev_null() {
 
     assert_eq!(
         err.to_string(),
-        "Unexpected server error: Internal error: Internal Error"
+        "Unexpected server error: The system is not in a state required for the operation's \
+         execution: error converting line protocol to flatbuffers: Error getting shard id No \
```
Comment (alamb) [inline tests/end_to_end_cases/write_api.rs:502]: 👍  for the "no sharding rule matches" 👍

**Review by alamb — APPROVED** [review]
