### PR TITLE
fix: do not loose data when Kafka reports that offset is above watermark

### LINKED ISSUE #5128: Ingester drops more writes than needed when Kafka offset is missing
If the ingester receives a `WriteBufferErrorKind::UnknownSequenceNumber` it concludes that the retention policy may have deleted the data and automatically jumps to the newest entry:

https://github.com/influxdata/influxdb_iox/blob/512f9850ee575c153ebd89ca8f53d7e290f0a410/ingester/src/stream_handler/handler.rs#L242-L263

Kafka (and other write buffers) however have a closed range of known sequence numbers though. The conclusion is only right on the lower end, i.e. if the known range is above the requested sequence number. If the requested sequence number was too new, then this either means we encountered a write buffer bug (e.g. https://github.com/influxdata/rskafka/issues/147 ) or something else is wrong (catalog data is wrong, some manual Kafka operation, ...). In that case we must bubble up the error.

May require https://github.com/influxdata/rskafka/issues/148.

### PR DESCRIPTION
**Pull request by crepererum**
*This can happen in certain cluster rebalance settings.

This is also linked to https://github.com/influxdata/rskafka/issues/147
but for the upstream issue I currently have no idea how to fix it, so
let's at least harden IOx against it.

Fixes #5128.

### CODE REVIEW

**Comment by crepererum** [comment]
Need to fix the tests.

**Comment by alamb** [comment]
@domodwyer  is this something you have time to review?

**Comment by domodwyer** [comment]
Without context it is hard to understand what has changed / what the fix is - maybe it is something I missed while I was off and someone else has better understanding?

**Comment by crepererum** [comment]
@domodwyer the problem is described in https://github.com/influxdata/influxdb_iox/issues/5128#issue-1304671998

File: write_buffer/src/core.rs [hunk 1]
```diff
@@ -38,8 +38,16 @@ impl WriteBufferError {
...
+    pub fn sequence_number_after_watermark(
+        e: impl Into<Box<dyn std::error::Error + Sync + Send>>,
+    ) -> Self {
+        Self::new(WriteBufferErrorKind::SequenceNumberAfterWatermark, e)
+    }
+
+    pub fn sequence_number_no_longer_exists(
+        e: impl Into<Box<dyn std::error::Error + Sync + Send>>,
+    ) -> Self {
+        Self::new(WriteBufferErrorKind::SequenceNumberNoLongerExists, e)
```
Comment (domodwyer) [inline write_buffer/src/core.rs:50]: So the fix is to split the two cases of "unknown watermark" to distinguish between them in the consumer? 

What should the ingester do if it observes `SequenceNumberAfterWatermark`? I'd imagine panic, but currently it just busy-waits in a loop I think.

File: ingester/src/stream_handler/handler.rs [hunk 2]
```diff
@@ -252,7 +252,7 @@ where
 
                     Some(op)
                 }
-                Some(Err(e)) if e.kind() == WriteBufferErrorKind::UnknownSequenceNumber => {
+                Some(Err(e)) if e.kind() == WriteBufferErrorKind::SequenceNumberNoLongerExists => {
```
Comment (domodwyer) [inline ingester/src/stream_handler/handler.rs:255]: It would be good to handle `SequenceNumberAfterWatermark` too - perhaps by panic-ing to attract the humans.

File: write_buffer/src/core.rs (hunk 1 above)
Comment (crepererum) [reply write_buffer/src/core.rs:50]: > So the fix is to split the two cases of "unknown watermark" to distinguish between them in the consumer?

Yes


> What should the ingester do if it observes `SequenceNumberAfterWatermark`? I'd imagine panic, but currently it just busy-waits in a loop I think.

Good call, will fix that :muscle:

Comment (crepererum) [reply write_buffer/src/core.rs:50]: done

File: ingester/src/stream_handler/handler.rs (hunk 2 above)
Comment (crepererum) [reply ingester/src/stream_handler/handler.rs:255]: done

File: ingester/src/stream_handler/handler.rs [hunk 3]
```diff
@@ -309,6 +309,16 @@ where
                     self.seq_invalid_data_count.inc(1);
                     None
                 }
+                Some(Err(e)) if e.kind() == WriteBufferErrorKind::SequenceNumberAfterWatermark => {
+                    panic!(
+                        "\
+Sequencer {:?} stream for topic {} has a high watermark BEFORE the sequence number we want. This is either a but (see \
```
Comment (domodwyer) [inline ingester/src/stream_handler/handler.rs:315]: Where's my butt emoji?!

> This is either a but

**Review by domodwyer — APPROVED** [review]

File: ingester/src/stream_handler/handler.rs (hunk 3 above)
Comment (carols10cents) [reply ingester/src/stream_handler/handler.rs:315]: 🍑

Comment (crepererum) [reply ingester/src/stream_handler/handler.rs]: s/:peach:/:bug:/
