### PR TITLE
fix: make "persist partition" a bit more stable

### LINKED ISSUE #2434: Flaky end to end test: end_to_end_cases::management_api::test_persist_partition
This test, introduced in https://github.com/influxdata/influxdb_iox/pull/2335 by @crepererum I think sometimes fails and then passes on rerun. This happens locally for me as well on circleci

Example 1:
* failed run: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/9791/workflows/70ca6083-aa14-4567-a1a4-c4a00646f03c/jobs/57696
* passed run (same code): https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/9791/workflows/7d9342d5-31c6-45f2-ba91-83aa78726a8e/jobs/57733

Example 2: 
* failed run: https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/9779/workflows/460babeb-759e-4739-a8ae-0d3c0e352b2c/jobs/57581
* passed run (same code): https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/9779/workflows/099dcdb4-354a-4dc4-8335-27aa5dceda71/jobs/57596

Output failure:
```
failures:

---- end_to_end_cases::management_api::test_persist_partition stdout ----
thread 'end_to_end_cases::management_api::test_persist_partition' panicked at 'called `Result::unwrap()` on an `Err` value: LifecycleError(Status { code: FailedPrecondition, message: "Precondition violation influxdata.com/iox - chunk: Cannot perform operation due to wrong chunk lifecycle: ChunkError: Internal Error: A lifecycle action 'Compacting' is already in progress for Chunk('CVfPyfOSca':'data':'data':0)", details: b"\x08\t\x12\xe4\x01Precondition violation influxdata.com/iox - chunk: Cannot perform operation due to wrong chunk lifecycle: ChunkError: Internal Error: A lifecycle action 'Compacting' is already in progress for Chunk('CVfPyfOSca':'data':'data':0)\x1a\x89\x02\n2type.googleapis.com/google.rpc.PreconditionFailure\x12\xd2\x01\n\xcf\x01\n\x05chunk\x12\x12influxdata.com/iox\x1a\xb1\x01Cannot perform operation due to wrong chunk lifecycle: ChunkError: Internal Error: A lifecycle action 'Compacting' is already in progress for Chunk('CVfPyfOSca':'data':'data':0)", metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Sat, 28 Aug 2021 10:12:10 GMT"} }, source: None })', tests/end_to_end_cases/management_api.rs:1372:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1037:23
   4: end_to_end::end_to_end_cases::management_api::test_persist_partition::{{closure}}
             at ./tests/end_to_end_cases/management_api.rs:1369:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/mod.rs:80:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/future/future.rs:119:9
   7: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:208:62
   8: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/coop.rs:106:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:400:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/local.rs:376:9
  11: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/coop.rs:99:5
  12: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/coop.rs:76:5
  13: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:208:39
  14: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:302:29
  15: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/macros/scoped_tls.rs:61:9
  16: tokio::runtime::basic_scheduler::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:302:5
  17: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:197:9
  18: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:448:9
  19: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/basic_scheduler.rs:157:24
  20: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.10.1/src/runtime/mod.rs:450:46
  21: end_to_end::end_to_end_cases::management_api::test_persist_partition
             at ./tests/end_to_end_cases/management_api.rs:1379:5
  22: end_to_end::end_to_end_cases::management_api::test_persist_partition::{{closure}}
             at ./tests/end_to_end_cases/management_api.rs:1331:7
  23: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    end_to_end_cases::management_api::test_persist_partition

test result: FAILED. 102 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.49s

error: test failed, to rerun pass '-p influxdb_iox --test end_to_end'

Exited with code exit status 101
CircleCI received exit code 101
```

### PR DESCRIPTION
**Pull request by crepererum**
- add longer wait times to tests
- exclude chunks that have active lifecycle actions early (instead of
  failing the whole set)
- properly catch the "no chunks" case

Fixes #2434.

### CODE REVIEW

File: server/src/db.rs [hunk 1]
```diff
@@ -747,13 +747,21 @@ impl Db {
                     let chunk = chunk.read();
                     if matches!(chunk.stage(), ChunkStage::Persisted { .. })
                         || (chunk.min_timestamp() > flush_handle.timestamp())
+                        || chunk.lifecycle_action().is_some()
```
Comment (NGA-TRAN) [inline server/src/db.rs:750]: 👍

File: server/src/db.rs [hunk 2]
```diff
@@ -747,13 +747,21 @@ impl Db {
...
                     }
                 })
                 .collect();
+            ensure!(
+                !chunks.is_empty(),
+                CannotFlushPartition {
+                    table_name,
+                    partition_key
+                }
+            );
```
Comment (NGA-TRAN) [inline server/src/db.rs:764]: 👍

**Review by NGA-TRAN — APPROVED** [review]
LGTM
