### PR TITLE
test: add test for gap fill query missing time bounds

### LINKED ISSUE #7330: Gap filling queries return `not implemented` error when there is no range
If you issue a gap filling query without a WHERE clause:
```sql
SELECT
  location,
  DATE_BIN_GAPFILL(INTERVAL '1 minute', time, '1970-01-01T00:00:00Z') AS minute,
  AVG(temp)
FROM temps
GROUP BY LOCATION, MINUTE
```

Then an error occurs:
```
This feature is not implemented: date_bin_gapfill is not yet implemented
```

This is because the `HandleGapFill` planner rule fails with an error (a time range predicate is required). But since the optimizer is configured such that rules that fail will not be fatal, it continues happily on. This particular rule is necessary though because it lowers away `DATE_BIN_GAPFILL` which does not have an actual implementation, instead it's used to create a `GapFill` node.

This issue could be fixed by addressing this issue in DataFusion:
https://github.com/apache/arrow-datafusion/issues/4615

### PR DESCRIPTION
**Pull request by wolffcm**
Closes #7330.

This adds an end-to-end test for user-facing errors when time predicates are omitted from gap fill queries.

This also updates the end-to-end test harness to be able to include user-facing error messages in `.expected` files for SQL end-to-end tests. This same behavior has been in the InfluxQL end-to-end tests for a while.

### CODE REVIEW

File: influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected [hunk 1]
```diff
@@ -51,6 +51,18 @@
 | 2000-05-05T12:40:00Z | 1               |
 | 2000-05-05T12:50:00Z |                 |
 +----------------------+-----------------+
+-- SQL: SELECT region, date_bin_gapfill('10 minute', time) as minute, locf(avg(cpu.user)) from cpu group by region, minute;
+Error while planning query: Optimizer rule 'handle_gap_fill' failed
+caused by
+Error during planning: gap-filling query is missing both upper and lower time bounds
```
Comment (NGA-TRAN) [inline influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected:57]: Since this is user facing error, I wonder whether it is better to only show the high level problem.

```suggestion
Error during planning: gap-filling query is missing both upper and lower time bounds
```

Comment (wolffcm) [reply influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected:57]: I would prefer this too actually. The prefix is added by DataFusion:
https://github.com/apache/arrow-datafusion/blob/8ffb4853db7415fe84456aec820be8f2a8fb4a06/datafusion/optimizer/src/optimizer.rs#L306-L311

I recently changed it to use `Context` instead of `Internal` but I did not remove the context altogether.

A lot of our user-facing errors have context that is not all that relevant to the user, it would be nice to clean it up. I wonder if there is a way to do so programmatically?

Comment (NGA-TRAN) [reply influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected:57]: Maybe a change in DF to provide an option for us to choose whether we want to receive the context message or not?

Comment (wolffcm) [reply influxdb_iox/tests/query_tests2/cases/in/gapfill.sql.expected:57]: I just wonder if rather than the complexity of an option we should be doing something like:
- The logical planner runs, and produces an error
- That error is `Context("rule failed <some rule>", Plan(<user-facing message>))`
- It seems like in this case we can unwrap and discard the context on the IOx side.

Since we often want that context if it is an internal error.
