### PR TITLE
fix: handle recursing limit in querier<>ingester comm 

### LINKED ISSUE #5974: Querier<>Ingester filter expr: recursion limit
Freshly from prod:

`Failed ingester query '.....': Failed to perform flight request: Invalid query, could not convert protobuf: Violation for field "exprs": Error creating Expr from bytes: Error during planning: Error decoding expr as protobuf: failed to decode Protobuf message: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: BinaryExprNode.r: LogicalExprNode.expr_type: BinaryExprNode.l: LogicalExprNode.expr_type: recursion limit reached`

We should probably not send an expression it all if it is too complex. I'm trying to isolate the query that was responsible for it.

### PR DESCRIPTION
**Pull request by crepererum**
I wanted to create a proper end2end test, but it's really hard to balance the gRPC recursion limit with real stack sizes in debug builds. Mostly DF is overflowing in debug builds when converting a too-nested SQL expression to a logical expression. I gave up, the test would be too flaky, so I've added a more direct test.

Closes #5974

### CODE REVIEW

File: querier/src/ingester/flight_client.rs [hunk 1]
```diff
@@ -189,3 +205,48 @@ impl CachedConnection {
...
+    #[test]
+    fn serialize_deeply_nested_predicate() {
+        // see https://github.com/influxdata/influxdb_iox/issues/5974
+
+        // we need more stack space so this doesn't overflow in dev builds
+        std::thread::Builder::new().stack_size(10_000_000).spawn(|| {
+            // don't know what "too much" is, so let's slowly try to increase complexity
+            let n_max = 100;
+
+            for n in 1..n_max {
```
Comment (alamb) [inline querier/src/ingester/flight_client.rs:225]: I wonder if we really need to try all 1 .. n_max combinations. It seems like simply making an expression with 100 (n_max) is probably sufficient

File: querier/src/ingester/flight_client.rs [hunk 2]
```diff
@@ -100,14 +100,30 @@ impl FlightClient for FlightClientImpl {
...
-        let request: proto::IngesterQueryRequest =
-            request.try_into().context(CreatingRequestSnafu)?;
+        let request = serialize_ingester_query_request(request)?;
 
         let perform_query = client.perform_query(request).await.context(FlightSnafu)?;
         Ok(Box::new(perform_query))
     }
 }
 
+fn serialize_ingester_query_request(
```
[the remark this answers is not in the document]
Comment (alamb) [reply querier/src/ingester/flight_client.rs:110]: For what it is worth, I filed https://github.com/apache/arrow-datafusion/issues/4066 to track an improvement in datafusion to actually support deeply nested AND / OR expressions

File: querier/src/ingester/flight_client.rs (hunk 1 above)
Comment (crepererum) [reply querier/src/ingester/flight_client.rs]: done
