### PR TITLE
fix: Remove partition_id from metric attributes

### LINKED ISSUE #4026: Excessive metric cardinality for `influxdb_iox_job` metrics
The `influxdb_iox_job_.*` metrics are responsible for a large amount of metrics:

Compare:

```console
$ kubectl -exec -ti svc/iox-shared-ingester-0 -c telegraf -- bash -c 'apk add curl >/dev/null; curl -sLf localhost:8080/metrics | wc -c'
4030655
$ kubectl exec -ti svc/iox-shared-ingester-0 -c telegraf -- bash -c 'apk add curl >/dev/null; curl -sLf localhost:8080/metrics | grep -v influxdb_iox_job_ | wc -c'
171404
```

More detailed breakdown:

```console
$ kubectl exec -ti svc/iox-shared-ingester-0 -c telegraf -- bash -c 'apk add curl >/dev/null; curl -sLf localhost:8080/metrics | awk -F"{" "{print \$1}" | sort | uniq -c | sort -n'
      3 http_request_duration_seconds_count
      3 http_request_duration_seconds_sum
      4 http_requests_total
      6 jemalloc_memstats_bytes
     14 catalog_op_duration_ms_count
     14 catalog_op_duration_ms_sum
     25 write_buffer_last_ingest_ts
     25 write_buffer_last_max_ts
     25 write_buffer_last_min_ts
     25 write_buffer_last_sequence_number
     25 write_buffer_read_bytes_total
     25 write_buffer_sequence_number_lag
     36 http_request_duration_seconds_bucket
     75 write_buffer_ingest_request_duration_seconds_count
     75 write_buffer_ingest_request_duration_seconds_sum
     75 write_buffer_ingest_requests_total
    168 catalog_op_duration_ms_bucket
    900 write_buffer_ingest_request_duration_seconds_bucket
   2084 influxdb_iox_job_completed_cpu_seconds_count
   2084 influxdb_iox_job_completed_cpu_seconds_sum
   2084 influxdb_iox_job_completed_wall_seconds_count
   2084 influxdb_iox_job_completed_wall_seconds_sum
   2084 influxdb_iox_job_count
  12504 influxdb_iox_job_completed_cpu_seconds_bucket
  12504 influxdb_iox_job_completed_wall_seconds_bucket
```

Exemplar:

```
influxdb_iox_job_completed_cpu_seconds_sum{name="persist",partition_id="118990",status="Success"} 0.000038231
```

---

Perhaps we should remove the `partition_id` label?

### PR DESCRIPTION
**Pull request by mkmik**
Closes #4026

### CODE REVIEW

File: ingester/src/job.rs [hunk 1]
```diff
@@ -65,11 +65,5 @@ impl JobRegistry {
...
 
 fn f_attributes(job: &Job) -> metric::Attributes {
-    let mut attributes = metric::Attributes::from(&[("name", job.name())]);
-
-    if let Some(partition_id) = job.partition_id() {
-        attributes.insert("partition_id", partition_id.get().to_string());
-    }
-
-    attributes
+    etric::Attributes::from(&[("name", job.name())])
```
Comment (crepererum) [inline ingester/src/job.rs:68]:
```suggestion
    metric::Attributes::from(&[("name", job.name())])
```

**Review by crepererum — APPROVED** [review]
