### PR TITLE
test: Record number of Parquet files before a write

### LINKED ISSUE #6506: Flaky test: `end_to_end_cases::querier::kafkaless_rpc_write::basic_on_parquet`
Example in https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/27431/workflows/95af4f59-5560-4d30-bded-fd2d987a186f/jobs/245010 :

```text
thread 'end_to_end_cases::querier::kafkaless_rpc_write::basic_on_parquet' panicked at 'did not get additional Parquet files in the catalog: Elapsed(())', /home/rust/project/test_helpers_end_to_end/src/client.rs:148:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::expect
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1070:23
   4: test_helpers_end_to_end::client::wait_for_new_parquet_file::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/client.rs:124:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   6: test_helpers_end_to_end::steps::StepTest::run::{{closure}}
             at /home/rust/project/test_helpers_end_to_end/src/steps.rs:205:21
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   8: end_to_end::end_to_end_cases::querier::kafkaless_rpc_write::basic_on_parquet::{{closure}}
             at ./tests/end_to_end_cases/querier.rs:922:9
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/future.rs:124:9
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:57
  12: tokio::runtime::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  13: tokio::runtime::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  14: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:531:25
  15: tokio::runtime::scheduler::current_thread::Context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:340:19
  16: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:530:36
  17: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:57
  18: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/macros/scoped_tls.rs:61:9
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:601:27
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:520:19
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/current_thread.rs:154:24
  22: tokio::runtime::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:279:47
  23: end_to_end::end_to_end_cases::querier::kafkaless_rpc_write::basic_on_parquet
             at ./tests/end_to_end_cases/querier.rs:901:9
  24: end_to_end::end_to_end_cases::querier::kafkaless_rpc_write::basic_on_parquet::{{closure}}
             at ./tests/end_to_end_cases/querier.rs:892:11
  25: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
```

### PR DESCRIPTION
**Pull request by carols10cents**
Fixes #6506.

Also has the pleasant side effect of making this code simpler and less hacky-- it now checks the number of Parquet files for the whole namespace, which is useful in cases where the line protocol writes to several tables.

### CODE REVIEW

File: test_helpers_end_to_end/src/steps.rs [hunk 1]
```diff
@@ -169,6 +227,9 @@ impl<'a> StepTest<'a> {
                         "====Begin writing line protocol to v2 HTTP API:\n{}",
                         line_protocol
                     );
+                    // Get the current number of Parquet files in the cluster's namespace before
+                    // starting a new write so we can observe a change when waiting for persistence.
+                    state.record_num_parquet_files().await;
```
Comment (crepererum) [inline test_helpers_end_to_end/src/steps.rs:232]: I think this should be an extra test step, because someone may call `WriteLineProtocol` twice in a row just to simulate two write requests. In that case the test should probably record this state before the two write requests and not twice.

File: test_helpers_end_to_end/src/steps.rs [hunk 2]
```diff
@@ -193,17 +254,10 @@ impl<'a> StepTest<'a> {
                     }
                     info!("====Done waiting for all write tokens to be persisted");
                 }
-                Step::WaitForPersisted2 { table_name } => {
```
Comment (crepererum) [inline test_helpers_end_to_end/src/steps.rs:196]: So this technique works, but doesn't this render the current write tokens useless? Do we have a tracking issue to get the write tokens back to work (they are required by some of our IDPE integration tests).

File: test_helpers_end_to_end/src/steps.rs (hunk 1 above)
Comment (carols10cents) [reply test_helpers_end_to_end/src/steps.rs:232]: Yeah, I've been thinking about this, and if the write is writing to 2 tables then we should be waiting for 2 parquet files, not just a change... so I'll fix and make the recording a separate step as well.

File: test_helpers_end_to_end/src/steps.rs (hunk 2 above)
Comment (carols10cents) [reply test_helpers_end_to_end/src/steps.rs:196]: [In this issue](https://github.com/influxdata/influxdb_iox/issues/6444) @domodwyer said the write tokens are not relevant to the RPC write path, so there's no current plan to reimplement.

Comment (crepererum) [reply test_helpers_end_to_end/src/steps.rs:196]: Had a quick look at the issue in question. The important bit is:

> As writes now have no TTBR lag

So I think IDPE can now work w/o the token :+1:

**Review by crepererum — APPROVED** [review]
Thank you! :)
