### PR TITLE
fix: Ensure mutable_linger_seconds can not be None

### LINKED ISSUE #1899: Not dropping old data when crossing the soft limit
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. create a database with a a soft of limit S and a hard limit of H
2. write data until the db holds more than S bytes.

__Expected behaviour:__

The DB should stabilize around S bytes before hitting H, or at try hard to not reach the hard limit.

__Actual behaviour:__

Server is almost idle, while rejecting all incoming writes with  `influxdata.com/iox/buffer: hard buffer limit reached`

While emitting only this in the logs:

```
soft limited exceeded, but no chunks found that can be evicted. Check lifecycle rules
```

### PR DESCRIPTION
**Pull request by mkmik**
Follow up cleanup PR: https://github.com/influxdata/influxdb_iox/pull/1917 (no longer make mutable_linger_seconds an option and move the defaulting to the configuration layer)

Closes #1899
Closes https://github.com/influxdata/influxdb_iox/issues/1914

### CODE REVIEW

File: lifecycle/src/policy.rs [hunk 1]
```diff
@@ -944,6 +941,31 @@ mod tests {
         let chunk = TestChunk::new(0, None, None, ChunkStorage::OpenMutableBuffer)
             .with_row_count(DEFAULT_MUB_ROW_THRESHOLD - 1);
         assert!(!can_move(&rules, &chunk, from_secs(0)));
+
+        // Also check that a "None" linger time is treated like a zero.
```
Comment (alamb) [inline lifecycle/src/policy.rs:945]:
```suggestion
```
I think this comment is now out of date

**Review by alamb — APPROVED** [review]

**Review by e-dard — APPROVED** [review]
LGTM 👍

File: lifecycle/src/policy.rs (hunk 1 above)
Comment (mkmik) [reply lifecycle/src/policy.rs]: good catch; removed
