### PR TITLE
fix: update clap parser for --ingester-addresses

### LINKED ISSUE #6719: Querier2: Invalid URI: invalid authority
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. run a query against querier2

__Actual behaviour:__

```
level=warn msg="request encountered non-fatal error - backing off" error="Failed ingester query 'iox-shared-ingester-0.iox-shared-ingester:8082,iox-shared-ingester-1.iox-shared-ingester:8082,iox-shared-ingester-2.iox-shared-ingester:8082': Failed to connect to ingester 'iox-shared-ingester-0.iox-shared-ingester:8082,iox-shared-ingester-1.iox-shared-ingester:8082,iox-shared-ingester-2.iox-shared-ingester:8082': Invalid URI: invalid authority" task_name="ingester request" backoff_secs=0 target="backoff" location="backoff/src/lib.rs:179" time=1674749357723693344
level=warn msg="Circuit open, not contacting ingester" ingester_address=iox-shared-ingester-0.iox-shared-ingester:8082,iox-shared-ingester-1.iox-shared-ingester:8082,iox-shared-ingester-2.iox-shared-ingester:8082 target="querier::ingester::circuit_breaker" location="querier/src/ingester/circuit_breaker.rs:306" time=1674749357825327620
level=warn msg="Could not connect to ingester, circuit broken" ingester_address=iox-shared-ingester-0.iox-shared-ingester:8082,iox-shared-ingester-1.iox-shared-ingester:8082,iox-shared-ingester-2.iox-shared-ingester:8082 namespace_id=246 table_id=125 target="querier::ingester" location="querier/src/ingester/mod.rs:507" time=1674749357825348073
```

The circuit breaker never opens and thus the data buffered in the ingesters is never returned.

__Expected behaviour:__

I expect the querier to return fresh data from the ingesters.

__Environment info:__

Reproduced on stag03 and stag101.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__

### PR DESCRIPTION
**Pull request by wolffcm**
Closes #6719

I found two separate issues here:
- We weren't parsing the `INGESTER_ADDRESSES` arguments properly because `clap` needs `num_args` and `value_delimiter` specified to populate a vector.
- ~~It seems like `INFLUXDB_IOX_INGESTER_ADDRESSES` is populated with `host:port` (and no `http://`) for the router, so I updated the querier's arg handling to follow suit.~~

### CODE REVIEW

File: clap_blocks/src/ingest_replica.rs [hunk 1]
```diff
@@ -7,17 +7,19 @@ pub struct IngestReplicaConfig {
...
     /// for multiple addresses.
     #[clap(
         long = "ingester-addresses",
         env = "INFLUXDB_IOX_INGESTER_ADDRESSES",
-        required = true
+        required = true,
+        num_args=1..,
+        value_delimiter = ','
     )]
     pub ingester_addresses: Vec<String>,
```
Comment (wolffcm) [inline clap_blocks/src/ingest_replica.rs:24]: This argument does not seem to actually be used when I follow it.

File: clap_blocks/src/router2.rs [hunk 2]
```diff
@@ -24,17 +24,19 @@ pub struct Router2Config {
...
     /// for multiple addresses.
     #[clap(
         long = "ingester-addresses",
         env = "INFLUXDB_IOX_INGESTER_ADDRESSES",
-        required = true
+        required = true,
+        num_args=1..,
+        value_delimiter = ','
     )]
     pub ingester_addresses: Vec<String>,
```
Comment (wolffcm) [inline clap_blocks/src/router2.rs:41]: Previously this vector was always a single element. However, the router immediately tries to join it here anyway:
https://github.com/influxdata/influxdb_iox/blob/5ef9018f7e31f5a8510c747268cce7112dfa66c4/ioxd_router/src/lib.rs#L287

So this change will have no effect, but should prevent confusion in the future.

File: ioxd_ingest_replica/src/lib.rs [hunk 3]
```diff
@@ -143,13 +143,13 @@ pub async fn create_ingest_replica_server_type(
...
-        Arc::clone(&metrics),
-    )
-    .await?;
+    let ingester_addresses = ingest_replica_config
+        .ingester_addresses
+        .clone()
+        .into_iter()
+        .map(|addr| format!("http://{}", addr))
+        .collect();
+    let grpc = ingest_replica::new(catalog, ingester_addresses, exec, Arc::clone(&metrics)).await?;
```
Comment (wolffcm) [inline ioxd_ingest_replica/src/lib.rs:152]: The ingester addresses don't appear to actually be used here, I made this change to prevent future confusion.

**Comment by carols10cents** [comment]
I think this also fixes https://github.com/influxdata/influxdb_iox/issues/6417 and https://github.com/influxdata/influxdb_iox/issues/6418 ?

**Comment by wolffcm** [comment]
> I think this also fixes https://github.com/influxdata/influxdb_iox/issues/6417 and https://github.com/influxdata/influxdb_iox/issues/6418 ?

That sounds right to me.

I am finding that tests are failing in CI (even though they pass when I run them locally), and I think it's because `test_helpers_end_to_end` populates `INGESTER_ADDRESSES` differently for the router vs the querier, and this fix is breaking that.

File: test_helpers_end_to_end/src/config.rs [hunk 4]
```diff
@@ -157,7 +157,11 @@ impl TestConfig {
 
         Self::new_querier2_without_ingester2(ingester_config).with_env(
             "INFLUXDB_IOX_INGESTER_ADDRESSES",
-            ingester_config.ingester_base().as_ref(),
+            ingester_config
+                .addrs()
+                .ingester_grpc_api()
+                .bind_addr()
+                .as_ref(),
```
Comment (wolffcm) [inline test_helpers_end_to_end/src/config.rs:164]: query2 now expects ingester addresses not to have `http://`.

File: clap_blocks/src/querier.rs [hunk 5]
```diff
@@ -204,14 +204,14 @@ pub struct QuerierConfig {
...
+    /// "127.0.0.1:8083"
     ///
     /// or
     ///
-    /// "http://10.10.10.1:8083,http://10.10.10.2:8083"
+    /// "10.10.10.1:8083,10.10.10.2:8083"
     ///
     /// for multiple addresses.
-    #[clap(long = "ingester-addresses", env = "INFLUXDB_IOX_INGESTER_ADDRESSES")]
+    #[clap(long = "ingester-addresses", env = "INFLUXDB_IOX_INGESTER_ADDRESSES", num_args=1.., value_delimiter = ',')]
```
Comment (alamb) [inline clap_blocks/src/querier.rs:214]: It looks like @mkmik changed the values of INFLUXDB_IOX_INGESTER_ADDRESSES in December  https://github.com/influxdata/k8s-idpe/commit/9cb9646a7f2f3982dfa40ee8a130bdb7d89c6429

So I don't really know what changed recently

To be honest I think it actually makes sense to have the config specify http/https rather than IOx assuming http, but I don't have a strong opinion on the matter. 

It looks like the values in `INFLUXDB_IOX_SHARD_TO_INGESTERS` (which was the old setting?) still relies on `http://` style addresses
https://github.com/influxdata/k8s-idpe/blob/3be75fb9820e7430eddedb8f97d9e6992d80675b/apps/iox/components/iox/querier.libsonnet#L16-L59

Comment (alamb) [reply clap_blocks/src/querier.rs:214]: TIL clap takes arguments like `1..` https://docs.rs/clap/latest/clap/builder/struct.Arg.html#method.num_args

File: ioxd_ingest_replica/src/lib.rs (hunk 3 above)
Comment (alamb) [reply ioxd_ingest_replica/src/lib.rs:152]: I think the ingester replica was copy/pasted version of the ingester / router. I don't understand what it is for

**Review by alamb — APPROVED** [review]
I think this PR does what it says and has nice coverage -- thank you @wolffcm 

I am somewhat confused about parameters and handling and all the various way to configure things, but I think that will be transient after we remove the old ingerster?

File: test_helpers_end_to_end/src/config.rs (hunk 4 above)
Comment (mkmik) [reply test_helpers_end_to_end/src/config.rs:164]: What's wrong with requiring actual urls to be provided by the caller? 

Ideally we should exit with an error at startup if the ingester addresses are malformed instead of handling the problem at run-time with a warning.

The main advantage of forcing the caller to specify the URL instead of slapping http is that we could support other schemes in the future like https

Comment (mkmik) [reply test_helpers_end_to_end/src/config.rs:164]: FWIW https://github.com/influxdata/influxdb_iox/blob/main/ingester2/README.md has an example of router2 invocation using `http://`. If we change this let's change that doc too. (I prefer not changing the doc and make the code enforce explicit http:// + fixing k8s_idpe to pass http)

Comment (wolffcm) [reply test_helpers_end_to_end/src/config.rs:164]: > What's wrong with requiring actual urls to be provided by the caller?

I thought about that, but the  `INFLUXDB_IOX_INGESTER_ADDRESSES` setting is shared across the router and the querier in the jsonnet that generates deployments. It wasn't the router that was broken, it was the querier, so I brought the latter in line with the former.

Longer term we might consider it but that would require coordinating a change in this repo with one in k8s-idpe.

Comment (wolffcm) [reply test_helpers_end_to_end/src/config.rs:164]: > I prefer not changing the doc and make the code enforce explicit http:// + fixing k8s_idpe to pass http

Do you think that `--ingester-addresses` for router2 and the querier2 should be the same? If so, then the doc will need to change either way, since the parameters for the two apps do not agree.

Side note: I am a little unclear on what the router actually does. I guess it routes incoming write requests to the right ingester?

Is there a way to make the change to require `http://` in the config for router2 but coordinate it with a change in k8s-idpe so that it doesn't create an outage? I am unclear on how to do that.

This area is pretty new to me so I don't have a sense of which is best but I am happy to go that route with some guidance.

Comment (mkmik) [reply test_helpers_end_to_end/src/config.rs:164]: @wolffcm perhaps something like this https://github.com/influxdata/k8s-idpe/pull/15587 can handle the temporary divergence of router2 from querier2

Comment (wolffcm) [reply test_helpers_end_to_end/src/config.rs:164]: Ok, yes, that makes sense. It also decouples the `clap` parser change from the URL prefix change. I will update this PR in a bit.

**Review by mkmik — APPROVED** [review]

**Comment by mkmik** [comment]
Will we do address validation in another PR?

**Comment by wolffcm** [comment]
> Will we do address validation in another PR?

You mean that the querier (and the router for that matter) should ensure that it's arguments are valid by hitting a `/health` endpoint or something? I will file an issue for it.

**Comment by mkmik** [comment]
> > Will we do address validation in another PR?
> 
> You mean that the querier (and the router for that matter) should ensure that it's arguments are valid by hitting a `/health` endpoint or something? I will file an issue for it.

no I mean something simpler: we should reject invalid values right when parsing arguments. The easiest way to catch a configuration issue is to have it blow up right in your face right when you start the binary. k8s rollouts will be automatically stopped if the binary crashloops immediately; no fancy healthchecks are required

**Comment by wolffcm** [comment]
Got it, I'll put up a separate PR to check the URL when parsing arguments tomorrow.
