### PR TITLE
fix: avoid user error for unsupported querier<>ingester preds

### LINKED ISSUE #6195: Confusing error message for unsupported subquery: Error during planning: Error encoding expr as protobuf: General error: Proto serialization error: Expr::ScalarSubquery(_) | Expr::InSubquery { .. } | Expr::Exists { .. }
@bpalani  reports that running the following query in IOx when trying out EXISTS based on https://arrow.apache.org/datafusion/user-guide/sql/subqueries.html#exists gets the error below:

```sql
select count(*) from http_request where exists (select req_bytes from http_request 
where time - now() - interval '4 hour')
```

Results in 
```
error executing SQL query: Error while planning query: External error: Error getting partitions from ingester: Failed ingester query 'http://iox-shared-ingester-1:8082/': Internal error creating flight request : Violation for field "exprs": Error converting Expr to bytes: Error during planning: Error encoding expr as protobuf: General error: Proto serialization error: Expr::ScalarSubquery(_) | Expr::InSubquery { .. } | Expr::Exists { .. } not supported
```

Internal slack context https://influxdata.slack.com/archives/C04768675QD/p1669056196021619?thread_ts=1668780132.191249&cid=C04768675QD

### PR DESCRIPTION
**Pull request by crepererum**
Fixes #6195.

### CODE REVIEW

File: querier/src/ingester/flight_client.rs [hunk 1]
```diff
@@ -120,15 +120,42 @@ fn serialize_ingester_query_request(
...
         Ok(proto) => Ok(proto),
-        Err(e) if (e.field == "exprs") && (e.description.contains("recursion limit reached")) => {
-            warn!(
-                predicate=?request.predicate,
-                "Cannot serialize predicate due to recursion limit, stripping it",
-            );
-            request.predicate = None;
-            request.try_into().context(CreatingRequestSnafu)
+        Err(e) => {
+            match SerializeFailureReason::extract_from_description(&e.field, &e.description) {
```
Comment (alamb) [inline querier/src/ingester/flight_client.rs:124]: 👍  I like the idea to log such predicates but run them anyways 👍

**Review by alamb — APPROVED** [review]
