### PR TITLE
fix: compactor-related freeze and shutdown  fixes

### LINKED ISSUE #5272: Ctrl-c is not terminating Iox Completely
@domodwyer told me to file this issue as we were communicating about it on slack...

On my mac as you can see below all the services gracefully shutdown but the process never exits
when running the command

```rust
./target/debug/influxdb_iox -vv
```

Here is the output from the verbose logging

```rust
2022-08-02T13:26:50.525706Z  INFO ioxd_common: Received SIGINT
2022-08-02T13:26:50.525706Z  INFO ioxd_common: Received SIGINT
2022-08-02T13:26:50.525707Z  INFO ioxd_common: Received SIGINT
2022-08-02T13:26:50.525707Z  INFO ioxd_common: Received SIGINT
2022-08-02T13:26:50.525787Z  INFO ioxd_common: Shutdown requested server_type=Querier
2022-08-02T13:26:50.525795Z  INFO ioxd_common: Shutdown requested server_type=Ingester
2022-08-02T13:26:50.525834Z  INFO ioxd_common: Shutdown requested server_type=Router
2022-08-02T13:26:50.525806Z  INFO ioxd_common: Shutdown requested server_type=Compactor
2022-08-02T13:26:50.525874Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-08-02T13:26:50.525887Z  INFO ioxd_common: HTTP server shutdown server_type=Querier
2022-08-02T13:26:50.525891Z  INFO ioxd_common: HTTP server shutdown server_type=Compactor
2022-08-02T13:26:50.525934Z  INFO ioxd_common: frontend shutdown completed server_type=Querier
2022-08-02T13:26:50.525951Z  INFO ioxd_common: frontend shutdown completed server_type=Compactor
2022-08-02T13:26:50.525929Z DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
2022-08-02T13:26:50.526057Z  INFO ioxd_common: HTTP server shutdown server_type=Router
2022-08-02T13:26:50.526090Z  INFO ioxd_common: frontend shutdown completed server_type=Router
2022-08-02T13:26:50.526160Z  INFO ioxd_common: backend shutdown completed server_type=Router
2022-08-02T13:26:50.527458Z  INFO ioxd_common: backend shutdown completed server_type=Querier
2022-08-02T13:26:50.530579Z  INFO ioxd_common: gRPC server shutdown server_type=Ingester
2022-08-02T13:26:50.530633Z  INFO ioxd_common: frontend shutdown completed server_type=Ingester
2022-08-02T13:26:50.530753Z  INFO ingester::lifecycle: Lifecycle manager shutdown
2022-08-02T13:26:50.530910Z  INFO ingester::stream_handler::handler: stream handler shutdown kafka_topic=iox-shared kafka_partition=0
2022-08-02T13:26:50.531320Z  INFO ioxd_common: backend shutdown completed server_type=Ingester
2022-08-02T13:26:50.531425Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8083) http_bind_address=None server_type=Ingester
2022-08-02T13:26:50.531505Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8081) http_bind_address=Some(SocketAddr(127.0.0.1:8080)) server_type=Router
2022-08-02T13:26:50.533515Z  INFO influxdb_iox::commands::run::main: done serving, draining futures grpc_bind_address=SocketAddr(127.0.0.1:8082) http_bind_address=None server_type=Querier
```

__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. ...
2. ...
3. ...

__Expected behaviour:__
Describe what you expected to happen.

__Actual behaviour:__
Describe What actually happened.

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.
* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).
* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

### PR DESCRIPTION
**Pull request by crepererum**
See commits.

Fixes #5272.

### CODE REVIEW

**Comment by stormasm** [comment]
@crepererum @alamb 

I pulled Marco's branch and tested that Ctrl-c works on my mac and I am very happy to report it works !

I have a working ctrl-c back, great news ! 😄 

You can happily land this PR...

**Review by NGA-TRAN — APPROVED** [review]

File: compactor/src/handler.rs [hunk 1]
```diff
@@ -366,10 +371,12 @@ impl CompactorHandler for CompactorHandlerImpl {
             .clone()
             .await
             .expect("compactor task failed");
+        self.exec.join().await;
     }
 
     fn shutdown(&self) {
         self.shutdown.cancel();
+        self.exec.shutdown();
```
Comment (alamb) [inline compactor/src/handler.rs:379]: this is the key, right? To pass through the shutdown request to outstanding tasks?

**Review by alamb — APPROVED** [review]
Thanks @crepererum

File: compactor/src/handler.rs (hunk 1 above)
Comment (crepererum) [reply compactor/src/handler.rs:379]: No, this is a drive-by fix to avoid warnings about "you haven't waited for the executor" on shut down. The actual fix is https://github.com/influxdata/influxdb_iox/pull/5299/commits/fd74f2639b5274a1585017fd291caf4df73bffc5
