### PR TITLE
fix: Don't try to parse /api/v2/query response as JSON

### LINKED ISSUE #5484: InfluxDB 2 Rust client: error while reading data
I use the library to store and read some data (both the client app and InfluxDB 2.4 instance are running inside a Kubernetes cluster). The former works well, but when I try to test getting data using the following code:

```rust
pub async fn read(influxdb_client: &InfluxDbClient) -> Result<(), CustomError> {
    let query = r#"
        from(bucket: "iot-measurements")
            |> range(start: -1h)
    "#;

    let res = influxdb_client
        .query(
            INFLUXDB_ORG.as_str(),
            Some(Query::new(query.to_string())),
        )
        .await?;

    Ok(())
}
```

The result of a call of the specified function is:

```
[src/processor.rs:61] data = Err(
    InternalError {
        message: "Error while processing the HTTP request: error decoding response body: EOF while parsing a value at line 2 column 0",
    },
)
```

When `trace` logger level is enabled, the output is as follows:

```
2022-08-29T09:17:08.951826Z TRACE hyper::client::pool: checkout waiting for idle connection: ("http", influxdb:8086)
2022-08-29T09:17:08.951862Z DEBUG reqwest::connect: starting new connection: http://influxdb:8086/    
2022-08-29T09:17:08.951880Z TRACE hyper::client::connect::http: Http::connect; scheme=Some("http"), host=Some("influxdb"), port=Some(Port(8086))
2022-08-29T09:17:08.952007Z DEBUG hyper::client::connect::dns: resolving host="influxdb"
2022-08-29T09:17:08.952880Z DEBUG hyper::client::connect::http: connecting to 10.96.179.109:8086
2022-08-29T09:17:08.953513Z TRACE mio::poll: registering event source with poller: token=Token(33554434), interests=READABLE | WRITABLE    
2022-08-29T09:17:08.954749Z DEBUG hyper::client::connect::http: connected to 10.96.179.109:8086
2022-08-29T09:17:08.954830Z TRACE hyper::client::conn: client handshake Http1
2022-08-29T09:17:08.954843Z TRACE hyper::client::client: handshake complete, spawning background dispatcher task
2022-08-29T09:17:08.954861Z TRACE want: signal: Want    
2022-08-29T09:17:08.954864Z TRACE want: signal found waiting giver, notifying    
2022-08-29T09:17:08.954869Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Busy }
2022-08-29T09:17:08.955714Z TRACE want: poll_want: taker wants!    
2022-08-29T09:17:08.955740Z TRACE hyper::client::pool: checkout dropped for ("http", influxdb:8086)
2022-08-29T09:17:08.955829Z TRACE encode_headers: hyper::proto::h1::role: Client::encode method=POST, body=Some(Known(96))
2022-08-29T09:17:08.955883Z TRACE hyper::proto::h1::encode: sized write, len = 96
2022-08-29T09:17:08.955928Z TRACE hyper::proto::h1::io: buffer.flatten self.len=204 buf.len=96
2022-08-29T09:17:08.956043Z DEBUG hyper::proto::h1::io: flushed 300 bytes
2022-08-29T09:17:08.956088Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: KeepAlive, keep_alive: Busy }
2022-08-29T09:17:08.965098Z TRACE hyper::proto::h1::conn: Conn::read_head
2022-08-29T09:17:08.965136Z TRACE hyper::proto::h1::io: received 209 bytes
2022-08-29T09:17:08.965196Z TRACE parse_headers: hyper::proto::h1::role: Response.parse bytes=209
2022-08-29T09:17:08.965209Z TRACE parse_headers: hyper::proto::h1::role: Response.parse Complete(197)
2022-08-29T09:17:08.965223Z DEBUG hyper::proto::h1::io: parsed 6 headers
2022-08-29T09:17:08.965229Z DEBUG hyper::proto::h1::conn: incoming body is chunked encoding
2022-08-29T09:17:08.965238Z TRACE hyper::proto::h1::decode: decode; state=Chunked(Size, 0)
2022-08-29T09:17:08.965243Z TRACE hyper::proto::h1::decode: Read chunk hex size
2022-08-29T09:17:08.965245Z TRACE hyper::proto::h1::decode: Read chunk hex size
2022-08-29T09:17:08.965247Z TRACE hyper::proto::h1::decode: Chunk size is 2
2022-08-29T09:17:08.965250Z DEBUG hyper::proto::h1::decode: incoming chunked header: 0x2 (2 bytes)
2022-08-29T09:17:08.965253Z TRACE hyper::proto::h1::decode: Chunked read, remaining=2
2022-08-29T09:17:08.965258Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Body(Chunked(BodyCr, 0)), writing: KeepAlive, keep_alive: Busy }
2022-08-29T09:17:08.965306Z DEBUG reqwest::async_impl::client: response '200 OK' for http://influxdb:8086/api/v2/query?org=iot
2022-08-29T09:17:08.965348Z TRACE hyper::proto::h1::decode: decode; state=Chunked(BodyCr, 0)
2022-08-29T09:17:08.965353Z TRACE hyper::proto::h1::decode: Read chunk hex size
2022-08-29T09:17:08.965355Z TRACE hyper::proto::h1::decode: Read chunk hex size
2022-08-29T09:17:08.965357Z TRACE hyper::proto::h1::decode: Chunk size is 0
2022-08-29T09:17:08.965359Z TRACE hyper::proto::h1::decode: end of chunked
2022-08-29T09:17:08.965362Z DEBUG hyper::proto::h1::conn: incoming body completed
2022-08-29T09:17:08.965383Z TRACE hyper::proto::h1::conn: maybe_notify; read_from_io blocked
2022-08-29T09:17:08.965452Z TRACE want: signal: Want    
2022-08-29T09:17:08.965479Z TRACE want: signal found waiting giver, notifying    
2022-08-29T09:17:08.965506Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
2022-08-29T09:17:08.965511Z TRACE want: signal: Want    
2022-08-29T09:17:08.965513Z TRACE hyper::proto::h1::conn: flushed({role=client}): State { reading: Init, writing: Init, keep_alive: Idle }
2022-08-29T09:17:08.965516Z TRACE want: poll_want: taker wants!    
2022-08-29T09:17:08.965519Z TRACE hyper::client::pool: put; add idle connection for ("http", influxdb:8086)
2022-08-29T09:17:08.965526Z DEBUG hyper::client::pool: pooling idle connection for ("http", influxdb:8086)
[src/processor.rs:61] data = Err(
    InternalError {
        message: "Error while processing the HTTP request: error decoding response body: EOF while parsing a value at line 2 column 0",
    },
)
```

It seems to me that the problem arises when deserialization is performed.

Do you have any thoughts on that?

### PR DESCRIPTION
**Pull request by carols10cents**
It's just plain text afaict.

Closes #5484.

So after actually getting a local influxdb 2.4 running and trying out queries that return data and queries that don't, I think the real problem is that we're trying to parse the response as JSON at all... 😳 

Looking at some of the other influxdb2 clients, it looks like the APIs that return the text without interpreting it at all are called `query_raw` rather than `query`, so I have another commit proposing to rename the function here... not sure if it'll break anything, but I doubt it as I don't think this ever worked 🤣 

@rkudryashov could you try out this branch and see if it works as you'd expect? Thanks!

### CODE REVIEW

**Review by NGA-TRAN — APPROVED** [review]
I approve this because it looks like it does what it means: return empty string rather than error.

File: influxdb2_client/src/api/query.rs [hunk 1]
```diff
@@ -78,17 +78,7 @@ impl Client {
         match response.status() {
             StatusCode::OK => {
                 let bytes = response.bytes().await.context(ResponseBytesSnafu)?;
-
-                let json_result = serde_json::from_slice::<String>(&bytes);
```
Comment (alamb) [inline influxdb2_client/src/api/query.rs:82]: this is really strange that we were parsing the response as JSON but then returning it to a string 🤔 


This PR's behavior makes much more sense

**Review by alamb — APPROVED** [review]

**Comment by rkudryashov** [comment]
@carols10cents that works, thanks for the fix!
