### PR TITLE
fix: limit number of S3 connections

### LINKED ISSUE #3336: S3 connection limit
It seems that we currently don't limit the number of connections to S3.

__Steps to reproduce:__
Test bench.

__Expected behaviour:__
IOx has a single, shared `Arc<ObjectStore>` and I would expect that this object somewhat limits the number of connections to S3.

__Actual behaviour:__
IOx seems to use too many connections, see logs.

__Config:__
Try to create 10k DBs using the test bench.

__Logs:__
- There are actual connection errors:
  `2021-12-08T12:28:25.697352Z ERROR server::database: database in error state - operator intervention required db_name=myorg_mytemplate667 e=error finding database directory in object storage: AWS S3-based Object Store error: Unable to list data. Bucket: iox, Error: Error during dispatch: connection error: Connection reset by peer (os error 104) (HttpDispatch(HttpDispatchError { message: "Error during dispatch: connection error: Connection reset by peer (os error 104)" })) state=DatabaseObjectStoreLookupError`
- And error responses (simulated w/ minio):
 `2021-12-08T12:28:25.731331Z ERROR server::database: database in error state - operator intervention required db_name=myorg_mytemplate432 e=error loading database rules: error fetching rules: AWS S3-based Object Store error: Unable to GET data. Bucket: iox, Location: dbs/c1fddde8-a28b-409c-837c-19d51969e285/rules.pb, Error: Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>SlowDown</Code><Message>A timeout exceeded while waiting to proceed with the request, please reduce your request rate</Message><Resource>/iox/dbs/c1fddde8-a28b-409c-837c-19d51969e285/rules.pb</Resource><RequestId>16BEC75554CC57B3</RequestId><HostId>21dee1c5-d7da-4817-a622-6f581cd876b9</HostId></Error> (Unknown(BufferedHttpResponse {status: 503, body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>A timeout exceeded while waiting to proceed with the request, please reduce your request rate</Message><Resource>/iox/dbs/c1fddde8-a28b-409c-837c-19d51969e285/rules.pb</Resource><RequestId>16BEC75554CC57B3</RequestId><HostId>21dee1c5-d7da-4817-a622-6f581cd876b9</HostId></Error>", headers: {"accept-ranges": "bytes", "content-length": "354", "content-security-policy": "block-all-mixed-content", "content-type": "application/xml", "retry-after": "120", "server": "MinIO", "strict-transport-security": "max-age=31536000; includeSubDomains", "vary": "Origin", "x-amz-request-id": "16BEC75554CC57B3", "x-content-type-options": "nosniff", "x-xss-protection": "1; mode=block", "date": "Wed, 08 Dec 2021 12:28:13 GMT"} })) state=RulesLoadError`

### PR DESCRIPTION
**Pull request by crepererum**
Otherwise the whole thing blows up when starting a server that has many
DBs registered, because we potentially create 1 connection per DB (e.g.
to read out the preserved catalog).

Fixes #3336.

Work for other backends is tracked under #3341.

### CODE REVIEW

File: object_store/src/aws.rs [hunk 1]
```diff
@@ -407,10 +423,43 @@ pub(crate) fn new_failing_s3() -> Result<AmazonS3> {
...
+        NonZeroUsize::new(16).unwrap(),
     )
 }
 
+/// S3 client bundled w/ a semaphore permit.
+#[derive(Clone)]
+struct SemaphoreClient {
+    /// Permit for this specific use of the client.
+    ///
+    /// Note that this field is never read and therefore considered "dead code" by rustc.
```
Comment (alamb) [inline object_store/src/aws.rs:435]: You can also name it like `_permit` to make the warnings go away, in case you like that better

**Review by alamb — APPROVED** [review]
Looks reasonable to me
