### PR TITLE
fix: treat early server worker exit as proper error

### LINKED ISSUE #3375: IOx Exit Code
**Problem**

Currently if IOx encounters an error, such as a background worker panicking, it will trigger server shutdown. However, the server will then exit with a zero exit-code.

**Proposal**

When shutting down because of an error, IOx should return a non-zero exit code

### PR DESCRIPTION
**Pull request by crepererum**
Instead of just logging the issue, also make sure the error gets
propagated all the way up to the exit code.

Fixes #3375.

### CODE REVIEW

File: influxdb_iox/src/commands/run/test.rs [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+        - command line arguments
+        - user set environment variables
+        - .env file contents
+        - pre-configured default values"
+)]
+pub struct Config {
+    #[structopt(flatten)]
+    pub(crate) run_config: RunConfig,
+
+    /// Test action
```
Comment (carols10cents) [inline influxdb_iox/src/commands/run/test.rs:49]: Do we want the valid values for `--test-action` documented here? Or is this command something we only expect to use in internal tests that we deliberately don't want to explain to end users?

File: influxdb_iox/src/influxdb_ioxd/server_type/test.rs [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+    type Err = String;
+
+    fn from_str(s: &str) -> Result<Self, Self::Err> {
+        match s.to_lowercase().as_ref() {
+            "none" => Ok(Self::None),
+            "early-return-from-grpc-worker" => Ok(Self::EarlyReturnFromGrpcWorker),
+            "early-return-from-server-worker" => Ok(Self::EarlyReturnFromServerWorker),
+            "panic-in-grpc-worker" => Ok(Self::PanicInGrpcWorker),
+            "panic-in-server-worker" => Ok(Self::PanicInServerWorker),
+            _ => Err(format!("Invalid test action: {}", s)),
```
Comment (carols10cents) [inline influxdb_iox/src/influxdb_ioxd/server_type/test.rs:49]: If we do want to document the possible values to show up in the `--help` output, I think it would also be nice to have the possible values in the error message here, so that if you type a value wrong it'll say something like `Invalid test action: arly-return-from-grpc-worker. Valid values are: none, early-return-from-grpc-worker...`

File: influxdb_iox/src/influxdb_ioxd/server_type/test.rs [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+            panic!("Test panic in gRPC worker");
+        }
+        if self.test_action == TestAction::EarlyReturnFromGrpcWorker {
+            return Ok(());
+        }
+
+        let builder = setup_builder!(builder_input, self);
+        serve_builder!(builder);
+
+        Ok(())
```
Comment (carols10cents) [inline influxdb_iox/src/influxdb_ioxd/server_type/test.rs:110]: Personally, I think these functions with multiple `if` blocks would be better expressed with `match`:

```suggestion
        match self.test_action {
            TestAction::PanicInGrpcWorker => panic!("Test panic in gRPC worker"),
            TestAction::EarlyReturnFromGrpcWorker => Ok(()),
            _ => {
                let builder = setup_builder!(builder_input, self);
                serve_builder!(builder);

                Ok(())
            }
        }
```

but I don't feel super strongly about it, especially because this is test code :)

**Review by carols10cents — APPROVED** [review]
I added a panic in the database background worker and observed on `main` the server exit code was 0, and on this branch it's 1 🎉 !

Just a few small thoughts to take or leave :)

File: influxdb_iox/src/influxdb_ioxd.rs [hunk 4]
```diff
@@ -276,19 +285,28 @@ where
...
+                }
                 Err(error) => {
                     error!(%error, "gRPC server error");
-                    res = res.and(Err(Error::ServingRpc{source: error}))
+                    res = res.and(Err(Error::ServingRpc{source: error}));
                 }
             },
             result = http_server => match result {
-                Ok(_) => info!("HTTP server shutdown"),
+                Ok(_) if frontend_shutdown.is_cancelled() => info!("HTTP server shutdown"),
```
Comment (alamb) [inline influxdb_iox/src/influxdb_ioxd.rs:302]: 👍

File: influxdb_iox/tests/end_to_end_cases/run_cli.rs [hunk 5]
```diff
@@ -93,3 +93,54 @@ fn test_deprecated_cli_without_server_type() {
     process.kill().unwrap();
     process.wait().unwrap();
 }
+
+#[test]
+fn test_early_return_from_grpc_worker() {
```
Comment (alamb) [inline influxdb_iox/tests/end_to_end_cases/run_cli.rs:98]: Nice

**Review by alamb — APPROVED** [review]
🥇 for some great testing

I liked @carols10cents  code style suggestions as well

**Comment by crepererum** [comment]
Fixed the test action CLI. Now we have:

```console
$ cargo run -- run test --help
...
        --test-action <test-action>
            Test action [env: IOX_TEST_ACTION=]  [default: None]  [possible values: None, EarlyReturnFromGrpcWorker,
            EarlyReturnFromServerWorker, PanicInGrpcWorker, PanicInServerWorker]
...

$ cargo run -- run test --test-action=Foo
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/influxdb_iox run test --test-action=Foo`
error: 'Foo' isn't a valid value for '--test-action <test-action>'
        [possible values: EarlyReturnFromGrpcWorker, EarlyReturnFromServerWorker, None, PanicInGrpcWorker, PanicInServerWorker]

File: influxdb_iox/src/influxdb_ioxd/server_type/test.rs [hunk 6]
```diff
@@ -27,27 +28,14 @@ impl HttpApiErrorSource for ApplicationError {
...
-    fn from_str(s: &str) -> Result<Self, Self::Err> {
-        match s.to_lowercase().as_ref() {
-            "none" => Ok(Self::None),
-            "early-return-from-grpc-worker" => Ok(Self::EarlyReturnFromGrpcWorker),
-            "early-return-from-server-worker" => Ok(Self::EarlyReturnFromServerWorker),
-            "panic-in-grpc-worker" => Ok(Self::PanicInGrpcWorker),
-            "panic-in-server-worker" => Ok(Self::PanicInServerWorker),
-            _ => Err(format!("Invalid test action: {}", s)),
-        }
+arg_enum! {
```
Comment (alamb) [inline influxdb_iox/src/influxdb_ioxd/server_type/test.rs:31]: TIL https://docs.rs/clap/2.34.0/clap/macro.arg_enum.html 👍
