### PR TITLE
fix(router2): lazily connect to ingesters

### LINKED ISSUE #6503: Unavailable Ingester causes router panic
When starting up, a router requires all ingesters to be available. If this is not the case, the router panics:

```
level=info msg="Creating jaeger tracing exporter" agent_endpoint=10.153.10.106:6831 service_name=iox-router2 target="trace_exporters::jaeger" location="trace_exporters/src/jaeger.rs:93" time=1672874288058705098
level=info msg="connected to config store" application_name=router2 target="iox_catalog::postgres" location="iox_catalog/src/postgres.rs:383" time=1672874288155825810
level=info msg="Object Store" bucket="Some(\"prod01-eu-central-1.aws.influxdata.io-iox\")" endpoint=None object_store_type=S3 target="clap_blocks::object_store" location="clap_blocks/src/object_store.rs:290" time=1672874288155854241
level=info msg="Using Instance credential provider" target="object_store::aws" location="/usr/local/cargo/git/checkouts/arrow-rs-3b86e19e889d5acc/f5c165a/object_store/src/aws/mod.rs:622" time=1672874288155875713
thread 'main' panicked at 'failed to connect to server iox-shared-ingester-0.iox-shared-ingester:8082: Connection error: transport error (error trying to connect: tcp connect error: Connection refused (os error 111))', /influxdb_iox/router/src/dml_handlers/rpc_write.rs:26:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: router::dml_handlers::rpc_write::write_service_client::{{closure}}::{{closure}}
             at ./influxdb_iox/router/src/dml_handlers/rpc_write.rs:26:29
   3: core::result::Result<T,E>::unwrap_or_else
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1504:23
   4: router::dml_handlers::rpc_write::write_service_client::{{closure}}
             at ./influxdb_iox/router/src/dml_handlers/rpc_write.rs:23:22
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   6: ioxd_router::create_router2_server_type::{{closure}}
             at ./influxdb_iox/ioxd_router/src/lib.rs:265:66
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   8: influxdb_iox::commands::run::router2::command::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/commands/run/router2.rs:99:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  10: influxdb_iox::commands::run::command::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/commands/run/mod.rs:129:67
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  12: influxdb_iox::main::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/main.rs:277:64
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  16: tokio::runtime::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  17: tokio::runtime::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  18: tokio::runtime::park::CachedParkThread::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  19: tokio::runtime::context::BlockingRegionGuard::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  20: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  21: tokio::runtime::runtime::Runtime::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:281:45
  22: influxdb_iox::main
             at ./influxdb_iox/influxdb_iox/src/main.rs:203:5
  23: core::ops::function::FnOnce::call_once
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
level=error msg="sender-side of async exporter dropped without waiting for shut down" target="trace_exporters::export" location="trace_exporters/src/export.rs:114" time=167287429011404515
```

This reduces write availability significantly, and triggers continuously during deployments - an ingester is deployed and begins replaying the WAL, and simultaneously the routers are deployed, all of which observe the dead ingester and panic.

There is also a failure to resolve the DNS address causing the same issue:

```
thread 'main' panicked at 'failed to connect to server iox-shared-ingester-0.iox-shared-ingester:8082: Connection error: transport error (error trying to connect: dns error: failed to lookup address information: Name or service not known)', /influxdb_iox/router/src/dml_handlers/rpc_write.rs:26:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: router::dml_handlers::rpc_write::write_service_client::{{closure}}::{{closure}}
             at ./influxdb_iox/router/src/dml_handlers/rpc_write.rs:26:29
   3: core::result::Result<T,E>::unwrap_or_else
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/result.rs:1504:23
   4: router::dml_handlers::rpc_write::write_service_client::{{closure}}
             at ./influxdb_iox/router/src/dml_handlers/rpc_write.rs:23:22
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   6: ioxd_router::create_router2_server_type::{{closure}}
             at ./influxdb_iox/ioxd_router/src/lib.rs:265:66
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
   8: influxdb_iox::commands::run::router2::command::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/commands/run/router2.rs:99:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  10: influxdb_iox::commands::run::command::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/commands/run/mod.rs:129:67
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  12: influxdb_iox::main::{{closure}}
             at ./influxdb_iox/influxdb_iox/src/main.rs:277:64
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  16: tokio::runtime::coop::with_budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  17: tokio::runtime::coop::budget
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  18: tokio::runtime::park::CachedParkThread::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  19: tokio::runtime::context::BlockingRegionGuard::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  20: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  21: tokio::runtime::runtime::Runtime::block_on
             at ./usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:281:45
  22: influxdb_iox::main
             at ./influxdb_iox/influxdb_iox/src/main.rs:203:5
  23: core::ops::function::FnOnce::call_once
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
```

Steps to reproduce:

1. Start a router with any number of ingester addresses, but at least one unavailable
2. Panic!

### PR DESCRIPTION
**Pull request by domodwyer**
As per the commit message, this has (minor) downsides. I'll add a comment to #6173 that should include improving this logic.

Fixes #6503.

---

* fix(router2): lazily connect to ingesters (a5a26f5ef)

      Allow the routers to start up without requiring full availability of all
      downstream ingesters. Previously a single unavailable ingester prevented
      the routers from starting up.
      
      This has downsides:
      
        * Lazily initialising a connection will cause the first writes to have
          higher latency as the connection is established.
        * The routers MAY come up in a state that will never work (i.e. bad
          ingester addresses)
        * Using the opaque gRPC load balancing mechanism restricts the
          visibility into which nodes are up/down (hindering useful log
          messages) and prevents us from implementing more advanced circuit
          breaking / probing logic / load-balancing strategies.
      
      This change is a quick fix - it leaves the round-robin handler in place,
      load-balancing over a single tonic Channel, which internally
      load-balances. This will need cleaning up.

### CODE REVIEW

File: router/src/dml_handlers/rpc_write.rs [hunk 1]
```diff
@@ -127,6 +130,7 @@ where
                     Ok(()) => break,
                     Err(e) => warn!(error=%e, "failed ingester rpc write"),
                 };
+                tokio::time::sleep(Duration::from_millis(50)).await;
```
Comment (alamb) [inline router/src/dml_handlers/rpc_write.rs:133]: waiting before retry makes sense. I wonder if a longer wait time (100 or 500 milliseconds) is worth considering. Trying ~ 20 times might still put a non trivial load on the system

File: router/src/dml_handlers/rpc_write.rs [hunk 2]
```diff
@@ -12,19 +12,22 @@ use mutable_batch::MutableBatch;
...
-    WriteServiceClient::new(connection.into_grpc_connection())
+/// Create a connection to one or more ingesters, load-balancing requests across
+/// all of them.
+///
+/// Connections are lazily established.
+pub fn build_ingester_connection<T>(addrs: impl Iterator<Item = T>) -> WriteServiceClient<Channel>
+where
+    T: AsRef<str>,
+{
+    WriteServiceClient::new(Channel::balance_list(
```
Comment (alamb) [inline router/src/dml_handlers/rpc_write.rs:28]: TIL https://docs.rs/tonic/0.8.3/tonic/transport/struct.Channel.html#method.balance_list 👍

**Review by alamb — APPROVED** [review]
I think this PR does what it says it does though I don't have the context to really understand all the potential implications. I say 🚢 🇮🇹

File: router/src/dml_handlers/rpc_write.rs (hunk 1 above)
Comment (domodwyer) [reply router/src/dml_handlers/rpc_write.rs:133]: Indeed - I'm punting a bunch of improvements to #6173 for when there's the magical "time". We shouldn't keep retrying failed endpoints, for example.

This is actually bounded, as the number of concurrent requests is also bounded, therefore the total load is bounded - good enough for the time being :+1:

Comment (alamb) [reply router/src/dml_handlers/rpc_write.rs:133]: Right -- it might be bounded but the absolute value of up to 20 per second seems like it might be excessive. I agree it is good for now
