### PR TITLE
fix: update PersistenceWindows on rules update (#2018)

### LINKED ISSUE #2018: PersistenceWindows update LifecycleRules
If you update the LifecycleRules, any pre-existing partitions will continue to use the old values for late_arrival_period but the lifecycle policy will use the new values for everything else. 

This is because the late_arrival_period is set on the PersistenceWindows at creation time and never updated. This prevents validation of the LifecycleRules, such as in #2005, from working correctly and is also just very confusing

### PR DESCRIPTION
**Pull request by tustvold**
Closes #2018

### CODE REVIEW

File: tests/end_to_end_cases/persistence.rs [hunk 1]
```diff
@@ -49,16 +49,43 @@ async fn test_chunk_is_persisted_automatically() {
...
+}
+
 #[tokio::test]
 async fn test_full_lifecycle() {
     let fixture = ServerFixture::create_shared().await;
     let mut write_client = fixture.write_client();
 
     let num_payloads = 10;
-    let num_duplicates = 2;
+    let num_duplicates = 1;
```
Comment (tustvold) [inline tests/end_to_end_cases/persistence.rs:85]: This was actually misleading, it was actually the number of times it would write the payload, not the number of duplicates - I've fixed this

File: server/src/db.rs [hunk 2]
```diff
@@ -333,13 +333,40 @@ impl Db {
     }
 
     /// Updates the database rules
-    pub fn update_db_rules<F, E>(&self, update: F) -> Result<Arc<DatabaseRules>, E>
+    pub fn update_rules<F, E>(&self, update: F) -> Result<Arc<DatabaseRules>, E>
```
Comment (crepererum) [inline server/src/db.rs:336]: IMHO we should disallow updating the rules for a running DB. Updating configs and reasoning about the effects and where to update what and which parts of the state to invalidate just asks for trouble. Why can we not recreate the entire DB object and just accept that updating rules is a rare and potentially expensive event?

Comment (crepererum) [reply server/src/db.rs:336]: BTW: this method as it stands here is already broken since it allows you to update write buffer configs w/o any effect. Same goes for persisted catalog configs (e.g. the checkpoint interval) and potentially many other configs.

Comment (alamb) [reply server/src/db.rs:336]: We have used the "update rules without restart" feature several times while debugging IOx on tools. For example, . to quickly test out the effect of lifecycle policy changes without having to wait for the dbs to be restarted (and potentially rebuild up sufficient in memory state). If possible it would be nice to maintain that ability. 

Perhaps a middle ground alternative is to whitelist updates to certain fields (e.g. memory limits or lifecycle limits) that can be safely changed for a running database but reject changes if they are for fields outside the whitelist

File: tests/end_to_end_cases/persistence.rs [hunk 3]
```diff
@@ -123,6 +140,49 @@ async fn test_full_lifecycle() {
...
+        .persist(true)
+        .persist_row_threshold(payload_size)
+        .persist_age_threshold_seconds(1000)
+        // Initially set to be a large value
+        .late_arrive_window_seconds(1000)
+        .build(fixture.grpc_channel())
+        .await;
+
+    write_data(&mut write_client, &db_name, 1, 0, payload_size).await;
+
```
Comment (alamb) [inline tests/end_to_end_cases/persistence.rs:161]: I suggest adding a `wait_for_exact_chunk_states` in `OpenMutableBuffer` to show that the state changes due to the change of `late_arrive_window_seconds`

File: server/src/db.rs [hunk 4]
```diff
@@ -333,13 +333,40 @@ impl Db {
...
+            let late_arrive_window_updated = rules.lifecycle_rules.late_arrive_window_seconds
+                != new_rules.lifecycle_rules.late_arrive_window_seconds;
+
+            *rules = Arc::clone(&new_rules);
+            (late_arrive_window_updated, new_rules)
+        };
+
+        if late_arrive_window_updated {
+            // Hold a read lock to prevent concurrent modification and
+            // use values from re-acquired read guard
```
Comment (alamb) [inline server/src/db.rs:353]: Is the theory here that if another call has updated the values during the lock gap, the following code that updates the persistence windows will be a no op, but that will be fine? I think it makes sense I am just validating my understanding.

**Review by alamb — APPROVED** [review]

File: server/src/db.rs (hunk 4 above)
Comment (tustvold) [reply server/src/db.rs:353]: Correct :+1:

File: server/src/db.rs (hunk 2 above)
Comment (tustvold) [reply server/src/db.rs:336]: I've created https://github.com/influxdata/influxdb_iox/issues/2065 to track returning an error on unanticipated changes to the configuration. I think it would be reasonable to reject any changes outside the LifecycleRules as a first step
