### PR TITLE
fix: statistics for max/min(time) should have data type timstamp

### LINKED ISSUE #2779: Inconsistent timestamp results from MUB and RUB
__Steps to reproduce:__
See these 3 current ignored tests (still in PR #2777):
  - sql::sql_select_with_delete_from_multi_exprs_max_time
  - sql::sql_select_with_delete_from_multi_exprs_min_time
  - sql::sql_select_with_delete_from_one_expr_max_time

Each test will run different  15 scenarios. When data is in MUB, timestamp format (e.g. `1970-01-01T00:00:00.000000020Z`) is returned. When data is in RUB, integer (e.g. `20`) is returned.

__Expected behaviour:__
The same format of timestamp should be returned

__Actual behaviour:__
Different format

### PR DESCRIPTION
**Pull request by NGA-TRAN**
Closes #2779

Describe your proposed changes here.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

File: query/src/statistics.rs [hunk 1]
```diff
@@ -1,16 +1,27 @@
...
+) -> Option<ScalarValue> {
     match stats {
-        IOxStatistics::I64(v) => v.min.map(ScalarValue::from),
+        IOxStatistics::I64(v) => {
+            if let Some(InfluxDbType::Timestamp) = *influx_type {
+                Some(ScalarValue::TimestampNanosecond(v.min))
+            } else {
+                v.min.map(ScalarValue::from)
+            }
+        }
```
Comment (NGA-TRAN) [inline query/src/statistics.rs:24]: This is the fix that returns the timestamp data type as needed

File: query_tests/cases/in/delete_multi_expr_one_chunk.expected [hunk 2]
```diff
@@ -75,6 +75,46 @@
 +--------------+
 | you          |
 +--------------+
+-- SQL: SELECT min(foo) from cpu group by bar;
```
Comment (NGA-TRAN) [inline query_tests/cases/in/delete_multi_expr_one_chunk.expected:78]: I added a few min/max(non time column) but have group by that we have missed

File: query_tests/cases/in/delete_multi_expr_one_chunk.sql [hunk 3]
```diff
@@ -25,10 +25,22 @@ SELECT foo from cpu;
...
---  inconsistent format returned
--- SELECT min(time) from cpu;
--- SELECT max(time) from cpu;
+-- SELECT min(foo) from cpu group by time;
+-- SELECT max(foo) from cpu group by time;
+-- SELECT time, max(foo) from cpu group by time;
+
+SELECT min(foo) from cpu group by bar;
+SELECT bar, max(foo) from cpu group by bar;
+-- Todo: Test not work in this framework. Exact same test works in sql.rs
```
Comment (NGA-TRAN) [inline query_tests/cases/in/delete_multi_expr_one_chunk.sql:34]: This is the reason of all commented-out queries under `cases` tests. The problem is the test framework. I will file a ticket first thing next week

File: query_tests/src/scenarios/delete.rs [hunk 4]
```diff
@@ -99,9 +99,9 @@ impl DbSetup for OneDeleteMultiExprsOneChunk {
         let table_name = "cpu";
         // chunk data
         let lp_lines = vec![
-            "cpu,foo=me bar=1 10",
+            "cpu,foo=me bar=1 10", // deleted
             "cpu,foo=you bar=2 20",
-            "cpu,foo=me bar=1 30",
+            "cpu,foo=me bar=1 30", // deleted
```
Comment (NGA-TRAN) [inline query_tests/src/scenarios/delete.rs:104]: added comments for me to verify the test output easier

File: query_tests/src/sql.rs [hunk 5]
```diff
@@ -772,4 +775,149 @@ async fn sql_select_without_delete_min_foo() {
     .await;
 }
 
+#[tokio::test]
```
Comment (NGA-TRAN) [inline query_tests/src/sql.rs:778]: The reason I added these group by tests here because many of them do not pass in the `cases` test framework

File: query/src/statistics.rs (hunk 1 above)
Comment (alamb) [reply query/src/statistics.rs:24]: this is a great find.

File: query_tests/cases/in/delete_multi_expr_one_chunk.sql [hunk 6]
```diff
@@ -25,10 +25,22 @@ SELECT foo from cpu;
 SELECT min(foo) from cpu;
 SELECT max(foo) from cpu;
 
--- BUG: https://github.com/influxdata/influxdb_iox/issues/2779
---  inconsistent format returned
--- SELECT min(time) from cpu;
--- SELECT max(time) from cpu;
+-- SELECT min(foo) from cpu group by time;
```
Comment (alamb) [inline query_tests/cases/in/delete_multi_expr_one_chunk.sql:28]: I think that we can probably remove these comments now that the same queries are included explicitly below

File: query_tests/cases/in/delete_three_delete_three_chunks.sql [hunk 7]
```diff
@@ -51,8 +54,7 @@ SELECT * from cpu where foo = 'you' and (bar > 3.0 or bar = 1) order by bar, foo
 
 SELECT min(bar) from cpu where foo = 'me' and (bar > 2 or bar = 1.0);
 
---  BUG: https://github.com/influxdata/influxdb_iox/issues/2779
```
Comment (alamb) [inline query_tests/cases/in/delete_three_delete_three_chunks.sql:54]: 👍

File: query_tests/cases/in/delete_three_delete_three_chunks.sql [hunk 8]
```diff
@@ -25,10 +25,13 @@ SELECT foo from cpu order by foo;
 SELECT min(foo) from cpu;
 SELECT max(foo) from cpu;
 
--- BUG: https://github.com/influxdata/influxdb_iox/issues/2779
```
Comment (alamb) [inline query_tests/cases/in/delete_three_delete_three_chunks.sql:28]: 👍

File: query_tests/src/sql.rs (hunk 5 above)
Comment (alamb) [reply query_tests/src/sql.rs:778]: The fact they don't pass in the cases framework is very strange. I would love to know why / help if possible (the compile times for `query_tests` is already bad enough :)

**Review by alamb — COMMENTED** [review]
Looks great @NGA-TRAN  -- this is a really nice find

https://github.com/influxdata/influxdb_iox/issues/2779#issuecomment-962145800 is a really nice analysis 👍

**Review by alamb — APPROVED** [review]

File: query_tests/cases/in/delete_multi_expr_one_chunk.sql (hunk 6 above)
Comment (NGA-TRAN) [reply query_tests/cases/in/delete_multi_expr_one_chunk.sql:28]: This test is different because it is grouped by `time`
