### PR TITLE
fix: fix flaky `test_unload_partition_chunk`

### LINKED ISSUE #2109: Flaky test end_to_end_cases::management_cli::test_unload_partition_chunk
```
failures:

---- end_to_end_cases::management_cli::test_unload_partition_chunk stdout ----
2.803959ms: chunk 0 partition cpu storage: OpenMutableBuffer row_count: 1 time_of_last_write: Some(2021-07-26T09:12:54.015931978Z)
514.128814ms: chunk 0 partition cpu storage: OpenMutableBuffer row_count: 1 time_of_last_write: Some(2021-07-26T09:12:54.015931978Z)
thread 'end_to_end_cases::management_cli::test_unload_partition_chunk' panicked at 'Unexpected failure.
code-1
stderr=```"Error in partition subcommand: Error unloading chunk: Not found: Resource chunk/cpu:cpu:1 not found\n"```
command=`"/home/rust/project/target/debug/influxdb_iox" "database" "partition" "unload-chunk" "mMX4rc6FbW" "cpu" "cpu" "1" "--host" "http://127.0.0.1:8091"`
code=1
stdout=```""```
stderr=```"Error in partition subcommand: Error unloading chunk: Not found: Resource chunk/cpu:cpu:1 not found\n"```
', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.7/src/assert.rs:155:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: assert_cmd::assert::Assert::success
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.7/src/assert.rs:155:13
   3: end_to_end::end_to_end_cases::management_cli::test_unload_partition_chunk::{{closure}}
             at ./tests/end_to_end_cases/management_cli.rs:733:5
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/mod.rs:80:19
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/future/future.rs:120:9
   6: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:208:62
   7: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:106:9
   8: std::thread::local::LocalKey<T>::try_with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:376:16
   9: std::thread::local::LocalKey<T>::with
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/thread/local.rs:352:9
  10: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:99:5
  11: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/coop.rs:76:5
  12: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:208:39
  13: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:299:29
  14: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/macros/scoped_tls.rs:61:9
  15: tokio::runtime::basic_scheduler::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:299:5
  16: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:197:9
  17: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:452:9
  18: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/basic_scheduler.rs:157:24
  19: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.9.0/src/runtime/mod.rs:450:46
  20: end_to_end::end_to_end_cases::management_cli::test_unload_partition_chunk
             at ./tests/end_to_end_cases/management_cli.rs:733:5
  21: end_to_end::end_to_end_cases::management_cli::test_unload_partition_chunk::{{closure}}
             at ./tests/end_to_end_cases/management_cli.rs:710:7
  22: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
  23: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    end_to_end_cases::management_cli::test_unload_partition_chunk

test result: FAILED. 86 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 30.09s

error: test failed, to rerun pass '-p influxdb_iox --test end_to_end'
```

### PR DESCRIPTION
**Pull request by crepererum**
Do not rely on the fact that the chunk ID is 1, because compaction and
other mechanisms might create chunks using different IDs.

Closes #2109.

### CODE REVIEW

**Review by mkmik — APPROVED** [review]

File: tests/end_to_end_cases/management_cli.rs [hunk 1]
```diff
@@ -722,13 +722,14 @@ async fn test_unload_partition_chunk() {
...
 
-    wait_for_exact_chunk_states(
+    let mut chunks = wait_for_exact_chunk_states(
         &fixture,
         &db_name,
         vec![ChunkStorage::ReadBufferAndObjectStore],
         std::time::Duration::from_secs(5),
     )
     .await;
+    let chunk = chunks.pop().unwrap();
```
Comment (alamb) [inline tests/end_to_end_cases/management_cli.rs:732]: 👍
