### PR TITLE
fix: Make --api-bind et.al. support localhost

### LINKED ISSUE #785: --api-bind doesn't support localhost:<port>
```
$ ./target/debug/influxdb_iox server --api-bind localhost:1234
error: Invalid value for '--api-bind <http-bind-address>': invalid IP address syntax
```

---

Possible root cause: we're using `structopt` to map flags directly into a `SocketAddr` instead of going through `to_socket_addrs`

### PR DESCRIPTION
**Pull request by mkmik**
Closes #785

### CODE REVIEW

File: src/commands/config.rs [hunk 1]
```diff
@@ -256,4 +266,32 @@ mod tests {
...
+            SocketAddr::V4(so) => {
+                assert_eq!(so, SocketAddrV4::new(Ipv4Addr::new(127, 0, 0, 1), 1234))
+            }
+            SocketAddr::V6(so) => assert_eq!(
+                so,
+                SocketAddrV6::new(Ipv6Addr::new(0, 0, 0, 0, 0, 0, 0, 1), 1234, 0, 0)
+            ),
+        };
+
+        Ok(())
```
Comment (alamb) [inline src/commands/config.rs:295]: I suggest also adding a test for an invalid host/port: `"this&*$(isnot:75882932492"` or something silly. I think as written the code above will `panic!` and it might be nice if it at least gave a useful error

File: src/commands/config.rs [hunk 2]
```diff
@@ -142,6 +144,11 @@ pub fn load_config() -> Config {
     Config::from_iter(strip_server(std::env::args()).iter())
 }
 
+fn parse_socket_addr(s: &str) -> std::io::Result<SocketAddr> {
+    let mut addrs = s.to_socket_addrs()?;
+    Ok(addrs.next().unwrap())
```
Comment (alamb) [inline src/commands/config.rs:149]: I think this might panic if the host did not have networking enabled (or the address couldn't be resolved for some other reason)?

https://doc.rust-lang.org/std/net/trait.ToSocketAddrs.html#tymethod.to_socket_addrs

> The returned iterator may not actually yield any values depending on the outcome of any resolution performed.

I suggest at least giving the user a hint when this happens with something like;

```suggestion
    Ok(addrs.next().expect("Could not resolve string to any socket address. Is networking enabled?"))
```

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Removed the merge label so @mkmik  can have a chance to think about the comments (I am fine with merging it in as is too)

File: src/commands/config.rs (hunk 2 above)
Comment (mkmik) [reply src/commands/config.rs]: makes sense

File: src/commands/config.rs (hunk 1 above)
Comment (mkmik) [reply src/commands/config.rs:318]: done; fwiw invalid host/port (either because of syntatic issues or because of failed runtime resolution) are real errors and don't produce an empty result iter silently.

File: src/commands/config.rs [hunk 3]
```diff
@@ -256,4 +271,50 @@ mod tests {
...
+            .expect_err("must fail"),
+            clap::ErrorKind::ValueValidation
+        );
+
+        assert_eq!(
+            Config::from_iter_safe(strip_server(
+                to_vec(&["cmd", "server", "--api-bind", "badhost.badtld:1234"]).into_iter(),
+            ))
+            .map_err(|e| e.kind)
+            .expect_err("must fail"),
```
Comment (alamb) [inline src/commands/config.rs:314]: thanks!
