### PR TITLE
fix(8191): directory path resolve

### LINKED ISSUE #8191: `influxdb_iox --data-dir ./new_data_dir` fails with `thread 'main' panicked at 'failed to resolve WAL directory to disk`
__Steps to reproduce:__
```shell
$ mkdir foo
# panic (at the disco!)
$ influxdb_iox --data-dir foo
```

```
(arrow_dev) alamb@MacBook-Pro-8:~/Downloads$ influxdb_iox --data-dir ./foo
2023-07-07T19:26:52.665088Z  WARN router::dml_handlers::rpc_write::lazy_connector: failed to connect to upstream ingester endpoint=http://127.0.0.1:8083/ error=transport error
thread 'main' panicked at 'failed to resolve WAL directory to disk', /Users/alamb/Software/influxdb_iox/ingester/src/init.rs:344:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-07-07T19:26:52.770459Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
2023-07-07T19:26:52.770868Z  WARN executor: DedicatedExecutor dropped without calling shutdown()
```

__Expected behaviour:__
I expect it to start up normally 

Interestingly if I give it the full path it works fine

```
# This works great!
$ influxdb_iox --data-dir `pwd`/foo
```

### PR DESCRIPTION
**Pull request by wiedld**
Closes #8191 

Need to resolve for all pathing use cases.

---

* fix(8191): resolve canonical, absolute form of the path (61710b118)

* test(8191): update test to cover path resolution (6c3427124)

## Checklist
- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed).

### CODE REVIEW

File: tracker/src/disk_metric.rs [hunk 1]
```diff
@@ -49,6 +51,7 @@ impl DiskSpaceMetrics {
         let system = System::new_with_specifics(RefreshKind::new().with_disks_list());
 
         // Resolve the mount point once.
+        // The directory path may be `/path/to/dir` and the mount point is `/`.
```
Comment (wiedld) [inline tracker/src/disk_metric.rs:54]: Want to explicitly highlight that the metric measurement is performed at a different path as the attributes label. This was part of the requirements/request at the time -- I leave others to decide whether or not to leave as is. 😄

Comment (domodwyer) [reply tracker/src/disk_metric.rs:54]: I don't think there's any point emitting the mount point, it's not really something people can correlate - I don't know what the mount point of the WAL dir is in prod, and I bet neither do you! You wouldn't probably recognise the WAL directory path though.

**Review by domodwyer — APPROVED** [review]

File: tracker/src/disk_metric.rs [hunk 2]
```diff
@@ -99,15 +102,22 @@ mod tests {
...
 
     use metric::Metric;
+    use uuid::Uuid;
 
     use super::*;
 
     #[tokio::test]
     async fn test_metrics() {
+        let unique_dir = Uuid::new_v4().to_string();
+        std::fs::create_dir(unique_dir.clone()).ok();
```
Comment (domodwyer) [inline tracker/src/disk_metric.rs:112]: Can we do this in `tmp` or something? Otherwise every time you run the test, you'll create a new directory in your working dir which is _annoying_ to say the least.

**Review by domodwyer — CHANGES_REQUESTED** [review]
I think we should avoid creating a mess in the work directory :+1:

Normally we'd create a temporary directory for tests that touch the filesystem, I think tempfile is somewhat standard usage.

File: tracker/src/disk_metric.rs (hunk 2 above)
Comment (alamb) [reply tracker/src/disk_metric.rs:112]: Perhaps https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html would be a good choice (it is used widely in other tests)

File: tracker/src/disk_metric.rs [hunk 3]
```diff
@@ -27,8 +27,10 @@ pub struct DiskSpaceMetrics {
 impl DiskSpaceMetrics {
     /// Create a new [`DiskSpaceMetrics`], returning [`None`] if no disk can be
     /// found for the specified `directory`.
-    pub fn new(mut directory: PathBuf, registry: &metric::Registry) -> Option<Self> {
+    pub fn new(directory: PathBuf, registry: &metric::Registry) -> Option<Self> {
         let path: Cow<'static, str> = Cow::from(directory.display().to_string());
+        let mut directory = directory.canonicalize().ok()?;
```
Comment (alamb) [inline tracker/src/disk_metric.rs:32]: Is this the bug fix (to canonicalize the directory?)

File: tracker/src/disk_metric.rs [hunk 4]
```diff
@@ -99,15 +102,22 @@ mod tests {
...
 
     use super::*;
 
     #[tokio::test]
     async fn test_metrics() {
+        let unique_dir = Uuid::new_v4().to_string();
+        std::fs::create_dir(unique_dir.clone()).ok();
+
+        let relative_path = PathBuf::from(unique_dir.clone());
+        let metric_label: Cow<'static, str> = unique_dir.clone().into();
```
Comment (alamb) [inline tracker/src/disk_metric.rs:115]: I verified that this test covers the behavior by reverting the code change 

```diff
diff --git a/tracker/src/disk_metric.rs b/tracker/src/disk_metric.rs
index 0ee395227..75b213347 100644
--- a/tracker/src/disk_metric.rs
+++ b/tracker/src/disk_metric.rs
@@ -27,10 +27,8 @@ pub struct DiskSpaceMetrics {
 impl DiskSpaceMetrics {
     /// Create a new [`DiskSpaceMetrics`], returning [`None`] if no disk can be
     /// found for the specified `directory`.
-    pub fn new(directory: PathBuf, registry: &metric::Registry) -> Option<Self> {
+    pub fn new(mut directory: PathBuf, registry: &metric::Registry) -> Option<Self> {
         let path: Cow<'static, str> = Cow::from(directory.display().to_string());
-        let mut directory = directory.canonicalize().ok()?;
-
         let attributes = Attributes::from([("path", path)]);
 
         let available_disk_space = registry

```

And then verifying that the test fails:

```
---- disk_metric::tests::test_metrics stdout ----
thread 'disk_metric::tests::test_metrics' panicked at 'root always exists', tracker/src/disk_metric.rs:119:18
stack backtrace:
   0: rust_begin_unwind
```

👍

**Review by alamb — APPROVED** [review]
I tested this out locally and it resolves the error I was seeing. Thank you @wiedld  🙏

File: tracker/src/disk_metric.rs (hunk 3 above)
Comment (wiedld) [reply tracker/src/disk_metric.rs:32]: Yes, and it handles various other use cases as well (path sym links, etc). Figured would fix it once.

File: tracker/src/disk_metric.rs (hunk 2 above)
Comment (wiedld) [reply tracker/src/disk_metric.rs]: TempDir was super useful. TY!

**Comment by wiedld** [comment]
Made the changes requested by @dom, and already have a re-approval from @alamb . To get this in more quickly, will merge now. But please let me know if I should include additional changes in another PR!

**Review by domodwyer — APPROVED** [review]
