### PR TITLE
fix: optimize field columns for all-time predicates

### LINKED ISSUE #4827: Ensure "All time" metadata queries are appropriately special cased

### PR DESCRIPTION
**Pull request by lesam**
Also fix timestamp range to allow selecting points at MAX_NANO_TIME

Closes #4827 

Describe your proposed changes here.

- [x] I've read the contributing section of the project [README](https://github.com/influxdata/influxdb_iox/blob/main/README.md).

### CODE REVIEW

File: iox_query/src/frontend/influxrpc.rs [hunk 1]
```diff
@@ -670,9 +668,25 @@ impl InfluxRpcPlanner {
...
+            if predicate.is_empty() {
+                // optimization: just get the field columns from metadata.
+                // note this both ignores field keys, and sets the timestamp data 'incorrectly'.
+                let schema = database
+                    .table_schema(table_name)
+                    .context(TableRemovedSnafu { table_name })?;
+                let fields = schema.fields_iter().map(|f| Field {
+                    name: f.name().clone(),
+                    data_type: f.data_type().clone(),
+                    last_timestamp: 0,
```
Comment (lesam) [inline iox_query/src/frontend/influxrpc.rs:683]: I could make this the system `now` time, but I think a constant signalling value would be better since it is much more clear to our users that it does not represent the time of any particular field value. `MIN_NANO_TIME` or `MAX_NANO_TIME` might also be good but zero was nicely 'default-y'.

File: data_types/src/lib.rs [hunk 2]
```diff
@@ -2085,14 +2085,14 @@ impl TimestampRange {
     ///
     /// Takes an inclusive start and an exclusive end. You may create an empty range by setting `start = end`.
     ///
-    /// Clamps to [`MIN_NANO_TIME`]/[`MAX_NANO_TIME`].
+    /// Clamps start to [`MIN_NANO_TIME`].
+    /// end is unclamped - end may be set to i64:MAX == MAX_NANO_TIME+1 to indicate no restriction on time.
```
Comment (lesam) [inline data_types/src/lib.rs:2089]: Note this change!

File: predicate/src/lib.rs [hunk 3]
```diff
@@ -220,7 +220,7 @@ impl Predicate {
     /// existing storage engine
     pub(crate) fn with_clear_timestamp_if_max_range(mut self) -> Self {
         self.range = self.range.take().and_then(|range| {
-            if range.start() <= MIN_NANO_TIME && range.end() >= MAX_NANO_TIME {
+            if range.start() <= MIN_NANO_TIME && range.end() == i64::MAX {
```
Comment (lesam) [inline predicate/src/lib.rs:223]: Note this change!

File: predicate/src/lib.rs [hunk 4]
```diff
@@ -220,7 +220,7 @@ impl Predicate {
     /// existing storage engine
     pub(crate) fn with_clear_timestamp_if_max_range(mut self) -> Self {
         self.range = self.range.take().and_then(|range| {
-            if range.start() <= MIN_NANO_TIME && range.end() >= MAX_NANO_TIME {
+            if range.start() <= MIN_NANO_TIME && range.end() > MAX_NANO_TIME {
```
Comment (lesam) [inline predicate/src/lib.rs:223]: Note also this change!

File: data_types/src/lib.rs (hunk 2 above)
Comment (crepererum) [reply data_types/src/lib.rs:2089]: This sounds really hackish to me. If you wanna allow no time restriction at all, then use `Option<TimestampRange>`.

We clamp it because `i64` is NOT a valid nanosecond range (now that I write that I think the clamping is actually incomplete, `start` must also be clamped by `MAX_NANO_TIME` and `end` must also be clamped by `MIN_NANO_TIME`). Otherwise other parts of the stack will likely explode when constructing filter predicates based on this data. Since this type is used for other requests as well, I suspect a user can now send out-of-bounds values and either get an error or (even worse) get the querier to panic.

File: service_grpc_influxrpc/src/service.rs [hunk 5]
```diff
@@ -2908,7 +2908,7 @@ mod tests {
         let request = MeasurementFieldsRequest {
             source: source.clone(),
             measurement: "TheMeasurement".into(),
-            range: None,
+            range: Some(make_timestamp_range(i64::MIN, i64::MAX - 1)),
```
Comment (crepererum) [inline service_grpc_influxrpc/src/service.rs:2911]: This is what I meant with typing: Use `None` if you actually mean "no restriction", not some magic out-of-bounds values.

**Review by crepererum — CHANGES_REQUESTED** [review]

File: service_grpc_influxrpc/src/service.rs (hunk 5 above)
Comment (lesam) [reply service_grpc_influxrpc/src/service.rs:2911]: This is actually just to avoid the 'optimized' case so the test doesn't change. This filter says 'range is all time except `i64::MAX-1`. Passing `None` still works fine and would actually mean 'all time'.

File: data_types/src/lib.rs (hunk 2 above)
Comment (lesam) [reply data_types/src/lib.rs:2089]: I disagree about clamping by MAX_NANO_TIME (though I agree we probably should clamp end by MIN_NANO_TIME for safety).

The definition for MAX_NANO_TIME:

```
/// maximum time that can be represented.
///
/// 2262-04-11 23:47:16.854775806 +0000 UTC
///
/// The highest time represented by a nanosecond needs to be used for an
/// exclusive range in the shard group, so the maximum time needs to be one
/// less than the possible maximum number of nanoseconds representable by an
/// int64 so that we don't lose a point at that one time.
/// Source: [influxdb](https://github.com/influxdata/influxdb/blob/540bb66e1381a48a6d1ede4fc3e49c75a7d9f4af/models/time.go#L12-L34)
pub const MAX_NANO_TIME: i64 = i64::MAX - 1;
```

Filter expressions need to be able to express the time range 'all representable timestamps above 1000', since the end of the range is exclusive this is the range `{1000, MAX_NANO_TIME+1}` == `{1000, i64::MAX}`.

IDPE unfortunately gets this right for tag keys:

https://github.com/influxdata/idpe/blob/master/storage/store/store.go#L1395-L1397

But wrong for ReadFilter:

https://github.com/influxdata/idpe/blob/master/storage/store/store.go#L1086-L1088

Comment (lesam) [reply data_types/src/lib.rs:2089]: Flux does have the bounds correct:

https://github.com/influxdata/flux/blob/master/execute/bounds.go#L15-L28

Comment (lesam) [reply data_types/src/lib.rs:2089]: Filed https://github.com/influxdata/influxdb/issues/23519 for OSS2

Comment (lesam) [reply data_types/src/lib.rs:2089]: > now that I write that I think the clamping is actually incomplete, start must also be clamped by MAX_NANO_TIME and end must also be clamped by MIN_NANO_TIME

I agree end should also be clamped by MIN_NANO_TIME, fixed now.

Comment (crepererum) [reply data_types/src/lib.rs:2089]: We had a quick 1:1 chat, I agree w/ @lesam 's statements here.

**Comment by lesam** [comment]
Created https://github.com/influxdata/influxdb_iox/issues/5051
