### PR TITLE
fix: ensure no rows returned for predicates with disjoint matching expressions

### LINKED ISSUE #1860: Read buffer returns values for `column_values` that do not pass the predicate
Note: when this is fixed, we should remove the workaround in the `list_tag_values_table_and_timestamp_and_state_pred_state_col_no_rows` test

__Steps to reproduce:__

There is a test case on the https://github.com/influxdata/influxdb_iox/tree/alamb/read_buffer_bug_repo branch, the diff for which is also included below

Load this data into the read buffer:

```
o2,state=MA,city=Boston temp=50.4 200
o2,state=CA temp=79.0 300
o2,state=NY temp=60.8 400
o2,state=NY,city=NYC temp=61.0 500
o2,state=NY,city=NYC,borough=Brooklyn temp=61.0 600
```

And then run tag_vaues with predicate of the form:

```rust
    let tag_name = "state";
    let predicate = PredicateBuilder::default()
        .table("o2")
        .timestamp_range(1, 300) // filters out the NY row
        .add_expr(col("state").eq(lit("NY"))) // state=NY
        .build();
    let expected_tag_keys = vec![];
```

__Expected behaviour:__
No rows should be returned

__Actual behaviour:__
Read buffer returns `{"CA", "MA", "NY"}` (note when the data is in the mutable buffer the correct answer is produced)

I suspect it has to do with Null handling (every one's favorite)

__Logs:__

```

Here are some logs:

Jun 30 14:53:56.684 TRACE server::db::chunk: Using read buffer predicate rb_predicate=Predicate([BinaryExpr { col: "time", op: GTE, value: Integer(1) }, BinaryExpr { col: "time", op: LT, value: Integer(300) }, BinaryExpr { col: "state", op: Equal, value: String("NY") }])
Jun 30 14:53:56.685 TRACE server::db::chunk: Raw values returned from read buffer  values={"state": {"CA", "MA", "NY"}}
Jun 30 14:53:56.685 TRACE server::db::chunk: selected values values={"CA", "MA", "NY"}
```

Here is the full test diff:

```diff
diff --git a/query_tests/src/influxrpc/tag_values.rs b/query_tests/src/influxrpc/tag_values.rs
index 0562aefb..c4a11b22 100644
--- a/query_tests/src/influxrpc/tag_values.rs
+++ b/query_tests/src/influxrpc/tag_values.rs
@@ -220,6 +220,23 @@ async fn list_tag_values_table_and_timestamp_and_state_pred_state_col_no_rows()
     );
 }
 
+#[tokio::test]
+async fn list_tag_values_table_and_timestamp_and_state_pred_state_col_no_rows_single_chunk() {
+    let tag_name = "state";
+    let predicate = PredicateBuilder::default()
+        .table("o2")
+        .timestamp_range(1, 300) // filters out the NY row
+        .add_expr(col("state").eq(lit("NY"))) // state=NY
+        .build();
+    let expected_tag_keys = vec![];
+    run_tag_values_test_case!(
+        TwoMeasurementsManyNullsSingleChunk {},
+        tag_name,
+        predicate,
+        expected_tag_keys
+    );
+}
+
 #[tokio::test]
 async fn list_tag_values_field_col() {
     let db_setup = TwoMeasurementsManyNulls {};
diff --git a/query_tests/src/scenarios.rs b/query_tests/src/scenarios.rs
index b2160410..e1422c61 100644
--- a/query_tests/src/scenarios.rs
+++ b/query_tests/src/scenarios.rs
@@ -264,6 +264,28 @@ impl DbSetup for MultiChunkSchemaMerge {
     }
 }
 
+
+/// Two measurements data with many null values in a single chunk
+#[derive(Debug)]
+pub struct TwoMeasurementsManyNullsSingleChunk {}
+#[async_trait]
+impl DbSetup for TwoMeasurementsManyNullsSingleChunk {
+    async fn make(&self) -> Vec<DbScenario> {
+        let partition_key = "1970-01-01T00";
+
+        let lp_lines = vec![
+            "o2,state=MA,city=Boston temp=50.4 200",
+            "o2,state=CA temp=79.0 300",
+            "o2,state=NY temp=60.8 400",
+            "o2,state=NY,city=NYC temp=61.0 500",
+            "o2,state=NY,city=NYC,borough=Brooklyn temp=61.0 600",
+        ];
+
+        make_one_chunk_scenarios(partition_key, &lp_lines.join("\n")).await
+    }
+}
+
+
 /// Two measurements data with many null values
 #[derive(Debug)]
 pub struct TwoMeasurementsManyNulls {}
```

### PR DESCRIPTION
**Pull request by e-dard**
Closes #1860

If a predicate was shown to the Read Buffer with multiple expressions, and both of those expressions matched a disjoint set of rows, then the Read Buffer would mistakenly assume the resulting empty row set (after intersection) was a signal that all rows matched the predicate.

The optimisation is there to avoid materialising large compressed bitmaps unnecessarily,  but it was missing an empty-set check during expression evaluation 😄

### CODE REVIEW

File: query_tests/src/influxrpc/tag_values.rs [hunk 1]
```diff
@@ -227,6 +227,23 @@ async fn list_tag_values_table_and_timestamp_and_state_pred_state_col_no_rows()
     );
 }
 
+#[tokio::test]
+async fn list_tag_values_table_and_timestamp_and_state_pred_state_col_no_rows_single_chunk() {
```
Comment (alamb) [inline query_tests/src/influxrpc/tag_values.rs:231]: Rather than a new test, you can also get coverage for the bug by removing the exception from the previous test: https://github.com/influxdata/influxdb_iox/pull/1866/files#diff-b52c1a54c0ba8c63984d59f72f490190e07ea84aef44618e4c9e386130b18ff4R216-R219

```rust
    // Ignore the compact case, until this is fixed:
    // https://github.com/influxdata/influxdb_iox/issues/1860
    let filter =
        |setup: &DbScenario| setup.scenario_name != "Data in one compacted read buffer chunk";
```

The reproducer on the ticket is a slimmed down version.

File: read_buffer/src/row_group.rs [hunk 2]
```diff
@@ -369,8 +369,16 @@ impl RowGroup {
                 RowIDsOption::Some(row_ids) => {
                     if result_row_ids.is_empty() {
                         result_row_ids.union(&row_ids)
+                    } else {
+                        result_row_ids.intersect(&row_ids);
+                    }
+
+                    // before evaluating the next expression check if we have
```
Comment (alamb) [inline read_buffer/src/row_group.rs:376]: 👍

**Review by alamb — APPROVED** [review]
Looks good to me. Thanks for the quick fix

File: query_tests/src/influxrpc/tag_values.rs [hunk 3]
```diff
@@ -213,14 +213,8 @@ async fn list_tag_values_table_and_timestamp_and_state_pred_state_col_no_rows()
...
 
-    // Ignore the compact case, until this is fixed:
-    // https://github.com/influxdata/influxdb_iox/issues/1860
-    let filter =
-        |setup: &DbScenario| setup.scenario_name != "Data in one compacted read buffer chunk";
-
     run_tag_values_test_case!(
-        //TwoMeasurementsManyNulls {},
-        FilteredSetup::new(TwoMeasurementsManyNulls {}, filter),
+        TwoMeasurementsManyNulls {},
```
Comment (alamb) [inline query_tests/src/influxrpc/tag_values.rs:217]: ❤️  beautiful

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
@e-dard  any reason not to merge this one in?
