### PR TITLE
fix: respect partition key when batching dml ops

### LINKED ISSUE #4787: Partitions contain writes that don't map to the partition's partition key
All writes in a partition should be for the same partition key.

We have 659,328 partitions that contain writes that span more than one partition key (at time of writing) :fire:

```sql
SELECT COUNT(id)
FROM
        parquet_file
WHERE
        to_timestamp(min_time / 1000000000) :: date != to_timestamp(max_time / 1000000000) :: date;
 count
--------
 659328
(1 row)
```

Lots of these seem to be potential rounding/timezone/off-by-one issues:

```
    id    | sequencer_id | table_id | partition_id | namespace_id | compaction_level |    min     |    max
----------+--------------+----------+--------------+--------------+------------------+------------+------------
 13908550 |           28 |   333125 |     21288956 |      4630294 |                0 | 2022-03-01 | 2022-03-02
 13908905 |           28 |   333125 |     21166535 |      4630294 |                0 | 2022-05-02 | 2022-05-03
 13908721 |           28 |   333125 |     21288972 |      4630294 |                0 | 2022-03-09 | 2022-03-10
 13908807 |           28 |   333125 |     21288985 |      4630294 |                0 | 2022-03-20 | 2022-03-21
```

However here are some more worrying examples:

```
    id    | sequencer_id | table_id | partition_id | namespace_id | compaction_level |    min     |    max
----------+--------------+----------+--------------+--------------+------------------+------------+------------
 10623921 |           36 |    13350 |     19051402 |          541 |                0 | 2022-04-28 | 2022-05-11
 14840098 |           21 |   105176 |     22112396 |       824781 |                1 | 1859-04-16 | 2022-06-03
 14876809 |           21 |   105176 |     22112396 |       824781 |                0 | 1859-04-16 | 2022-06-03
 15452719 |           13 |    99163 |     22277696 |          604 |                1 | 1798-10-17 | 2022-06-05
 15472059 |           13 |    99163 |     22277696 |          604 |                0 | 1798-10-17 | 2022-06-05
```

These queries show examples where the YMD derived from the min/max timestamps in the parquet file are not equal (they should always be equal for the current YMD partitioning scheme). There may be more examples where min/max in parquet files derive to the same, but incorrect, YMD partition key r.w.t the partition they are part of.

### PR DESCRIPTION
**Pull request by domodwyer**
This PR fixes #4787.

The router is hard-coded to [partition writes by YMD][scheme] (meaning a partition per day, today's being `2022-06-16`), breaking the writes into a single [DML write request per partition][router-partition]. The router then dispatches each of these partitioned DML writes into kafka via the write buffer abstraction.

On the other side of kafka, the ingester reads these messages and uses the same hard-coded partitioning scheme to [infer the partition key][ingest] of the batch. This inference solution was a temporary workaround until OG was deprecated and removed, which made changing the kafka message format feasible (#3603). 

Correctness of this scheme relies on the atomicity of the DML batches being preserved through the system - a batch is split up by the router according to the partition rules, and then sent to the ingester which uses the same logic to infer it.

Unfortunately the kafka write buffer client (and _only the kafka impl_...) [merges together DML operations][agg] before writing the resulting merged batch to kafka. This undid the partitioning the router performed by glueing together independent, per partition DML ops without respecting the partitioning, causing one DML op to contain many distinct partitions. This would lead to the ingester incorrectly inferring the partition key for the batch which would contain data for multiple desired partitions. This caused both the per-partition catalog metadata, and actual resulting parquet files to incorrectly contain data for multiple partitions.

This led to at least 902,241 partitions which broke the "writes for one day" invariant after being merged together with writes for different dates.

## Further work

* Affected partitions need to be fixed, or removed. This includes both the catalog references, and the parquet files.
* Pass the derived partition key over the API boundary (from router -> ingester) removing the need for inference (follow-up PR incoming!)
* Reconsider the DML aggregation strategy:
  * Aggregation should occur "above" the kafka client - aggregating should be independent of the client used, both for consistency across all write buffer impls, and separation of concerns. This made debugging much harder as it didn't happen when using the all-in-one mode, nor did any unit tests trigger the issue as there is no aggregation for the mock impl used in tests.
  * Consider preserving the individual DML ops, but batching them up (effectively `Vec<DmlOp>` rather than merging them into a single `DmlOp`). The potential loss of compression is likely to be negligible, but both the impl & mental model would be much simpler.

[router-partition]:https://github.com/influxdata/influxdb_iox/blob/43b3f224116f5a886ec7c77e70ed479f21721a17/router/src/dml_handlers/partitioner.rs#L76-L98
[scheme]:https://github.com/influxdata/influxdb_iox/blob/43b3f224116f5a886ec7c77e70ed479f21721a17/ioxd_router/src/lib.rs#L198
[ingest]:https://github.com/influxdata/influxdb_iox/blob/43b3f224116f5a886ec7c77e70ed479f21721a17/ingester/src/partioning.rs#L25-L39
[agg]:https://github.com/influxdata/influxdb_iox/blob/43b3f224116f5a886ec7c77e70ed479f21721a17/write_buffer/src/kafka/aggregator.rs#L128-L147
---

* fix: respect partition key when batching dml ops (43b3f2241)

      This commit changes the kafka write aggregator to only merge DML ops destined
      for the same partition.

      Prior to this commit the aggregator was merging DML ops that had different
      partition keys, causing data to be persisted in incorrect partitions:

          https://github.com/influxdata/influxdb_iox/issues/4787

### CODE REVIEW

**Comment by crepererum** [comment]
> Aggregation should occur "above" the kafka client - aggregating should be independent of the client used, both for consistency across all write buffer impls, and separation of concerns. This made debugging much harder as it didn't happen when using the all-in-one mode, nor did any unit tests trigger the issue as there is no aggregation for the mock impl used in tests.

The issue is that Kafka (or any sequencer) is NOT a data stream but a message stream and the message size depends on the concrete write buffer type (e.g. Kafka) as well as on the infrastructure. So performing this aggregation on a higher level is IMHO as messy as the current solution.


> Consider preserving the individual DML ops, but batching them up (effectively Vec<DmlOp> rather than merging them into a single DmlOp). The potential loss of compression is likely to be negligible, but both the impl & mental model would be much simpler.

At least for the current serialization format this is not true, because now you need to store column names and string dictionaries for every single tiny write operation.

**Review by crepererum — APPROVED** [review]
Good catch!

File: write_buffer/src/kafka/aggregator.rs [hunk 1]
```diff
@@ -91,6 +100,11 @@ impl WriteAggregator {
     fn can_push(&self, write: &DmlWrite) -> bool {
         assert_eq!(write.namespace(), self.namespace);
 
+        // Only batch together writes for the same partition.
+        if write.partition_key() != Some(&self.partition_key) {
```
Comment (alamb) [inline write_buffer/src/kafka/aggregator.rs:104]: this is the actual fix, right?

**Review by alamb — APPROVED** [review]

File: write_buffer/src/kafka/aggregator.rs (hunk 1 above)
Comment (domodwyer) [reply write_buffer/src/kafka/aggregator.rs:104]: Yes sorry, I was going to comment around the place but got meeting sniped.

Comment (tustvold) [reply write_buffer/src/kafka/aggregator.rs:104]: If I understand this correctly, any write for a different partition will effectively poison the aggregation logic for all batches. This seems not ideal...

**Comment by tustvold** [comment]
> Consider preserving the individual DML ops, but batching them up

FWIW rskafka has provides an Aggregator that does this, the implementation in IOx just exploits the fact we can do better and aggregate the actual messages themselves - https://docs.rs/rskafka/latest/rskafka/client/producer/aggregator/struct.RecordAggregator.html.

File: write_buffer/src/kafka/aggregator.rs (hunk 1 above)
Comment (alamb) [reply write_buffer/src/kafka/aggregator.rs:104]: Context is https://github.com/influxdata/conductor/issues/971 where we are trying to get more throughput from kafka and the current theory is that small kafka batch sizes are a contributing factor

Comment (crepererum) [reply write_buffer/src/kafka/aggregator.rs:104]: Should be fixed by #5113
