### PR TITLE
fix: improve error for malformed gap fill query

### LINKED ISSUE #8208: SQL: `date_bin_gapfill` returns error when casting to `bigint`
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

Using the metrics line protocol, execute

```sql
select date_bin_gapfill('60 seconds'::interval, time)::bigint as time, sum(usage_idle) from cpu WHERE time >= '2020-06-11T16:52:00Z' AND time < '2020-06-11T16:54:00Z' group by 1;
```

__Expected behaviour:__

Executes the query and returns the time column as nanosecond integers.

__Actual behaviour:__

```text
Error querying: Tonic(Status { code: Internal, message: "External error: Internal error: time array must be a TimestampNanosecondArray. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker", source: None })
```

### Other information

Interestingly, I can workaround the issue by running the following query:

```sql
SELECT 
  date_bin_gapfill('60 seconds'::interval, time)::bigint as time, sum(usage_idle) 
FROM cpu 
WHERE time >= '2020-06-11T16:52:00Z' AND time < '2020-06-11T16:54:00Z' 
GROUP BY date_bin_gapfill('60 seconds'::interval, time);
```

which produces the expected output:

```
+---------------------+---------------------+
| time                | SUM(cpu.usage_idle) |
+---------------------+---------------------+
| 1591894320000000000 | 9945.307130522731   |
| 1591894380000000000 | 9989.904543698025   |
+---------------------+---------------------+
```

> **Note**
> 
> The first column in the projection list performs the cast is not in the `GROUP BY`, yet the query still works.

We can see from the logical plan that the expression `date_bin_gapfill('60 seconds'::interval, time)` has been extracted and only the cast is performed at the final projection:

```text
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                                                                |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: CAST(date_bin_gapfill(Utf8("60 seconds"),cpu.time) AS Int64) AS time, SUM(cpu.usage_idle)                                                                                                                                                                                                                               |
|               |   GapFill: groupBy=[[date_bin_gapfill(Utf8("60 seconds"),cpu.time)]], aggr=[[SUM(cpu.usage_idle)]], time_column=date_bin_gapfill(Utf8("60 seconds"),cpu.time), stride=IntervalMonthDayNano("60000000000"), range=Included(TimestampNanosecond(1591894320000000000, None))..Excluded(TimestampNanosecond(1591894440000000000, None)) |
|               |     Aggregate: groupBy=[[date_bin(IntervalMonthDayNano("60000000000"), cpu.time) AS date_bin_gapfill(IntervalMonthDayNano("60000000000"),cpu.time) AS date_bin_gapfill(Utf8("60 seconds"),cpu.time)]], aggr=[[SUM(cpu.usage_idle)]]                                                                                                 |
|               |       TableScan: cpu projection=[time, usage_idle], full_filters=[cpu.time >= TimestampNanosecond(1591894320000000000, None), cpu.time < TimestampNanosecond(1591894440000000000, None)]                                                                                                                                            |
```

### PR DESCRIPTION
**Pull request by wolffcm**
Closes #8208.

This improves error message when the user submits a gap filling query that we can't handle because the the data is not being grouped by `DATE_BIN_GAPFILL`. Previously we did not catch this until execution had begun. This change catches the error during planning.

### CODE REVIEW

File: influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected [hunk 1]
```diff
@@ -247,4 +247,8 @@ Error during planning: gap-filling query is missing lower time bound
 | 2023-06-10T12:02:00Z | pod2 | {value: imageB, time: 2023-06-10T12:00:02} |
 | 2023-06-10T12:03:00Z | pod2 | {value: imageB, time: 2023-06-10T12:00:02} |
 | 2023-06-10T12:04:00Z | pod2 | {value: imageB, time: 2023-06-10T12:00:02} |
-+----------------------+------+--------------------------------------------+
\ No newline at end of file
++----------------------+------+--------------------------------------------+
+-- SQL: select date_bin_gapfill('60 seconds'::interval, time)::bigint as time, sum(idle) from cpu WHERE time >= '2020-06-11T16:52:00Z' AND time < '2020-06-11T16:54:00Z' group by 1;
+Error while planning query: Optimizer rule 'handle_gap_fill' failed
+caused by
+Error during planning: DATE_BIN_GAPFILL must a top-level expression in the GROUP BY clause when gap filling
```
Comment (alamb) [inline influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected:254]: 👍

Comment (alamb) [reply influxdb_iox/tests/query_tests/cases/in/gapfill.sql.expected:254]: Maybe we could also hint at "it can't be used in expressions or casts" -- for example

```
Error during planning: DATE_BIN_GAPFILL must a top-level expression in the GROUP BY clause when gap filling. It can not be part of another expression or cast
```

File: iox_query/src/logical_optimizer/handle_gapfill.rs [hunk 2]
```diff
@@ -298,8 +298,24 @@ fn replace_date_bin_gapfill(group_expr: &[Expr]) -> Result<Option<RewriteInfo>>
                 "DATE_BIN_GAPFILL specified more than once".to_string(),
             ))
         }
-        _ => (),
+        n => {
+            // I'm not sure why I need a catch-all pattern for this arm,
```
Comment (alamb) [inline iox_query/src/logical_optimizer/handle_gapfill.rs:302]: maybe you could move it above the `0..2` so the cases are in order `0, 1, 2..`

**Review by alamb — APPROVED** [review]

File: iox_query/src/logical_optimizer/handle_gapfill.rs (hunk 2 above)
Comment (wolffcm) [reply iox_query/src/logical_optimizer/handle_gapfill.rs]: Hmm, I wanted the `1` last since the other arms return early. But even re-ordering the arms does not satisfy the compiler.
