### PR TITLE
fix: Use datafusion optimizer in IOx query plans

### LINKED ISSUE #422: bug: Wrong answers when using DataFusion optimizer
DataFusion includes an optimization pass (`ExecutionContext::optimize`) that should do things like predicate pushdown and projection pruning. 

However, when I enable it for IOx, wrong answers come out (filters appear to be dropped unecessairly)

Definition of done for this bug is to figure out what is wrong and enable the optimizer pass.

Example:

Apply this patch:
```
diff --git a/storage/src/exec/planning.rs b/storage/src/exec/planning.rs
index 4cd095b..bd03b46 100644
--- a/storage/src/exec/planning.rs
+++ b/storage/src/exec/planning.rs
@@ -99,14 +99,12 @@ impl IOxExecutionContext {
     }
 
     pub async fn make_plan(&self, plan: &LogicalPlan) -> Result<Arc<dyn ExecutionPlan>> {
-        debug!("Running plan, input\n----\n{}\n----", dump_plan(plan));
+        debug!("Preparing to run plan. Input: \n----\n{}\n----", dump_plan(plan));
 
-        // TODO the datafusion optimizer was removing filters..
-        //let logical_plan = ctx.optimize(&plan).context(DataFusionOptimization)?;
-        let logical_plan = plan;
+        let logical_plan = self.inner.optimize(&plan)?;
         debug!(
-            "Running optimized plan\n----\n{}\n----",
-            dump_plan(logical_plan)
+            "Preparing to run plan. Optimized:\n----\n{}\n----",
+            dump_plan(&logical_plan)
         );
 
         self.inner.create_physical_plan(&logical_plan)
```

Then the following test fails:

```
failures:

---- database::tests::list_column_names_predicate stdout ----
thread 'database::tests::list_column_names_predicate' panicked at 'assertion failed: `(left == right)`
  left: `{"city", "county", "state"}`,
 right: `{"borough", "city", "county", "state"}`', write_buffer/src/database.rs:1684:9

---- database::tests::list_column_names stdout ----
Running test case: TestCase { description: "No predicates", predicate: Predicate { table_names: None, field_columns: None, exprs: [], range: None }, expected_tag_keys: Ok(["borough", "city", "county", "state"]) }
Running test case: TestCase { description: "Restrictions: timestamp", predicate: Predicate { table_names: None, field_columns: None, exprs: [], range: Some(TimestampRange { start: 150, end: 201 }) }, expected_tag_keys: Ok(["city", "state"]) }
Running test case: TestCase { description: "Restrictions: predicate", predicate: Predicate { table_names: None, field_columns: None, exprs: [#state Eq Utf8("MA")], range: None }, expected_tag_keys: Ok(["city", "county", "state"]) }
thread 'database::tests::list_column_names' panicked at 'Mismatch
actual_tag_keys: 
Ok({"borough", "city", "county", "state"})
expected_tag_keys: 
Ok(["city", "county", "state"])
Test_case: 
TestCase {
    description: "Restrictions: predicate",
    predicate: Predicate {
        table_names: None,
        field_columns: None,
        exprs: [
            #state Eq Utf8("MA"),
        ],
        range: None,
    },
    expected_tag_keys: Ok(
        [
            "city",
            "county",
            "state",
        ],
    ),
}', write_buffer/src/database.rs:1606:13


failures:
    database::tests::list_column_names
    database::tests::list_column_names_predicate


```

### PR DESCRIPTION
**Pull request by alamb**
There was a bug in Apache Arrow DataFusion (https://issues.apache.org/jira/browse/ARROW-10547, fixed in https://github.com/apache/arrow/pull/8633) that prevented us from enabling its query Optimizer passes in IOx. The issue has been resolved upstream so we can now enable the optimizer in IOx.

This PR:
1. Upgrades to use a new version of arrow https://github.com/apache/arrow/commit/8e4d9ebef30857bab7a35003af0c663e776909aa
2. Enables the query optimizer passes
3. Note this also removes vestigial `dump_plan` code in IOx in favor of `display_indent_schema` and `display_graphviz` from DataFusion.
4. Fixes #422

### CODE REVIEW

File: storage/src/exec/planning.rs [hunk 1]
```diff
@@ -99,17 +98,21 @@ impl IOxExecutionContext {
...
 
     pub async fn make_plan(&self, plan: &LogicalPlan) -> Result<Arc<dyn ExecutionPlan>> {
-        debug!("Running plan, input\n----\n{}\n----", dump_plan(plan));
+        debug!(
+            "Creating plan: Initial plan\n----\n{}\n{}\n----",
+            plan.display_indent_schema(),
+            plan.display_graphviz(),
+        );
+
+        let plan = self.inner.optimize(&plan)?;
```
Comment (alamb) [inline storage/src/exec/planning.rs:107]: here is the call to run the actual optimizer 😓 such a small change

**Review by e-dard — APPROVED** [review]
