### PR TITLE
fix: incorrect speculation of post-persist sequence ranges

### LINKED ISSUE #2206: FlushHandle Generates Incorrect PartitionCheckpoint
As part of a persist operation, a `FlushHandle` is obtained from the `PersistenceWindow`, this in turn is used to generate the `PartitionCheckpoint` that is written as part of this operation. This must describe the state of the system speculatively, i.e. what the state of the system will be after the persist operation, but must defer the actual modification of the `PersistenceWindow` until after the persist operation completes, at which point `FlushHandle::flush` is called.

On flush all closed windows that were present at the time of the `FlushHandle`'s creation, have their min row timestamp updated to be one nanosecond greater than the flush timestamp (as those rows must have been persisted). 

The bug concerns what happens when the chosen flush timestamp exceeds the max of a closed (but not persistable) window, in this case `FlushHandle::flush` drops the window entirely. 

Whilst correct this can cause a mismatch between the state of the system described by the PartitionCheckpoint, and the actual state after the persistence. Namely it is possible for the PartitionCheckpoint to think there are remaining unpersisted writes when there aren't. 

Subsequent persist operations to other partitions, will encode this in the DatabaseCheckpoint that they generate. This then causes a sanity check to fail on restart, as the incorrect PartitionCheckpoint will say that writes to that partition remain to be persisted, but the last DatabaseCheckpoint will say we've fully persisted up to a min sequence number that is greater than the min in the PartitionCheckpoint.

When generating the sequence number for the PersistenceWindow, the system should take into account that any "covered" closed windows will also be flushed entirely.

### PR DESCRIPTION
**Pull request by crepererum**
This fixes an edge case where the speculated sequence ranges that can be
obtained from flush handles do not account for overlapping windows. The
symptom being that the resulting partition checkpoint marked sequence
numbers as unpersisted that where already persisted.

Fixes #2206.

### CODE REVIEW

File: persistence_windows/src/persistence_windows.rs [hunk 1]
```diff
@@ -398,6 +411,10 @@ impl PersistenceWindows {
     }
 }
 
+fn new_min_time_from_persistable(persistable: &Window) -> DateTime<Utc> {
```
Comment (alamb) [inline persistence_windows/src/persistence_windows.rs:414]: Can we add a doc comment please (explaining the rationale for the return value of this function)?

File: persistence_windows/src/persistence_windows.rs [hunk 2]
```diff
@@ -238,20 +239,25 @@ impl PersistenceWindows {
         }
     }
 
+    /// Returns the sequence number range of unpersisted writes described by this instance.
```
Comment (alamb) [inline persistence_windows/src/persistence_windows.rs:242]: I like how the public API is now less confusing (can't pass in `skip`)

File: persistence_windows/src/persistence_windows.rs [hunk 3]
```diff
@@ -1472,4 +1491,41 @@ mod tests {
             ]
         );
     }
+
+    #[test]
+    fn test_regression_2206() {
```
Comment (alamb) [inline persistence_windows/src/persistence_windows.rs:1496]: "regression 2206" -- sounds like a science fiction (or maybe horror) movie title 😆

File: persistence_windows/src/persistence_windows.rs [hunk 4]
```diff
@@ -1472,4 +1491,41 @@ mod tests {
...
+            now,
+        );
+
+        // persist
+        let handle = w.flush_handle(now).unwrap();
+        let ckpt = handle.checkpoint();
+        w.flush(handle);
+
+        // speculated checkpoint should be correct
+        let ckpt_sequencer_numbers: BTreeMap<_, _> = ckpt.sequencer_numbers_iter().collect();
```
Comment (alamb) [inline persistence_windows/src/persistence_windows.rs:1528]: 👍

File: server/src/db/replay.rs [hunk 5]
```diff
@@ -1933,11 +1924,6 @@ mod tests {
         }
         .run()
         .await;
-
-        assert_contains!(
```
Comment (alamb) [inline server/src/db/replay.rs:1937]: Maybe we should change these asserts to `assert_not_contains!`? But on the other hand, given there is a regression test now specifically for this case, perhaps it is not needed.

**Review by alamb — APPROVED** [review]

File: persistence_windows/src/persistence_windows.rs [hunk 6]
```diff
@@ -238,20 +239,25 @@ impl PersistenceWindows {
...
     ) -> BTreeMap<u32, OptionalMinMaxSequence> {
         if self.is_empty() {
             Default::default()
         }
 
-        let skip = match skip_persistable {
-            true if self.persistable.is_some() => 1,
-            _ => 0,
+        let (skip, min_time) = match (skip_persistable, self.persistable.deref()) {
+            (true, Some(persistable)) => (1, Some(new_min_time_from_persistable(persistable))),
```
Comment (tustvold) [inline persistence_windows/src/persistence_windows.rs:259]: FWIW it would also be correct to just call this flush_time, and drop any windows with a max time <= it, instead of the +1 dance which only exists for updating the min time in the windows. Doesn't matter hugely though

**Review by tustvold — APPROVED** [review]
LGTM :+1:

File: persistence_windows/src/persistence_windows.rs (hunk 1 above)
Comment (crepererum) [reply persistence_windows/src/persistence_windows.rs:415]: done

File: server/src/db/replay.rs (hunk 5 above)
Comment (crepererum) [reply server/src/db/replay.rs:1937]: done

File: persistence_windows/src/persistence_windows.rs (hunk 6 above)
Comment (crepererum) [reply persistence_windows/src/persistence_windows.rs]: done
