### PR TITLE
fix: Switch `list_database_names` to `get_namespaces`

### LINKED ISSUE #4478: Switch still-relevant uses of management list_database_names to namespace service get_namespaces
These:

- [x] ~~ioxd_database/src/lib.rs~~ these are `run database`, which is [getting removed](https://github.com/influxdata/influxdb_iox/issues/4474)

```
446:        client.list_database_names().await.unwrap();
469:        b3_tracing_client.list_database_names().await.unwrap();
474:            .list_database_names()
647:            .list_database_names()
```

- [x] influxdb_iox/src/commands/sql/repl.rs

```
62:            .list_database_names()
```

- [x] influxdb_iox/src/commands/sql/observer.rs

```
118:        .list_database_names()
```

- [x] ~~influxdb_iox/src/commands/database.rs~~ This is in the `database list` CLI command, which is [getting removed](https://github.com/influxdata/influxdb_iox/issues/4474)

```
351:                let names = client.list_database_names().await?;
```

need to be changed to use https://github.com/influxdata/influxdb_iox/blob/b6af3964985d681902d707acd1ffd65982fe5739/ioxd_querier/src/rpc/namespace.rs#L38 before removing list_database_names

### PR DESCRIPTION
**Pull request by carols10cents**
Closes #4478.

### CODE REVIEW

File: influxdb_iox/src/commands/sql/observer.rs [hunk 1]
```diff
@@ -102,22 +91,19 @@ async fn load_remote_system_tables(
...
 ) -> Result<()> {
     // all prefixed with "system."
-    let table_names = vec![
-        "chunks",
-        "chunk_columns",
-        "columns",
-        "operations",
-        "queries",
-    ];
+    let table_names = vec!["queries"];
```
Comment (alamb) [inline influxdb_iox/src/commands/sql/observer.rs:94]: 👍

**Review by alamb — APPROVED** [review]
looks (great) to me! Thank you @carols10cents
