### PR TITLE
fix: unambigious bucket/org to DB mappings

### LINKED ISSUE #436: org/bucket namespace collision
This code has the same output for `org="org_a", bucket="bucket"` and `org="org", bucket="a_bucket"`:

https://github.com/influxdata/influxdb_iox/blob/141527425d4d7a460d33a1f3ee346addeda9239b/storage/src/lib.rs#L126-L132

This leads to writes to distinct databases ending up in the same database.

### PR DESCRIPTION
**Pull request by domodwyer**
Previously the $ORG and $BUCKET was joined as:

	$ORG + "_" + $BUCKET

Which is fine unless either $ORG or $BUCKET includes a "_", such as:

	$ORG = "org_a"
	$BUCKET = "bucket"

	and

	$ORG = "org"
	$BUCKET = "a_bucket"

This change continues to join $ORG and $BUCKET with an underscore, but
disallows underscores in either $ORG or $BUCKET. It appears these values
are non-zero u64s in the gRPC protocol converted to their base-10 string
representations for the DB name, so this seems safe to enforce.

In addition, this change introduces a `DatabaseName` type to avoid
passing bare strings around, and allow consuming code to ensure only
valid database names are provided at compile type. This type works with
both owned & borrowed content so doesn't force a string copy where we
can avoid it, and derefs to `str` to make it easier to use with existing
code.

I've been minimally invasive in pushing the `DatabaseName` through the
existing code and figured I'd see what the sentement is first.
Candidates for conversion from `str` to `DatabaseName` that seem to make
sense to me include:

- `DatabaseStore` trait
- `RemoteServer` trait
- Others? Basically anywhere other than the "edge" API inputs

Fixes #436 (thanks @zeebo)

### CODE REVIEW

File: data_types/src/database_name.rs [hunk 1]
```diff
@@ -0,0 +1,147 @@
+use snafu::Snafu;
+use std::{borrow::Cow, ops::Range};
+
+/// Length constraints for a database name.
+///
+/// A `Range` is half open covering [1, 64)
+const LENGTH_CONSTRAINT: Range<usize> = 1..64;
```
Comment (domodwyer) [inline data_types/src/database_name.rs:7]: Appropriate length constraints?

**Comment by domodwyer** [comment]
I'm still figuring out the best places for things to live - please let me know if anything should be moved around! 👍

File: data_types/src/database_name.rs [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+#[derive(
+    Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize, serde::Deserialize,
+)]
+pub struct DatabaseName<'a>(Cow<'a, str>);
+
+impl<'a> DatabaseName<'a> {
+    pub fn new<T: Into<Cow<'a, str>>>(name: T) -> Result<Self, DatabaseNameError> {
+        let name: Cow<'a, str> = name.into();
+
+        if !LENGTH_CONSTRAINT.contains(&name.len()) {
```
Comment (alamb) [inline data_types/src/database_name.rs:56]: I doubt it matters, but I wonder if this actually has to do 64 comparisons to `len()` on valid database names? I wonder if checking `name.len() > 0 && name.len() <= 64` might be faster (and perhaps easier to read)

File: data_types/src/database_name.rs (hunk 1 above)
Comment (alamb) [reply data_types/src/database_name.rs:7]: Seems reasonable to me

**Review by alamb — APPROVED** [review]
Thanks @domodwyer  - I think I learned more Rust patterns just reading this PR!

The only thing I didn't see, that I would like to see is a test that actually tries to access a database using a name that contains `_` -- aka test this code path: https://github.com/influxdata/influxdb_iox/pull/521/files#diff-48d27698cc708c7efe770fd897e4885efaa0a15cae30d54936068603ba03bbd9R32

Maybe I missed it.

The rationale for adding such a test is mostly to document the expected behavior (error) and protect against regressions, not that I think the code won't work as written.

File: data_types/src/database_name.rs (hunk 2 above)
Comment (domodwyer) [reply data_types/src/database_name.rs:56]: I don't think this is the case - the `Range` is generic over an `Idx` which has `PartialOrd` bounds so I would expect it to do > and < checks internally. I'll double check though!

Comment (domodwyer) [reply data_types/src/database_name.rs:56]: Yep looks sensible: https://doc.rust-lang.org/stable/src/core/ops/range.rs.html#717-731 👍

File: src/server.rs [hunk 3]
```diff
@@ -1,2 +1,45 @@
...
+    #[snafu(display("Invalid database name: {}", source))]
+    InvalidDatabaseName { source: DatabaseNameError },
+}
+
+/// Map an InfluxDB 2.X org & bucket into an IOx DatabaseName.
+///
+/// This function ensures the mapping is unambiguous by requiring both `org` and
+/// `bucket` to not contain the `_` character in addition to the [`DatabaseName`]
+/// validation.
+pub(crate) fn org_and_bucket_to_database<'a, O: AsRef<str>, B: AsRef<str>>(
```
Comment (domodwyer) [inline src/server.rs:25]: I have forgotten to add tests for this - thanks @alamb!

File: data_types/src/database_name.rs (hunk 1 above)
Comment (e-dard) [inline data_types/src/database_name.rs:7]:
```suggestion
/// A `Range` is half open covering [1, 64]
const LENGTH_CONSTRAINT: RangeInclusive<usize> = 1..=64;
```

A maximum length of `63` characters feels a bit odd to me.

File: data_types/src/database_name.rs [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+const LENGTH_CONSTRAINT: Range<usize> = 1..64;
+
+/// Database name validation errors.
+#[derive(Debug, Snafu)]
+pub enum DatabaseNameError {
+    #[snafu(display(
+        "Database name {} length must be between {} and {} characters",
+        name,
+        LENGTH_CONSTRAINT.start,
+        LENGTH_CONSTRAINT.end
```
Comment (e-dard) [inline data_types/src/database_name.rs:16]:
```suggestion
        LENGTH_CONSTRAINT.start(),
        LENGTH_CONSTRAINT.end()
```

(`RangeInclusive` doesn't expose these as fields).

File: data_types/src/database_name.rs [hunk 5]
```diff
@@ -0,0 +1,147 @@
+use snafu::Snafu;
+use std::{borrow::Cow, ops::Range};
```
Comment (e-dard) [inline data_types/src/database_name.rs:2]:
```suggestion
use std::{borrow::Cow, ops::RangeInclusive};
```

**Review by pauldix — COMMENTED** [review]
This seems sensible to me. Although I'd be interested in hearing @carols10cents and @shepmaster comment on the overall pattern.

**Review by e-dard — APPROVED** [review]
This LGTM :-)

Though I wonder if `DatabaseName` can't just own a `String`. I can't imagine that we would need to create a `DatabaseName` much and wherever we needed a `&str` we would have it via `deref`.

**Comment by pauldix** [comment]
@e-dard yeah, that was what I was wondering. What's the advantage of doing it this way vs. just having: `type DatabaseName = String`?

**Comment by domodwyer** [comment]
The `Cow` vs. `String` thing is to allow zero-cost usage with methods like `query_local(db_name: &str)` [here](https://github.com/influxdata/influxdb_iox/blob/main/server/src/server.rs#L219) - we're given a str, potentially from some borrowed source like a network request buffer and without the CoW we would have to clone the `str` into a `String` for every call. 

Not a problem worth solving if we're only ever doing one call per request for example, but if we have any code paths that do one request -> many calls with `str`, then it's probably worth doing - I'm not sure if we do this anywhere though!

**Comment by e-dard** [comment]
@domodwyer yeah that was my assumption - that we probably need a database name one or a few times per request, but not more.

File: data_types/src/database_name.rs (hunk 1 above)
Comment (domodwyer) [reply data_types/src/database_name.rs:7]: Yeah it is weird! I took it from the [AWS bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) docs but we don't need to worry about that I think for DB names (@pauldix ?)

Comment (e-dard) [reply data_types/src/database_name.rs:7]: oh ok I didn't think there was precident for this 😂

Comment (pauldix) [reply data_types/src/database_name.rs:7]: Yeah, we don't need to worry about this for db names. The structure is:
```
<bucket>/<writer id>/<database name>/...
```
The database name is part of the file path for any object inside a bucket. Your bucket would likely be called something like `iox-production` or something like that.

File: data_types/src/database_name.rs (hunk 2 above)
Comment (alamb) [reply data_types/src/database_name.rs:56]: Like I said -- I learn something new every day -- thanks!

File: server/src/server.rs [hunk 6]
```diff
@@ -201,32 +193,38 @@ impl<M: ConnectionManager> Server<M> {
...
 
+        let db_name = DatabaseName::new(db_name).context(InvalidDatabaseName)?;
         let db = self
             .config
             .databases
-            .get(db_name)
-            .context(DatabaseNotFound { db_name })?;
+            .get(&db_name)
+            .context(DatabaseNotFound {
+                db_name: db_name.to_string(),
```
Comment (carols10cents) [inline server/src/server.rs:202]: This will allocate a new string whether or not the error happens. `SNAFU`'s `context` calls `into` in a closure, so it's better to pass references here. Rust needs a little help figuring out the deref coercion; this works for me: 

```suggestion
                db_name: &*db_name,
```

File: server/src/server.rs [hunk 7]
```diff
@@ -201,32 +193,38 @@ impl<M: ConnectionManager> Server<M> {
...
-            .get(db_name)
-            .context(DatabaseNotFound { db_name })?;
-
-        let buff = db
-            .local_store
-            .as_ref()
-            .context(NoLocalBuffer { db: db_name })?;
+            .get(&db_name)
+            .context(DatabaseNotFound {
+                db_name: db_name.to_string(),
```
Comment (carols10cents) [inline server/src/server.rs:222]: Same here:

```suggestion
                db_name: &*db_name,
```

File: server/src/server.rs [hunk 8]
```diff
@@ -201,32 +193,38 @@ impl<M: ConnectionManager> Server<M> {
...
+            })?;
+
+        let buff = db.local_store.as_ref().context(NoLocalBuffer {
+            db: db_name.to_string(),
```
Comment (carols10cents) [inline server/src/server.rs:226]: And here:

```suggestion
            db: &*db_name,
```

File: server/src/server.rs [hunk 9]
```diff
@@ -79,7 +77,7 @@ pub struct Server<M: ConnectionManager> {
 struct Config {
     // id is optional because this may not be set on startup. It might be set via an API call
     id: Option<u32>,
-    databases: BTreeMap<String, Db>,
+    databases: BTreeMap<DatabaseName<'static>, Db>,
```
Comment (carols10cents) [inline server/src/server.rs:80]: The first time I looked at this I thought this `'static` wasn't what we would want here, but then I saw that you're always creating owned `String`s to go in here, and that's exactly what you want for this case where the `Config` outlives the call to `create_database`, and `'static` here enforces that :) Nice!

File: server/src/server.rs [hunk 10]
```diff
@@ -420,12 +418,8 @@ mod tests {
                 ..Default::default()
             };
             let got = server.create_database(name, rules).await.unwrap_err();
-            if let Error::InvalidDatabaseName { db_name: got } = got {
-                if got != name {
-                    panic!(format!("expected name {} got {}", name, got));
-                }
-            } else {
-                panic!("unexpected error");
+            if !matches!(got, Error::InvalidDatabaseName { source: _s }) {
```
Comment (carols10cents) [inline server/src/server.rs:421]: This could be a bit shorter as:

```suggestion
            if !matches!(got, Error::InvalidDatabaseName { .. }) {
```

since we're ignoring all the fields.

File: src/server.rs [hunk 11]
```diff
@@ -1,2 +1,72 @@
...
+) -> Result<DatabaseName<'a>, OrgBucketMappingError> {
+    const SEPARATOR: char = '_';
+
+    // Ensure neither the org, nor the bucket contain the separator character.
+    if org.as_ref().chars().any(|c| c == SEPARATOR)
+        || bucket.as_ref().chars().any(|c| c == SEPARATOR)
+    {
+        return InvalidBucketOrgName {
+            bucket_name: bucket.as_ref().to_string(),
+            org: org.as_ref().to_string(),
```
Comment (carols10cents) [inline src/server.rs:37]: Same here:

```suggestion
            bucket_name: bucket.as_ref(),
            org: org.as_ref(),
```

File: src/server.rs [hunk 12]
```diff
@@ -1,2 +1,72 @@
...
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+
+    #[test]
+    fn test_org_bucket_map_db_ok() {
+        let got = org_and_bucket_to_database("org", "bucket").expect("failed on valid DB mapping");
+
+        assert_eq!(got.to_string(), "org_bucket");
```
Comment (carols10cents) [inline src/server.rs:55]: I realize this is just test code, but this could be:

```suggestion
        assert_eq!(&*got, "org_bucket");
```

File: src/server/rpc/storage.rs [hunk 13]
```diff
@@ -785,11 +786,9 @@ impl SetRange for PredicateBuilder {
     }
 }
 
-fn get_database_name(input: &impl GrpcInputs) -> Result<String, Status> {
-    Ok(org_and_bucket_to_database(
-        input.org_id()?,
-        &input.bucket_name()?,
-    ))
+fn get_database_name<'a>(input: &impl GrpcInputs) -> Result<DatabaseName<'a>, Status> {
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:789]: I think this actually wants to use `'static` too:

```suggestion
fn get_database_name(input: &impl GrpcInputs) -> Result<DatabaseName<'static>, Status> {
```

Otherwise the `'a` is saying the output lifetime is tied to something that comes out of nowhere (it's not tied to any of the input parameters). This compiles because the only lifetime that *could* satisfy this constraint, and the only lifetime that is actually used in practice, is `'static` (aka owned `String`s that don't have any references)

File: src/server/rpc/storage.rs [hunk 14]
```diff
@@ -813,19 +812,21 @@ where
     let plan = db_store
         .db(&db_name)
         .await
-        .context(DatabaseNotFound { db_name: &db_name })?
+        .context(DatabaseNotFound {
+            db_name: db_name.to_string(),
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:816]: :)

```suggestion
            db_name: &*db_name,
```

File: src/server/rpc/storage.rs [hunk 15]
```diff
@@ -813,19 +812,21 @@ where
...
+        })?
         .table_names(predicate)
         .await
         .map_err(|e| Error::ListingTables {
-            db_name: db_name.clone(),
+            db_name: db_name.to_string(),
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:821]: This one is actually fine because it's in a closure (and isn't using SNAFU anyway)

File: src/server/rpc/storage.rs [hunk 16]
```diff
@@ -861,16 +862,15 @@ where
         })?
         .build();
 
-    let db = db_store
-        .db(&db_name)
-        .await
-        .context(DatabaseNotFound { db_name: &db_name })?;
+    let db = db_store.db(&db_name).await.context(DatabaseNotFound {
+        db_name: db_name.to_string(),
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:866]:
```suggestion
        db_name: &*db_name,
```

File: src/server/rpc/storage.rs [hunk 17]
```diff
@@ -916,16 +916,15 @@ where
...
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:920]: I hope all these comments come across as helpful, not pedantic ❤️ 

```suggestion
        db_name: &*db_name,
```

File: src/server/rpc/storage.rs [hunk 18]
```diff
@@ -975,16 +974,15 @@ where
...
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:978]:
```suggestion
        db_name: &*db_name,
```

File: src/server/rpc/storage.rs [hunk 19]
```diff
@@ -1058,16 +1056,15 @@ where
...
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:1060]:
```suggestion
        db_name: &*db_name,
```

File: src/server/rpc/storage.rs [hunk 20]
```diff
@@ -1119,16 +1116,15 @@ where
...
```
Comment (carols10cents) [inline src/server/rpc/storage.rs:1120]:
```suggestion
        db_name: &*db_name,
```

**Review by carols10cents — CHANGES_REQUESTED** [review]
A few suggestions and thoughts :)

**Comment by carols10cents** [comment]
In general for cases like this, I'd say go with the `String` approach first and then profile/benchmark to see if the optimization would be worth the time and complexity in practice. But now that it's done, I think this is fine!

File: src/server/rpc/storage.rs (hunk 17 above)
Comment (domodwyer) [reply src/server/rpc/storage.rs:920]: They're awesome! thanks 🥕

File: data_types/src/database_name.rs [hunk 21]
```diff
@@ -0,0 +1,147 @@
+use snafu::Snafu;
+use std::{borrow::Cow, ops::RangeInclusive};
+
+/// Length constraints for a database name.
+///
+/// A `Range` is half open covering [1, 64]
```
[the remark this answers is not in the document]
Comment (domodwyer) [reply data_types/src/database_name.rs:6]: I was fully set up by @e-dard

File: server/src/server.rs (hunk 6 above)
Comment (domodwyer) [reply server/src/server.rs:202]: Ah nice - the closure thing is pretty neat!

File: src/server/rpc/storage.rs (hunk 13 above)
Comment (domodwyer) [reply src/server/rpc/storage.rs:789]: Nice - that makes total sense.

Thanks!

**Comment by domodwyer** [comment]
Yeah I took the stance that my change should not impact overall performance of the system, and couldn't completely figure out the access patterns this would be subject to - I guess default-to-simple should have won here!

File: src/server/rpc/storage.rs (hunk 17 above)
Comment (alamb) [reply src/server/rpc/storage.rs]: 🥕  indeed -- @carols10cents  I think has taught me 95% of what I know about Rust. Getting her comments on a PR is like a personal Rust tutor. 💯  thanks again @carols10cents
