### PR TITLE
fix: Escape non-printable characters in logfmt

### LINKED ISSUE #1791: logfmt doesn't escape NUL chars
__Steps to reproduce:__

```console
$ kubectl logs deploy/iox-test -c iox | head -n 1| hexdump -C
00000000  6c 65 76 65 6c 3d 69 6e  66 6f 20 6d 73 67 3d 22  |level=info msg="|
00000010  49 6e 66 6c 75 78 44 42  20 49 4f 78 20 73 65 72  |InfluxDB IOx ser|
00000020  76 65 72 20 73 74 61 72  74 69 6e 67 22 20 67 69  |ver starting" gi|
00000030  74 5f 68 61 73 68 3d 64  64 34 34 37 64 39 34 30  |t_hash=dd447d940|
00000040  63 63 61 66 33 62 30 34  64 62 62 65 64 61 38 32  |ccaf3b04dbbeda82|
00000050  64 34 38 62 61 66 36 63  39 36 64 31 64 38 62 20  |d48baf6c96d1d8b |
00000060  6e 75 6d 5f 63 70 75 73  3d 38 20 62 75 69 6c 64  |num_cpus=8 build|
00000070  5f 6d 61 6c 6c 6f 63 5f  63 6f 6e 66 3d 00 20 74  |_malloc_conf=. t|
00000080  61 72 67 65 74 3d 22 69  6e 66 6c 75 78 64 62 5f  |arget="influxdb_|
00000090  69 6f 78 3a 3a 69 6e 66  6c 75 78 64 62 5f 69 6f  |iox::influxdb_io|
000000a0  78 64 22 20 6c 6f 63 61  74 69 6f 6e 3d 22 73 72  |xd" location="sr|
000000b0  63 2f 69 6e 66 6c 75 78  64 62 5f 69 6f 78 64 2e  |c/influxdb_ioxd.|
000000c0  72 73 3a 31 31 30 22 20  74 69 6d 65 3d 31 36 32  |rs:110" time=162|
000000d0  34 34 35 34 36 32 31 33  37 33 34 37 34 36 34 35  |4454621373474645|
000000e0  0a                                                |.|
000000e1
```

__Actual behaviour:__
Describe What actually happened.

Zoom in and you'll se an actual NUL (0) character in the log output
```
00000070  5f 6d 61 6c 6c 6f 63 5f  63 6f 6e 66 3d 00 20 74  |_malloc_conf=. t|
                                                  ^^
```

__Expected behaviour:__

Some sort of escaping of the NUL character; e.g. `\0` or `\u{0}`

### PR DESCRIPTION
**Pull request by mkmik**
The is no specification logfmt, most implementations only unescape `\"` and leave
`\n` as is when parsing. Some implementations like go-logfmt do escape newlines as `\n` (and other chars
according to Go's escaping rules).

This PR just escapes non-printable characters using rust's string literal rules; they are not perfect but
they don't seem to be worse than other players.

(If this bites us some more we will probably be better of switching to json log output format and then equip ourselves with some simple shell scripts to reformat the logs on the fly while we're streaming them from k8s)

As a bonus point, this effectively simplifies the escaping code, possibly also speeding it up a bit
since it doesn't have to call replace twice (although I don't know what magic would the rust compiler have done to this double replace).

Closes #1791

Closes influxdata/k8s-iox#8

CC: @primeroz

### CODE REVIEW

**Review by crepererum — APPROVED** [review]

File: logfmt/src/lib.rs [hunk 1]
```diff
@@ -376,4 +375,16 @@ mod test {
...
+
+    #[test]
+    fn quote_not_printable() {
+        assert_eq!(quote_and_escape("foo\nbar"), r#""foo\nbar""#);
+        assert_eq!(quote_and_escape("foo\r\nbar"), r#""foo\r\nbar""#);
+        assert_eq!(quote_and_escape("foo\0bar"), r#""foo\u{0}bar""#);
+    }
+
+    #[test]
+    fn not_quote_unicode_unnecessarily() {
```
Comment (alamb) [inline logfmt/src/lib.rs:387]: 👍

**Review by alamb — APPROVED** [review]
looks reasonable to me 👍
