### PR TITLE
fix: account for memory in `GapFillStream`

### LINKED ISSUE #7048: Update `GapFill` oerator to use DataFusion's memory manager
This will make it less likely to cause an OOM and instead return an error gracefully.

Overview of gap filling implementation issues: https://github.com/influxdata/influxdb_iox/issues/6594

PR that created `GapFillStream`
https://github.com/influxdata/influxdb_iox/pull/7037

Examples of accounting for memory:
- https://github.com/apache/arrow-datafusion/pull/4820
- https://github.com/apache/arrow-datafusion/pull/4405

### PR DESCRIPTION
**Pull request by wolffcm**
Closes #7048.

These changes update `GapFillStream` to report memory usage when buffering input records and creating output, and includes associated tests to show it all works right.

### CODE REVIEW

**Review by stuartcarnie — APPROVED** [review]
Looks good.

Very nice that we have memory accounting built-in.

File: iox_query/src/exec/gapfill.rs [hunk 1]
```diff
@@ -1230,6 +1234,28 @@ mod test {
...
+            input_batch_size,
+        };
+        let params = get_params_ms(&batch, 25, Some(975), 1_125);
+        let tc = TestCase {
+            test_records: batch,
+            output_batch_size,
+            params,
+        };
+        let result = tc.run_with_memory_limit(1).await;
+        assert_error!(result, DataFusionError::ResourcesExhausted(_));
```
Comment (alamb) [inline iox_query/src/exec/gapfill.rs:1256]: 👍

**Review by alamb — COMMENTED** [review]
LGTM -- thanks @wolffcm

File: iox_query/src/exec/gapfill/stream.rs [hunk 2]
```diff
@@ -151,6 +164,9 @@ impl Stream for GapFillStream {
             Ok((output_batch, remaining_input_batch)) => {
                 self.buffered_input_batches.push(remaining_input_batch);
                 assert_eq!(1, self.buffered_input_batches.len());
+
+                self.reservation
```
Comment (alamb) [inline iox_query/src/exec/gapfill/stream.rs:168]: I see now what you are saying there about slice vs concat and the challenge of accounting between them

I wonder if using something like 

https://docs.rs/arrow/34.0.0/arrow/array/struct.ArrayData.html#method.get_slice_memory_size

While perhaps less accurate, would be easier to reason about 🤔

Comment (wolffcm) [reply iox_query/src/exec/gapfill/stream.rs:168]: > I wonder if using something like
> https://docs.rs/arrow/34.0.0/arrow/array/struct.ArrayData.html#method.get_slice_memory_size
> While perhaps less accurate, would be easier to reason about 🤔

Now that I have it sorted in m head, I can reason about it okay. I think it would be less intuitive to use something less accurate, it would hide what's going on under the hood even more?

I've never seen memory accounting done quite like this. I don't really have a sense of how accurate the accounting needs to be. Stability, operating cost and engineering effort are all at play here and I can see there's lots of tradeoffs to be had.

It seems like it might be a common enough pattern where records are accessed in a FIFO way that some kind of abstraction could be of use.

Comment (alamb) [reply iox_query/src/exec/gapfill/stream.rs:168]: > I've never seen memory accounting done quite like this. I don't really have a sense of how accurate the accounting needs to be. Stability, operating cost and engineering effort are all at play here and I can see there's lots of tradeoffs to be had.

I agree

> I don't really have a sense of how accurate the accounting needs to be

I think it needs to be "in the ballpark / right order of magnitude" -- the idea is to avoid OOMs but without the overhead of annotating every single allocation site. So that typically means annotating the "big" ones and ensuring the medium ones are good enough.

> It seems like it might be a common enough pattern where records are accessed in a FIFO way that some kind of abstraction could be of use.

I agree it would be useful
