### PR TITLE
fix: Do not send GroupFrames in response to read_window_aggregate

### LINKED ISSUE #490: bug: read_window_group produces " duration used as an interval cannot be zero" when evaluting group aggregate
__Steps to reproduce:__
Reproducer:
* point telegraph at a local delorean server and run the following flux query from the UI

```
from(bucket: "devbucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)
  |> yield(name: "sum")
```

__Expected behaviour:__
Much glorious data is produced

__Actual behaviour:__

Produces the following error in the UI (comes from IOx):

```
  query error: rpc error: code = InvalidArgument desc = Error converting read_aggregate_window aggregate definition 'aggregate: [Aggregate { r#type: Sum }], window_every: 0, offset: 0, window: Some(Window { every: Some(Duration { nsecs: 10000000000, months: 0, negative: false }), offset: Some(Duration { nsecs: 0, months: 0, negative: false }) })': Error parsing window bounds duration 'window.offset': duration used as an interval cannot be zero
```

__Environment info:__

* Please provide the command you used to build the project, including any `RUSTFLAGS`.
* System info: Run `uname -srm` or similar and copy the output here (we want to know your OS, architecture etc).
* If you're running IOx in a containerised environment then details about that would be helpful.
* Other relevant environment details: disk info, hardware setup etc.

__Config:__
Copy any non-default config values here or attach the full config as a gist or file.

__Logs:__
Include snippet of errors in logs or stack traces here.
Sometimes you can get useful information by running the program with the `RUST_BACKTRACE=full` environment variable.
Finally, the IOx server has a `-vv` for verbose logging.

### PR DESCRIPTION
**Pull request by alamb**
This is fix 2 of 2 needed to get read_window_aggregate working correctly

Closes #490

- [x] Allow empty `offset` windows (https://github.com/influxdata/influxdb_iox/pull/493
- [x] Don't send back GroupFrames in responses (this PR)

# Background:

Despite even writing a mini spec, I still ended up creating a plan that sent back `GroupFrame` responses for read_window_aggregate, which is not correct

This PR adds a hack / special case to not do this.

I am also working a PR with a much more significant refactoring to unify / remove the duplication between the Group / non Grouped query execution path and remove this special case but figured I would get this one up so that I had it ready and so I can demonstrate the the functionality working.

### CODE REVIEW

File: tests/end-to-end.rs [hunk 1]
```diff
@@ -534,10 +534,8 @@ async fn test_read_window_aggregate(
         .collect();
 
     let expected_frames = vec![
-        "GroupFrame, tag_keys: city,state, partition_key_vals: Boston,MA",
```
Comment (alamb) [inline tests/end-to-end.rs:537]: The lack of group frames here is what needs to happen to have IDPE run the appropriate flux queries

**Review by e-dard — APPROVED** [review]
