### PR TITLE
fix: persist deadlock (#2045)

### LINKED ISSUE #2045: Persist Deadlock
One of the query servers locked up in tools, with all the tokio threads in the primary pool stuck trying to acquire locks. The full thread dump can be found here - [thread-dump-deadlock.txt](https://github.com/influxdata/influxdb_iox/files/6839944/thread-dump-deadlock.txt).

There are two sets of threads blocked on different partition locks

* Threads 2, 6 are blocked on partition lock "139814035056144"
* Threads 3, 4, 7, 9 are blocked on partition lock "139816278737936"

Threads 5, 8 are both blocked on different chunks locks, whilst holding a read lock on a single partition. One in `Partition::open_chunk` and the other in `LifecyclePolicy<M>::maybe_cleanup_failed`. Assuming no leaked locks, these must therefore be holding locks on different partitions.

Thread 4 and 6 are both on the following line

```
#13 0x000055d71a365391 in server::db::lifecycle::persist::persist_chunks::{{closure}} () at server/src/db/lifecycle/persist.rs:129
```

Looking at the code for this

```
let mut partition_write = partition.write();
            for id in chunk_ids {
                partition_write.force_drop_chunk(id)
            }

            // Upsert remainder to catalog
            if remainder.rows() > 0 {
                partition_write.create_rub_chunk(remainder, Arc::clone(&schema));
            }

            assert!(to_persist.rows() > 0);

            let to_persist = LockableCatalogChunk {
                db: Arc::clone(&db),
                chunk: partition_write.create_rub_chunk(to_persist, schema),
            };
            let to_persist = to_persist.write();

            // Drop partition lock guard after locking chunk
            std::mem::drop(partition_write);

            let partition = LockableCatalogPartition::new(db, partition);
            let partition = partition.write();
```

It is trying to acquire an exclusive lock on the partition whilst holding an exclusive lock on the chunk - this will deadlock. It is unclear why it doesn't just keep the partition_write around. This code was introduced in https://github.com/influxdata/influxdb_iox/pull/1972/files#diff-7525ab2db0582abcead1272df41d4844d9f87f0ce359bb3d04a0bf45732cd72fR128

We should fix this deadlock, and perhaps bring forward plans to encapsulate the locking into a transaction object to avoid this issue in future

### PR DESCRIPTION
**Pull request by tustvold**
Closes #2045

Trying to acquire a partition write lock whilst holding a write lock on a chunk, will likely result in a deadlock. There is a plan to encapsulate these locks in a transaction type, perhaps that work should be brought forward to avoid this kind of issue... :thinking:

### CODE REVIEW

File: server/src/db/lifecycle/persist.rs [hunk 1]
```diff
@@ -117,18 +118,12 @@ pub fn persist_chunks(
             assert!(to_persist.rows() > 0);
 
             let to_persist = LockableCatalogChunk {
-                db: Arc::clone(&db),
+                db,
                 chunk: partition_write.create_rub_chunk(to_persist, schema),
             };
             let to_persist = to_persist.write();
 
-            // Drop partition lock guard after locking chunk
```
Comment (alamb) [inline server/src/db/lifecycle/persist.rs:125]: it is strange -- I see no reason this code was here (why did it drop the lock and reacquire it?)

**Review by alamb — APPROVED** [review]
As I understand it, the theory is that by dropping the partition lock and reacquiring it, we have effectively inverted the lock acquisition order which should (implicitly) be
1. Partition
2. Chunk

And instead had code dropped and reacquired the partition lock such that it was:
1. Chunk
2. Partition

Which is the classical way to get intermittent deadlocks when acquiring multiple locks

I agree this is the kind of thing that a `CatalogTransaction` type interface would help avoid. I will write up a ticket

**Review by crepererum — APPROVED** [review]

**Comment by alamb** [comment]
Here is a writeup of catalog transactions https://github.com/influxdata/influxdb_iox/issues/2047
