### PR TITLE
fix: fix NaN+NULL handling in parquet stats 

### LINKED ISSUE #1576: Complete parquet statistics extraction
This is mostly a reminder for myself to get [this branch](https://github.com/influxdata/influxdb_iox/tree/crepererum/more_parquet_stats_work) merged. It was mostly blocked on upstream bugs that are now fixed. While doing so also investigate why the unique count seems to be never set as discussed [here](https://github.com/influxdata/influxdb_iox/pull/1568#discussion_r641326066).

### PR DESCRIPTION
**Pull request by crepererum**
Closes #1576.

### CODE REVIEW

File: parquet_file/src/metadata.rs [hunk 1]
```diff
@@ -454,8 +457,8 @@ fn extract_iox_statistics(
     match (parquet_stats, iox_type) {
         (ParquetStatistics::Boolean(stats), InfluxColumnType::Field(InfluxFieldType::Boolean)) => {
             Ok(Statistics::Bool(StatValues {
-                min: Some(*stats.min()),
-                max: Some(*stats.max()),
+                min: min_max_set.then(|| *stats.min()),
```
Comment (alamb) [inline parquet_file/src/metadata.rs:460]: TIL how to turn `bool` --> `Option<>` 👍

File: parquet_file/src/storage_testing.rs [hunk 2]
```diff
@@ -87,14 +87,14 @@ mod tests {
         // Now verify return results. This assert_batches_eq still works correctly without the metadata
         // We might modify it to make it include checking metadata or add a new comparison checking macro that prints out the metadata too
         let expected = vec![
-            "+------------------+---------------+---------------------------+------------------------+----------------------+----------------------+----------------------+----------------------+-------------------+--------------------+----------------+----------------------------+",
```
Comment (alamb) [inline parquet_file/src/storage_testing.rs:90]: I found looking at this diff in my local diff tool was much easier to see the differences -- they looked good to me

File: parquet_file/src/test_utils.rs [hunk 3]
```diff
@@ -398,31 +420,67 @@ pub fn make_record_batch(
...
         &format!("{}_tag_empty", column_prefix),
-        vec![vec![""], vec![""], vec!["", ""]],
+        vec![vec![Some("")], vec![Some("")], vec![Some(""), Some("")]],
+        &mut arrow_cols,
+        &mut summaries,
+        &mut schema_builder,
+    );
+    create_column_tag(
+        &format!("{}_tag_null_some", column_prefix),
+        vec![vec![None], vec![Some("bar")], vec![Some("baz"), None]],
```
Comment (alamb) [inline parquet_file/src/test_utils.rs:442]: 👍  for testing both `Some("")` and `None`

**Review by alamb — APPROVED** [review]
Thank you @crepererum
