### PR TITLE
chore: fix flaky test

### LINKED ISSUE #1641: Flaky test in end_to_end_cases::management_api::test_chunk_lifecycle
This is likely a flaky test:

https://app.circleci.com/pipelines/github/influxdata/influxdb_iox/6594/workflows/9e1349db-928a-4fd9-ab0d-2fc0ca647873/jobs/26746

```
failures:

---- end_to_end_cases::management_api::test_chunk_lifecycle stdout ----
thread 'end_to_end_cases::management_api::test_chunk_lifecycle' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `3`', tests/end_to_end_cases/management_api.rs:755:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    end_to_end_cases::management_api::test_chunk_lifecycle

test result: FAILED. 66 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.60s

error: test failed, to rerun pass '-p influxdb_iox --test end-to-end'
```

### PR DESCRIPTION
**Pull request by tustvold**
Closes #1641

### CODE REVIEW

File: tests/end_to_end_cases/management_api.rs [hunk 1]
```diff
@@ -744,15 +745,24 @@ async fn test_chunk_lifecycle() {
...
+            .await
+            .expect("listing chunks");
 
-    assert_eq!(chunks.len(), 1);
-    assert_eq!(chunks[0].storage, ChunkStorage::ReadBuffer as i32);
+        assert_eq!(chunks.len(), 1);
+        if chunks[0].storage == ChunkStorage::ReadBuffer as i32 {
+            break;
+        }
+    }
```
Comment (alamb) [inline tests/end_to_end_cases/management_api.rs:761]: The `while` condition is probably not necessary -- if you want to avoid repeating the `10` constant, I have seen @crepererum use a pattern like this to good effect:

```
loop {
...
        tokio::time::sleep(tokio::time::Duration::from_millis(200)).await;
        if start.elapsed().as_secs_f64() > 10. {
          panic!("chunk failed to transition to read buffer after 10 seconds")
        }
}

**Review by alamb — APPROVED** [review]
Thank you
